/****** Object:  Database [dba] ******/
CREATE DATABASE [dba]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dba', FILENAME = N'I:\SQLServerData\dba.mdf' , SIZE = 2033664KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dba_log', FILENAME = N'H:\SQLServerData\dba_log.ldf' , SIZE = 279296KB , MAXSIZE = 2048GB , FILEGROWTH = 16384KB )
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dba].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dba] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dba] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dba] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dba] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dba] SET ARITHABORT OFF 
GO
ALTER DATABASE [dba] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dba] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [dba] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dba] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dba] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dba] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dba] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dba] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dba] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dba] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dba] SET  DISABLE_BROKER 
GO
ALTER DATABASE [dba] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dba] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dba] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dba] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dba] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dba] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [dba] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dba] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [dba] SET  MULTI_USER 
GO
ALTER DATABASE [dba] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dba] SET DB_CHAINING OFF 
GO
ALTER DATABASE [dba] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [dba] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [dba] SET  READ_WRITE 
GO
