/****** Object:  Database [Manager_Control] ******/
CREATE DATABASE [Manager_Control] ON  PRIMARY 
( NAME = N'ManagerControl', FILENAME = N'I:\SQLServerData\Manager_Control_data.mdf' , SIZE = 20160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'ManagerControl_log', FILENAME = N'I:\SQLServerData\Manager_Control_log.ldf' , SIZE = 2560KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [Manager_Control] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Manager_Control].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [Manager_Control] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [Manager_Control] SET ANSI_NULLS ON 
GO
ALTER DATABASE [Manager_Control] SET ANSI_PADDING ON 
GO
ALTER DATABASE [Manager_Control] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [Manager_Control] SET ARITHABORT ON 
GO
ALTER DATABASE [Manager_Control] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Manager_Control] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Manager_Control] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Manager_Control] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Manager_Control] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Manager_Control] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Manager_Control] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [Manager_Control] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Manager_Control] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [Manager_Control] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Manager_Control] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Manager_Control] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Manager_Control] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Manager_Control] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Manager_Control] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Manager_Control] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Manager_Control] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Manager_Control] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Manager_Control] SET  READ_WRITE 
GO
ALTER DATABASE [Manager_Control] SET RECOVERY FULL 
GO
ALTER DATABASE [Manager_Control] SET  MULTI_USER 
GO
ALTER DATABASE [Manager_Control] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Manager_Control] SET DB_CHAINING OFF 
GO
GRANT CONNECT TO [D3J410] AS [dbo]
GO
GRANT CONNECT TO [DMS_Guest] AS [dbo]
GO
GRANT CONNECT TO [DMS_User] AS [dbo]
GO
GRANT CONNECT TO [DMSWebUser] AS [dbo]
GO
GRANT CONNECT TO [mtuser] AS [dbo]
GO
GRANT CONNECT TO [PNL\D3m480] AS [dbo]
GO
GRANT CONNECT TO [RBAC-MgrConfig_Admin] AS [dbo]
GO
GRANT CONNECT TO [svc-dms] AS [dbo]
GO
