/****** Object:  Table [dbo].[T_Mgrs] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_Mgrs](
	[M_ID] [int] IDENTITY(300,1) NOT NULL,
	[M_Name] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[M_TypeID] [int] NOT NULL,
	[M_ParmValueChanged] [tinyint] NOT NULL,
	[M_ControlFromWebsite] [tinyint] NOT NULL,
 CONSTRAINT [PK_T_Mgrs] PRIMARY KEY CLUSTERED 
(
	[M_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [IX_T_Mgrs] UNIQUE NONCLUSTERED 
(
	[M_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Index [IX_T_Mgrs_1] ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_T_Mgrs_1] ON [dbo].[T_Mgrs] 
(
	[M_Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_Mgrs]  WITH CHECK ADD  CONSTRAINT [FK_T_Mgrs_T_MgrTypes] FOREIGN KEY([M_TypeID])
REFERENCES [T_MgrTypes] ([MT_TypeID])
GO
ALTER TABLE [dbo].[T_Mgrs] CHECK CONSTRAINT [FK_T_Mgrs_T_MgrTypes]
GO
ALTER TABLE [dbo].[T_Mgrs] ADD  CONSTRAINT [DF_T_Mgrs_M_ParmValueChanged]  DEFAULT ((1)) FOR [M_ParmValueChanged]
GO
ALTER TABLE [dbo].[T_Mgrs] ADD  CONSTRAINT [DF_T_Mgrs_M_ControlFromWebsite]  DEFAULT ((0)) FOR [M_ControlFromWebsite]
GO
