/****** Object:  Table [T_ParamType] ******/
/****** RowCount: 160 ******/
SET IDENTITY_INSERT [T_ParamType] ON
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (1,'connectionstring','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (2,'username','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (3,'userpwd','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (4,'usetls','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (5,'serverport','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (6,'timeout','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (7,'passive','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (8,'restart','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (9,'workdir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (10,'machname','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (11,'zipprogram','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (12,'debuglevel','debugLevelPickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (13,'ftplogging','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (14,'maxrepetitions','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (15,'perspective','perspectivePickList','Can be client or server')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (16,'instclass','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (17,'mgractive','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (18,'testzip','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (19,'transfervol','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (20,'drives','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (21,'machnames','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (22,'bionetuser','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (23,'bionetpwd','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (24,'sleepinterval','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (25,'DSFolderExistsAction','folderExistsActionPickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (26,'mindiskspace','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (27,'toolresulttypes','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (28,'priorities','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (29,'xtprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (30,'sourcedir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (31,'fastacnstring','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (32,'performextraction','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (33,'statusfilelocation','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (34,'orgdbdir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (35,'lcqdtaloc','','The location of Extract_MSn.exe and its required DLLs; test change')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (36,'xtoutconv-dir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (37,'xtoutconv-prog','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (38,'xtoutconv-xslt','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (39,'usefilecheck','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (40,'performcal','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (41,'masicprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (42,'cluster','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (43,'bioworksversion','bioWorksVersionPickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (44,'xcalversion','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (45,'createnowindow','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (46,'numberofprocessors','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (47,'seqprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (48,'paramtemplateloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (49,'hostsfilelocation','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (50,'nodedblocation','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (51,'substatusfile','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (52,'tcpport','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (53,'configfilename','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (54,'localmgrpath','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (55,'remotemgrpath','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (56,'programfoldername','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (57,'modulename','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (58,'servername','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (59,'showinmgrctrl','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (60,'showinanmonitor','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (61,'logfilename','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (62,'brokerconnectionstring','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (64,'storedprocedure','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (65,'importdelay','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (66,'enableemail','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (67,'smtpserver','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (68,'to','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (69,'from','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (70,'subject','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (71,'deletebadxmlfiles','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (72,'deletegoodxmlfiles','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (73,'xferdir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (74,'successfolder','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (75,'failurefolder','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (77,'timevalidationtolerance','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (78,'timevalidationfolder','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (79,'ArchiveOrUpdate','archiveOrUpdatePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (80,'xmlfiledelay','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (81,'cmdtimeout','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (82,'AppendMgrNameToXferFolder','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (83,'UseDTALooping','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (85,'johns new param','TrueFalsePickList','This is just a comment.  This is a really, really long comment.  I just want to see how the display is working.')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (89,'MultiAlignprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (93,'New ParamXX','YNPickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (96,'ReAdWProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (97,'InspectDir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (98,'pythonprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (99,'ManagerUpdateRequired','TrueFalsePickList','When True, then the manager will stop picking up new jobs and will exit.  However, prior to exiting, it will call SP AckManagerUpdateRequired')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (100,'LogMemoryUsage','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (101,'MinimumMemoryUsageLogInterval','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (102,'LogStatusToBrokerDB','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (103,'BrokerDBStatusUpdateIntervalMinutes','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (104,'LogStatusToMessageQueue','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (105,'MessageQueueURI','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (106,'MessageQueueTopicMgrStatus','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (107,'DTAFolderLocation','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (108,'DTAProcessedFolderLocation','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (109,'XcalDLLPath','','The location of xrawfile2.dll and its required DLLs.  This folder also has DeconMSn.exe and deconmsnengine.dll')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (114,'FailedResultsFolderPath','','The folder to copy analysis results to when an analysis job produces results, but has a problem delivering them')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (115,'MSClusterprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (116,'ControlQueueName','','Name of message queue used for sending commands to manager')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (117,'BroadcastQueueTopic','','Message queue topic for controlling manager')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (118,'StatusMsgIncomingTopic','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (119,'StatusMsgDBUpdateInterval','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (120,'ManagerErrorCleanupMode','','0 = No auto cleanup, 1 = Attempt auto cleanup once, 2 = Auto cleanup always')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (121,'ICR2LSprogloc','','The location of ICR-2LS.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (122,'SequestNodeCountExpected','','Expected number of processing nodes on a Sequest cluster')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (123,'LCMSFeatureFinderProgLoc','','The location of the LCMS Feature Finder')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (124,'formatdbprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (125,'OMSSAprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (126,'dtatoxmlprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (127,'dtarefineryloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (128,'omssa2pepprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (129,'puttyprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (130,'puttysftpprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (131,'MSDataFileTrimmerprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (132,'AScoreprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (133,'JavaLoc','','Should be 64-bit version of Java')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (134,'MSGFLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (136,'ChameleonCachedDataFolder','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (137,'ChameleonLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (138,'HashFileLocation','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (139,'CompassXportLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (140,'ProteoWizardDir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (141,'PeptideProphetRunnerProgLoc','','The location of the Peptide Prophet Runner')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (142,'DeconToolsProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (143,'MSGFDbProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (144,'PHRPProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (145,'MSDeconvProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (146,'MSAlignProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (147,'RProgLoc','','Used by the Cyclops plugin')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (148,'CheckDataFolderCreateQueue','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (149,'SMAQCProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (150,'WorkDirMinFreeSpaceMB','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (151,'OrgDBDirMinFreeSpaceMB','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (152,'TransferDirMinFreeSpaceGB','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (153,'MD5ResultsFolderPath','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (154,'ShareConnectorType','','PRISM or DotNET')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (156,'MyEmslUpload','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (157,'MSFileInfoScannerDir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (158,'PVMProgLoc','','Folder containing PVM on Sequest clusters')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (159,'IDPickerProgLoc','','Folder containing IDPicker-related .Exe files')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (160,'PeptideListToXMLProgLoc','','Folder containing PeptideListToXML.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (161,'LipidToolsProgLoc','','Folder containing LipidTools.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (162,'MgrSettingGroupName','','Parameter group to use for this manager; points to a Ghost manager that has parameters defined in T_ParamValue')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (163,'TargetedWorkflowsProgLoc','','Folder containing TargetedWorkflowConsole.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (164,'IonMobilityMsMsProgLoc','','Folder containing IonMobilityMsMsConsole.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (165,'QuameterProgLoc','','Folder containing Quameter.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (166,'PRIDEConverterProgLoc','','Folder containing pride-converter-2.0-SNAPSHOT.jar')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (167,'MSGFPlusIndexFilesFolderPath','','Folder containing MSGF+ index files for Fasta files created from the Protein_Sequences database')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (168,'MSAlignHistoneProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (169,'MSXMLCacheFolderPath','','Folder containing cached .mzXML files')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (170,'DMSWorkflowsFolderPath','','Folder with scripts and parameter files for MAC jobs')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (171,'LLRCRunnerProgLoc','','Folder containing LLRCRunner.exe, Models_paper.Rdata, and allData_v4.Rdata')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (172,'AgilentToUIMFProgLoc','','Folder containing AgilentToUimfConverter.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (173,'MSGFPlusIndexFilesFolderPathLegacyDB','','Folder containing MSGF+ index files for Fasta files not created from the Protein_Sequences database')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (174,'PICHPCUser','','Username to use when connecting to PIC HPC')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (175,'PICHPCPassword','','Password to use when connecting to PIC HPC')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (176,'MODaProgLoc','','Path to modA')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (177,'DeconPeakDetectorProgLoc','','Path to HammerOrDeconSimplePeakDetector.exe')
SET IDENTITY_INSERT [T_ParamType] OFF
