/****** Object:  Table [T_ParamType] ******/
/****** RowCount: 202 ******/
SET IDENTITY_INSERT [T_ParamType] ON
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (1,'connectionstring',null,'Connection string to the DMS database for requesting tasks or updating status (DMS_Capture, DMS_Pipeline, or DMS5)')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (2,'username',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (3,'userpwd',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (4,'usetls','TrueFalsePickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (5,'serverport',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (6,'timeout',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (7,'passive','TrueFalsePickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (8,'restart','TrueFalsePickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (9,'workdir',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (10,'machname',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (11,'zipprogram',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (12,'debuglevel','debugLevelPickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (13,'ftplogging','TrueFalsePickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (14,'maxrepetitions',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (15,'perspective','perspectivePickList','Can be client or server')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (16,'instclass',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (17,'mgractive','TrueFalsePickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (18,'testzip','TrueFalsePickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (19,'transfervol',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (20,'drives',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (21,'machnames',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (22,'bionetuser',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (23,'bionetpwd',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (24,'sleepinterval',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (25,'DSFolderExistsAction','folderExistsActionPickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (26,'mindiskspace',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (27,'toolresulttypes',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (28,'priorities',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (29,'xtprogloc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (30,'sourcedir',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (31,'fastacnstring',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (32,'UNUSED_performextraction',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (33,'statusfilelocation',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (34,'orgdbdir',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (35,'lcqdtaloc',null,'The location of Extract_MSn.exe and its required DLLs; test change')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (36,'UNUSED_xtoutconv-dir',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (37,'UNUSED_xtoutconv-prog',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (38,'UNUSED_xtoutconv-xslt',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (39,'UNUSED_usefilecheck',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (40,'UNUSED_performcal',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (41,'masicprogloc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (42,'cluster','TrueFalsePickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (43,'bioworksversion','bioWorksVersionPickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (44,'UNUSED_xcalversion',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (45,'createnowindow','TrueFalsePickList','Obsolete / unused')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (46,'numberofprocessors',null,'Obsolete / unused')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (47,'seqprogloc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (48,'paramtemplateloc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (49,'hostsfilelocation',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (50,'nodedblocation',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (51,'UNUSED_substatusfile',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (52,'tcpport',null,'Legacy parameter')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (53,'configfilename',null,'')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (54,'localmgrpath',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (55,'remotemgrpath',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (56,'programfoldername',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (57,'modulename',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (58,'servername',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (59,'showinmgrctrl','TrueFalsePickList','Obsolete / unused')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (60,'showinanmonitor','TrueFalsePickList','Obsolete / unused')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (61,'logfilename',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (62,'brokerconnectionstring',null,'Connection string to the DMS_Pipeline database')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (64,'storedprocedure',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (65,'importdelay',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (66,'enableemail','TrueFalsePickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (67,'smtpserver',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (68,'to',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (69,'from',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (70,'subject',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (71,'deletebadxmlfiles',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (72,'deletegoodxmlfiles',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (73,'xferdir',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (74,'successfolder',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (75,'failurefolder',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (77,'timevalidationtolerance',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (78,'timevalidationfolder',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (79,'ArchiveOrUpdate','archiveOrUpdatePickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (80,'xmlfiledelay',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (81,'cmdtimeout',null,'Obsolete / unused')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (82,'AppendMgrNameToXferFolder','TrueFalsePickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (83,'UseDTALooping','TrueFalsePickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (89,'MultiAlignprogloc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (96,'ReAdWProgLoc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (97,'InspectDir',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (98,'PythonProgLoc',null,'Full path to python.exe (python 2.x)')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (99,'ManagerUpdateRequired','TrueFalsePickList','When True, then the manager will stop picking up new jobs and will exit.  However, prior to exiting, it will call SP AckManagerUpdateRequired')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (100,'LogMemoryUsage','TrueFalsePickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (101,'MinimumMemoryUsageLogInterval',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (102,'LogStatusToBrokerDB','TrueFalsePickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (103,'BrokerDBStatusUpdateIntervalMinutes',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (104,'LogStatusToMessageQueue','TrueFalsePickList',null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (105,'MessageQueueURI',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (106,'MessageQueueTopicMgrStatus',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (107,'DTAFolderLocation',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (108,'DTAProcessedFolderLocation',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (109,'XcalDLLPath',null,'The directory containing DeconMSn.exe and DeconEngineV2.dll')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (114,'FailedResultsFolderPath',null,'The directory to copy analysis results to when an analysis job or capture task produces results, but has a problem delivering them')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (115,'MSClusterprogloc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (116,'ControlQueueName',null,'Name of message queue used for sending commands to manager')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (117,'BroadcastQueueTopic',null,'Message queue topic for controlling manager')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (118,'StatusMsgIncomingTopic',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (119,'StatusMsgDBUpdateInterval',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (120,'ManagerErrorCleanupMode',null,'0 = No auto cleanup, 1 = Attempt auto cleanup once, 2 = Auto cleanup always')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (121,'ICR2LSprogloc',null,'Full path to file ICR-2LS.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (122,'SequestNodeCountExpected',null,'Expected number of processing nodes on a Sequest cluster')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (123,'LCMSFeatureFinderProgLoc',null,'Directory containing LCMSFeatureFinder.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (124,'formatdbprogloc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (125,'OMSSAprogloc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (126,'dtatoxmlprogloc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (127,'DtaRefineryLoc',null,'Full path to  dta_refinery.py (previously dta_refinery.exe)')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (128,'omssa2pepprogloc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (129,'puttyprogloc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (130,'puttysftpprogloc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (131,'MSDataFileTrimmerprogloc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (132,'AScoreprogloc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (133,'JavaLoc',null,'Should be 64-bit version of Java')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (134,'MSGFLoc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (136,'ChameleonCachedDataFolder',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (137,'ChameleonLoc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (138,'HashFileLocation',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (139,'CompassXportLoc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (140,'ProteoWizardDir',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (141,'PeptideProphetRunnerProgLoc',null,'Full path to file PeptideProphetRunner.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (142,'DeconToolsProgLoc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (143,'MSGFDbProgLoc',null,'Superseded by MSGFPlusProgLoc')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (144,'PHRPProgLoc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (145,'MSDeconvProgLoc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (146,'MSAlignProgLoc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (147,'RProgLoc',null,'Used by the Cyclops plugin (though this parameter is no longer in active use)')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (148,'CheckDataFolderCreateQueue',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (149,'SMAQCProgLoc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (150,'WorkDirMinFreeSpaceMB',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (151,'OrgDBDirMinFreeSpaceMB',null,'Target minimum free disk space on the drive with the DMS_Temp_Org directory; ignored if OrgDBDirMaxSizeGB is defined')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (152,'TransferDirMinFreeSpaceGB',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (153,'MD5ResultsFolderPath',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (154,'ShareConnectorType',null,'PRISM or DotNET')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (156,'MyEmslUpload',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (157,'MSFileInfoScannerDir',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (158,'PVMProgLoc',null,'Directory containing PVM on Sequest clusters')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (159,'IDPickerProgLoc',null,'Directory containing IDPicker-related .Exe files')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (160,'PeptideListToXMLProgLoc',null,'Directory containing PeptideListToXML.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (161,'LipidToolsProgLoc',null,'Directory containing LipidTools.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (162,'MgrSettingGroupName',null,'Parameter group to use for this manager; points to a Ghost manager that has parameters defined in T_ParamValue')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (163,'TargetedWorkflowsProgLoc',null,'Directory containing TargetedWorkflowConsole.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (164,'IonMobilityMsMsProgLoc',null,'Directory containing IonMobilityMsMsConsole.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (165,'QuameterProgLoc',null,'Directory containing Quameter.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (166,'PRIDEConverterProgLoc',null,'Directory containing pride-converter-2.0-SNAPSHOT.jar')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (167,'MSGFPlusIndexFilesFolderPath',null,'Directory containing MSGF+ index files for Fasta files created from the Protein_Sequences database')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (168,'MSAlignHistoneProgLoc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (169,'MSXMLCacheFolderPath',null,'Directory containing cached .mzXML files')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (170,'DMSWorkflowsFolderPath',null,'Directory with scripts and parameter files for MAC jobs')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (171,'LLRCRunnerProgLoc',null,'Directory containing LLRCRunner.exe, Models_paper.Rdata, and allData_v4.Rdata')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (172,'AgilentToUIMFProgLoc',null,'Directory containing AgilentToUimfConverter.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (173,'MSGFPlusIndexFilesFolderPathLegacyDB',null,'Directory containing MSGF+ index files for Fasta files not created from the Protein_Sequences database')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (174,'PICHPCUser','','Username to use when connecting to PIC HPC')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (175,'PICHPCPassword',null,'Password to use when connecting to PIC HPC')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (176,'MODaProgLoc',null,'Directory containing MODa.jar')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (177,'DeconPeakDetectorProgLoc',null,'Directory containing HammerOrDeconSimplePeakDetector.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (178,'MSPathFinderProgLoc',null,'Directory containing MSPathFinderT.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (179,'PbfGenProgLoc',null,'Directory containing PbfGen.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (180,'MzRefineryProgLoc',null,'Directory containing customized msconvert that supports MzRefinery; also has PPMErrorCharter.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (181,'UimfDemultiplexerProgLoc',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (182,'ProMexProgLoc',null,'Directory containing ProMex.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (183,'GlyQIQProgLoc',null,'Directory containing IQGlyQ_Console.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (184,'NOMSIProgLoc',null,'Directory containing NOMSI.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (185,'MSFileInfoScannerX86Dir',null,null)
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (186,'MODPlusProgLoc',null,'Directory containing modp_pnnl.jar')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (188,'OpenChromProgLoc',null,'Directory containing OpenChrom.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (189,'AuroraAvailable','TrueFalsePickList','True if Aurora is supported (\\a2.emsl.pnl.gov)')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (190,'MyEmslAvailable','TrueFalsePickList','True if MyEmsl is supported')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (191,'LCMethodFilesDir',null,'Directory with LC method files from LCMSNet')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (192,'QCARTRScriptName',null,'Filename of the QC-ART script')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (193,'MzidToTsvConverterProgLoc',null,'Directory containing MzidToTsvConverter.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (194,'RawConverterProgLoc',null,'Directory containing RawConverter.exe (He and Yates. Anal Chem. 2015 Nov 17; 87 (22): 11361-11367)')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (195,'RunJobsRemotely','TrueFalsePickList','When True, copy required files to the Remote Host then create a new JobTask file in the LocalTaskQueue directory on the remote host')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (196,'RemoteHostName',null,'Remote host for pushing jobs')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (197,'RemoteHostUser',null,'Username for connecting to the remote host')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (198,'RemoteTaskQueuePath',null,'Path on the remote computer to create task info files, e.g. Job1449504_Step03_20170515_1532.info')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (199,'RemoteWorkDirPath',null,'Path on the remote computer to tranfer files required for the analysis')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (200,'RemoteOrgDBPath',null,'Path on the remote computer for storing FASTA files')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (201,'RemoteHostPrivateKeyFile',null,'File with the RSA private key for connecting to RemoteHostName as user RemoteHostUser')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (202,'RemoteHostPassphraseFile',null,'File with the RSA passphrase')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (203,'MSGFPlusProgLoc',null,'Directory containing MSGFPlus.jar')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (204,'UimfToMassHunterProgLoc',null,'Directory containing UimfToMassHunter.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (205,'DMSUpdateManagerSource',null,'Server share with the master copy of files to copy to the local computer (or to a remote Linux host)')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (206,'RemoteHostDMSProgramsPath',null,'Path on the remote computer to the directory holding applications used by the analysis manager')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (207,'DMSUpdateManagerFilesToIgnore',null,'Filenames to ignore when updating files with the DMS Update Manager')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (209,'RemoteHostAnalysisManagerDirs',null,'Name (not full path) of the directory or directories below directory RemoteHostDMSProgramsPath')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (210,'MzidMergerProgLoc',null,'Directory with MzidMerger.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (211,'FormularityProgLoc',null,'Directory with the Formularity command line tool CIA.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (212,'TopFDProgLoc',null,'Directory with topfd.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (213,'TopPICProgLoc',null,'Directory with toppic.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (214,'BrukerSpectraExportMethodDir',null,'Directory with method .m subdirectories for use by the Bruker_DA_Export step tool (part of the Formularity script)')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (215,'ThermoPeakDataExporterProgLoc',null,'Directory with ThermoPeakDataExporter.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (216,'MSFraggerProgLoc',null,'Directory with MSFragger.jar')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (217,'PhilosopherProgLoc',null,'Directory with Philosoper exe, typically philosopher_windows_amd64.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (218,'Python3ProgLoc',null,'Directory with python.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (219,'FailedResultsDirectoryPath',null,'The directory to copy analysis results to when an analysis job or capture task produces results, but has a problem delivering them')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (220,'MaxQuantProgLoc',null,'Directory with a bin subdirectory that has MaxQuantCmd.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (221,'OrgDBDirMaxSizeGB',null,'Maximum disk usage of files in the DMS_Temp_Org directory')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (222,'TaskRequestEnableTime',null,'Date/time that can be used to prevent a manager from requesting new tasks until after this timestamp')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (223,'PNNLPreProcessorProgLoc',null,'Directory with PNNL-PreProcessor.exe')
SET IDENTITY_INSERT [T_ParamType] OFF
