/****** Object:  Table [T_ParamType] ******/
/****** RowCount: 190 ******/
SET IDENTITY_INSERT [T_ParamType] ON
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (1,'connectionstring','','Connection string to the DMS database for requesting tasks or updating status (DMS_Capture, DMS_Pipeline, or DMS5)')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (2,'username','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (3,'userpwd','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (4,'usetls','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (5,'serverport','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (6,'timeout','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (7,'passive','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (8,'restart','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (9,'workdir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (10,'machname','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (11,'zipprogram','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (12,'debuglevel','debugLevelPickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (13,'ftplogging','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (14,'maxrepetitions','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (15,'perspective','perspectivePickList','Can be client or server')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (16,'instclass','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (17,'mgractive','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (18,'testzip','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (19,'transfervol','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (20,'drives','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (21,'machnames','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (22,'bionetuser','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (23,'bionetpwd','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (24,'sleepinterval','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (25,'DSFolderExistsAction','folderExistsActionPickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (26,'mindiskspace','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (27,'toolresulttypes','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (28,'priorities','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (29,'xtprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (30,'sourcedir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (31,'fastacnstring','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (32,'UNUSED_performextraction','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (33,'statusfilelocation','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (34,'orgdbdir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (35,'lcqdtaloc','','The location of Extract_MSn.exe and its required DLLs; test change')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (36,'UNUSED_xtoutconv-dir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (37,'UNUSED_xtoutconv-prog','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (38,'UNUSED_xtoutconv-xslt','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (39,'UNUSED_usefilecheck','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (40,'UNUSED_performcal','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (41,'masicprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (42,'cluster','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (43,'bioworksversion','bioWorksVersionPickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (44,'UNUSED_xcalversion','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (45,'createnowindow','TrueFalsePickList','Obsolete / unused')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (46,'numberofprocessors','','Obsolete / unused')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (47,'seqprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (48,'paramtemplateloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (49,'hostsfilelocation','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (50,'nodedblocation','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (51,'UNUSED_substatusfile','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (52,'tcpport','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (53,'configfilename','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (54,'localmgrpath','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (55,'remotemgrpath','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (56,'programfoldername','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (57,'modulename','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (58,'servername','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (59,'showinmgrctrl','TrueFalsePickList','Obsolete / unused')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (60,'showinanmonitor','TrueFalsePickList','Obsolete / unused')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (61,'logfilename','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (62,'brokerconnectionstring','','Connection string to the DMS_Pipeline database')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (64,'storedprocedure','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (65,'importdelay','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (66,'enableemail','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (67,'smtpserver','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (68,'to','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (69,'from','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (70,'subject','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (71,'deletebadxmlfiles','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (72,'deletegoodxmlfiles','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (73,'xferdir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (74,'successfolder','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (75,'failurefolder','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (77,'timevalidationtolerance','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (78,'timevalidationfolder','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (79,'ArchiveOrUpdate','archiveOrUpdatePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (80,'xmlfiledelay','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (81,'cmdtimeout','','Obsolete / unused')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (82,'AppendMgrNameToXferFolder','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (83,'UseDTALooping','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (89,'MultiAlignprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (96,'ReAdWProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (97,'InspectDir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (98,'pythonprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (99,'ManagerUpdateRequired','TrueFalsePickList','When True, then the manager will stop picking up new jobs and will exit.  However, prior to exiting, it will call SP AckManagerUpdateRequired')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (100,'LogMemoryUsage','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (101,'MinimumMemoryUsageLogInterval','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (102,'LogStatusToBrokerDB','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (103,'BrokerDBStatusUpdateIntervalMinutes','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (104,'LogStatusToMessageQueue','TrueFalsePickList','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (105,'MessageQueueURI','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (106,'MessageQueueTopicMgrStatus','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (107,'DTAFolderLocation','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (108,'DTAProcessedFolderLocation','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (109,'XcalDLLPath','','The directory containing DeconMSn.exe and DeconEngineV2.dll')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (114,'FailedResultsFolderPath','','The directory to copy analysis results to when an analysis job produces results, but has a problem delivering them')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (115,'MSClusterprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (116,'ControlQueueName','','Name of message queue used for sending commands to manager')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (117,'BroadcastQueueTopic','','Message queue topic for controlling manager')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (118,'StatusMsgIncomingTopic','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (119,'StatusMsgDBUpdateInterval','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (120,'ManagerErrorCleanupMode','','0 = No auto cleanup, 1 = Attempt auto cleanup once, 2 = Auto cleanup always')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (121,'ICR2LSprogloc','','Full path to file ICR-2LS.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (122,'SequestNodeCountExpected','','Expected number of processing nodes on a Sequest cluster')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (123,'LCMSFeatureFinderProgLoc','','Directory containing LCMSFeatureFinder.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (124,'formatdbprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (125,'OMSSAprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (126,'dtatoxmlprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (127,'dtarefineryloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (128,'omssa2pepprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (129,'puttyprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (130,'puttysftpprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (131,'MSDataFileTrimmerprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (132,'AScoreprogloc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (133,'JavaLoc','','Should be 64-bit version of Java')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (134,'MSGFLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (136,'ChameleonCachedDataFolder','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (137,'ChameleonLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (138,'HashFileLocation','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (139,'CompassXportLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (140,'ProteoWizardDir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (141,'PeptideProphetRunnerProgLoc','','Full path to file PeptideProphetRunner.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (142,'DeconToolsProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (143,'MSGFDbProgLoc','','Superseded by MSGFPlusProgLoc')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (144,'PHRPProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (145,'MSDeconvProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (146,'MSAlignProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (147,'RProgLoc','','Used by the Cyclops plugin (though this parameter is no longer in active use)')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (148,'CheckDataFolderCreateQueue','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (149,'SMAQCProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (150,'WorkDirMinFreeSpaceMB','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (151,'OrgDBDirMinFreeSpaceMB','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (152,'TransferDirMinFreeSpaceGB','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (153,'MD5ResultsFolderPath','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (154,'ShareConnectorType','','PRISM or DotNET')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (156,'MyEmslUpload','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (157,'MSFileInfoScannerDir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (158,'PVMProgLoc','','Directory containing PVM on Sequest clusters')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (159,'IDPickerProgLoc','','Directory containing IDPicker-related .Exe files')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (160,'PeptideListToXMLProgLoc','','Directory containing PeptideListToXML.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (161,'LipidToolsProgLoc','','Directory containing LipidTools.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (162,'MgrSettingGroupName','','Parameter group to use for this manager; points to a Ghost manager that has parameters defined in T_ParamValue')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (163,'TargetedWorkflowsProgLoc','','Directory containing TargetedWorkflowConsole.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (164,'IonMobilityMsMsProgLoc','','Directory containing IonMobilityMsMsConsole.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (165,'QuameterProgLoc','','Directory containing Quameter.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (166,'PRIDEConverterProgLoc','','Directory containing pride-converter-2.0-SNAPSHOT.jar')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (167,'MSGFPlusIndexFilesFolderPath','','Directory containing MSGF+ index files for Fasta files created from the Protein_Sequences database')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (168,'MSAlignHistoneProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (169,'MSXMLCacheFolderPath','','Directory containing cached .mzXML files')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (170,'DMSWorkflowsFolderPath','','Directory with scripts and parameter files for MAC jobs')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (171,'LLRCRunnerProgLoc','','Directory containing LLRCRunner.exe, Models_paper.Rdata, and allData_v4.Rdata')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (172,'AgilentToUIMFProgLoc','','Directory containing AgilentToUimfConverter.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (173,'MSGFPlusIndexFilesFolderPathLegacyDB','','Directory containing MSGF+ index files for Fasta files not created from the Protein_Sequences database')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (174,'PICHPCUser','','Username to use when connecting to PIC HPC')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (175,'PICHPCPassword','','Password to use when connecting to PIC HPC')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (176,'MODaProgLoc','','Directory containing MODa.jar')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (177,'DeconPeakDetectorProgLoc','','Directory containing HammerOrDeconSimplePeakDetector.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (178,'MSPathFinderProgLoc','','Directory containing MSPathFinderT.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (179,'PbfGenProgLoc','','Directory containing PbfGen.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (180,'MzRefineryProgLoc','','Directory containing customized msconvert that supports MzRefinery; also has PPMErrorCharter.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (181,'UimfDemultiplexerProgLoc','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (182,'ProMexProgLoc','','Directory containing ProMex.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (183,'GlyQIQProgLoc','','Directory containing IQGlyQ_Console.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (184,'NOMSIProgLoc','','Directory containing NOMSI.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (185,'MSFileInfoScannerX86Dir','','')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (186,'MODPlusProgLoc','','Directory containing modp_pnnl.jar')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (188,'OpenChromProgLoc','','Directory containing OpenChrom.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (189,'AuroraAvailable','TrueFalsePickList','True if Aurora is supported (\\a2.emsl.pnl.gov)')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (190,'MyEmslAvailable','TrueFalsePickList','True if MyEmsl is supported')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (191,'LCMethodFilesDir','','Directory with LC method files from LCMSNet')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (192,'QCARTRScriptName','','Filename of the QC-ART script')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (193,'MzidToTsvConverterProgLoc','','Directory containing MzidToTsvConverter.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (194,'RawConverterProgLoc','','Directory containing RawConverter.exe (He and Yates. Anal Chem. 2015 Nov 17; 87 (22): 11361-11367)')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (195,'RunJobsRemotely','TrueFalsePickList','When True, copy required files to the Remote Host then create a new JobTask file in the LocalTaskQueue directory on the remote host')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (196,'RemoteHostName','','Remote host for pushing jobs')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (197,'RemoteHostUser','','Username for connecting to the remote host')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (198,'RemoteTaskQueuePath','','Path on the remote computer to create task info files, e.g. Job1449504_Step03_20170515_1532.info')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (199,'RemoteWorkDirPath','','Path on the remote computer to tranfer files required for the analysis')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (200,'RemoteOrgDBPath','','Path on the remote computer for storing FASTA files')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (201,'RemoteHostPrivateKeyFile','','File with the RSA private key for connecting to RemoteHostName as user RemoteHostUser')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (202,'RemoteHostPassphraseFile','','File with the RSA passphrase')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (203,'MSGFPlusProgLoc','','Directory containing MSGFPlus.jar')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (204,'UimfToMassHunterProgLoc','','Directory containing UimfToMassHunter.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (205,'DMSUpdateManagerSource','','Server share with the master copy of files to copy to the local computer (or to a remote Linux host)')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (206,'RemoteHostDMSProgramsPath','','Path on the remote computer to the directory holding applications used by the analysis manager')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (207,'DMSUpdateManagerFilesToIgnore','','Filenames to ignore when updating files with the DMS Update Manager')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (209,'RemoteHostAnalysisManagerDirs','','Name (not full path) of the directory or directories below directory RemoteHostDMSProgramsPath')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (210,'MzidMergerProgLoc','','Directory with MzidMerger.exe')
INSERT INTO [T_ParamType] (ParamID, ParamName, PicklistName, Comment) VALUES (211,'FormularityProgLoc','','Directory with the Formularity command line tool CIA.exe')
SET IDENTITY_INSERT [T_ParamType] OFF
