/****** Object:  Table [T_Job_State_Name] ******/
/****** RowCount: 20 ******/
/****** Columns: ID, Name ******/
INSERT INTO [T_Job_State_Name] VALUES (0,'(none)')
INSERT INTO [T_Job_State_Name] VALUES (1,'New')
INSERT INTO [T_Job_State_Name] VALUES (2,'Job In Progress')
INSERT INTO [T_Job_State_Name] VALUES (3,'Results Received')
INSERT INTO [T_Job_State_Name] VALUES (4,'Complete')
INSERT INTO [T_Job_State_Name] VALUES (5,'Failed')
INSERT INTO [T_Job_State_Name] VALUES (6,'Transfer Failed')
INSERT INTO [T_Job_State_Name] VALUES (7,'No Intermediate Files Created')
INSERT INTO [T_Job_State_Name] VALUES (8,'Holding')
INSERT INTO [T_Job_State_Name] VALUES (9,'Transfer In Progress')
INSERT INTO [T_Job_State_Name] VALUES (10,'Spectra Required')
INSERT INTO [T_Job_State_Name] VALUES (11,'Spectra Req. In Progress')
INSERT INTO [T_Job_State_Name] VALUES (12,'Spectra Req. Failed')
INSERT INTO [T_Job_State_Name] VALUES (14,'No Export')
INSERT INTO [T_Job_State_Name] VALUES (15,'SpecialClusterFailed')
INSERT INTO [T_Job_State_Name] VALUES (16,'Data Extraction Required')
INSERT INTO [T_Job_State_Name] VALUES (17,'Data Extraction In Progress')
INSERT INTO [T_Job_State_Name] VALUES (18,'Data Extraction Failed')
INSERT INTO [T_Job_State_Name] VALUES (20,'Resuming')
INSERT INTO [T_Job_State_Name] VALUES (21,'Permanent')
