/****** Object:  Table [T_Processor_Tool_Groups] ******/
/****** RowCount: 22 ******/
/****** Columns: Group_ID, Group_Name, Enabled, Comment ******/
INSERT INTO [T_Processor_Tool_Groups] VALUES (0,'Disabled Processors',0,'')
INSERT INTO [T_Processor_Tool_Groups] VALUES (1,'Proto_Storage_Servers',1,'')
INSERT INTO [T_Processor_Tool_Groups] VALUES (2,'Mash_Prep_Servers',1,'')
INSERT INTO [T_Processor_Tool_Groups] VALUES (3,'Poweredge 1750 XP Pubs',-10,'Old boxes that we need to excess')
INSERT INTO [T_Processor_Tool_Groups] VALUES (4,'Poweredge 1750 XP Pubs with ICR2LS',-10,'Old boxes that we need to excess')
INSERT INTO [T_Processor_Tool_Groups] VALUES (5,'Poweredge 1850 XP Pubs',1,'')
INSERT INTO [T_Processor_Tool_Groups] VALUES (6,'Poweredge 1850 Windows 7 Pubs',1,'')
INSERT INTO [T_Processor_Tool_Groups] VALUES (7,'Poweredge 1950 quad core, 1 GB Pubs',1,'Windows 2003 Server Pubs')
INSERT INTO [T_Processor_Tool_Groups] VALUES (8,'Poweredge 1950 quad core, 2 GB Pubs',1,'Running 32-bit Windows XP')
INSERT INTO [T_Processor_Tool_Groups] VALUES (9,'R610 Pubs, Group 1, Decon2LS_V2',1,'Have .NET 4; running LCMSFeatureFinder and Decon2LS_V2')
INSERT INTO [T_Processor_Tool_Groups] VALUES (10,'Sequest Clusters',1,'')
INSERT INTO [T_Processor_Tool_Groups] VALUES (11,'Old single core XP pubs',1,'')
INSERT INTO [T_Processor_Tool_Groups] VALUES (12,'Peaks and Daffy Pubs',1,'')
INSERT INTO [T_Processor_Tool_Groups] VALUES (13,'Monroe Development Box',1,'')
INSERT INTO [T_Processor_Tool_Groups] VALUES (14,'Sandoval Development Box',1,'')
INSERT INTO [T_Processor_Tool_Groups] VALUES (15,'Poweredge 1850 XP Pubs with ICR2LS-Lite',1,'')
INSERT INTO [T_Processor_Tool_Groups] VALUES (17,'R610 Pubs, Group 2, Decon2LS_V2',1,'Have .NET 4; running LCMSFeatureFinder and Decon2LS_V2; also supports MSXML_Bruker; Microsoft Forefront ignores DMS_WorkDir folders; 24 GB of ram (only 16 GB on Pub-74)')
INSERT INTO [T_Processor_Tool_Groups] VALUES (18,'Crowell Development Box',1,'')
INSERT INTO [T_Processor_Tool_Groups] VALUES (19,'R610 Pub-88, Decon2LS_V2',1,'Pub-88 is connected to Chinook and can run XTandem_HPC')
INSERT INTO [T_Processor_Tool_Groups] VALUES (21,'R610 Pubs, Group 3, Decon2LS_V2',1,'Have .NET 4; running LCMSFeatureFinder and Decon2LS_V2; 24 GB of ram')
INSERT INTO [T_Processor_Tool_Groups] VALUES (22,'R610 Pubs, Group 4, R 2.13.1',1,'Have .NET 4; running LCMSFeatureFinder and Decon2LS_V2; 24 GB of ram; have R 2.13.1')
INSERT INTO [T_Processor_Tool_Groups] VALUES (23,'Mallard',1,'Has .NET 4; running LCMSFeatureFinder and Decon2LS_V2')
