/****** Object:  Table [T_Scripts] ******/
/****** RowCount: 61 ******/
/****** Columns: ID, Script, Description, Enabled, Results_Tag, Contents, Parameters, Backfill_to_DMS ******/
INSERT INTO [T_Scripts] VALUES (0,'(none)','"Standard" processing for DMS tool','N','','','',0)
INSERT INTO [T_Scripts] VALUES (1,'Sequest','This is the standard script for the "Sequest" DMS tool (modified to have conditional data extraction dependency)','Y','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Sequest"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (2,'ICR2LS','"Standard" processing for DMS tool','Y','ICR','<JobScript Name="ICR2LS"><Step Number="1" Tool="ICR2LS" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (4,'TIC_ICR','"Standard" processing for DMS tool','N','TIC','<JobScript Name="TIC_ICR"><Step Number="1" Tool="Bogus" /></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (5,'TIC_LCQ','"Standard" processing for DMS tool','N','TIC','','',0)
INSERT INTO [T_Scripts] VALUES (6,'QTOFSequest','"Standard" processing for DMS tool','N','','','',0)
INSERT INTO [T_Scripts] VALUES (7,'QTOFPek','"Standard" processing for DMS tool','N','','','',0)
INSERT INTO [T_Scripts] VALUES (8,'DeNovoID','"Standard" processing for DMS tool','N','','','',0)
INSERT INTO [T_Scripts] VALUES (9,'AgilentSequest','"Standard" processing for DMS tool','N','Seq','','',0)
INSERT INTO [T_Scripts] VALUES (10,'MLynxPek','"Standard" processing for DMS tool','N','ICR','','',0)
INSERT INTO [T_Scripts] VALUES (11,'AgilentTOFPek','"Standard" processing for DMS tool','N','ICR','','',0)
INSERT INTO [T_Scripts] VALUES (12,'LTQ_FTPek','"Standard" processing for DMS tool','Y','ICR','<JobScript Name="LTQ_FTPek"><Step Number="1" Tool="LTQ_FTPek" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (13,'MASIC_Finnigan','This is the standard script for the "MASIC_Finnigan" DMS tool','Y','SIC','<JobScript Name="MASIC_Finnigan"><Step Number="1" Tool="MASIC_Finnigan" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (14,'MASIC_Agilent','This is the standard script for the "MASIC_Agilent" DMS tool','Y','SIC','<JobScript Name="MASIC_Agilent"><Step Number="1" Tool="MASIC_Agilent" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (15,'XTandem','This is the standard script for the "XTandem" DMS tool','Y','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (16,'Decon2LS','This is the standard script for the "Decon2LS" DMS tool.','Y','DLS','<JobScript Name="Decon2LS"><Step Number="1" Tool="Decon2LS" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (17,'TIC_D2L','This is the standard script for the "TIC_D2L" DMS tool','Y','TDL','<JobScript Name="TIC_D2L"><Step Number="1" Tool="TIC_D2L" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (18,'Decon2LS_Agilent','This is the standard script for the "Decon2LS_Agilent" DMS tool','Y','DLS','<JobScript Name="Decon2LS_Agilent"><Step Number="1" Tool="Decon2LS_Agilent" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (19,'TIC_D2L_Agilent','This is the standard script for the "TIC_D2L_Agilent" DMS tool','Y','TDL','<JobScript Name="TIC_D2L_Agilent"><Step Number="1" Tool="TIC_D2L_Agilent" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (20,'Inspect','This is the parallelized script for the "Inspect" DMS tool','Y','INS','<JobScript Name="Inspect"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="DTA_Split"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="Inspect" Special="Clone"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="InspectResultsAssembly"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="DataExtractor"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="MSGF"><Depends_On Step_Number="6" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="7" Enable_Only="1" /></Step><Step Number="9" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (21,'XTandemSplice','This is a splice script to add XTandem steps onto standard Sequest script job','N','XTS','<JobScript Name="XTandemSplice"><Step Number="10" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="11" Tool="DataExtractor"><Depends_On Step_Number="10" /></Step><Step Number="12" Tool="Results_Transfer"><Depends_On Step_Number="11" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (22,'MSXML_Gen','Uses the ReadW tool to creates mzXML or mzML files','Y','XML','<JobScript Name="MSXML_Gen"><Step Number="1" Tool="MSXML_Gen" Special="Job_Results" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (23,'DTA_Gen','Uses Extract_MSn or DeconMSn to create a concatenated DTA (_Dta.txt) file','Y','DTA','<JobScript Name="DTA_Gen"><Step Number="1" Tool="DTA_Gen" Special="Job_Results" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (24,'MSClusterDAT_Gen','This script generates .dat files for use by Ari Frank''s MSCluster tool','Y','MSCD','<JobScript Name="MSClusterDAT_Gen"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSClusterDTAtoDAT"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="2" Enable_Only="1" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (25,'DTA_Import','Imports externally-supplied DTA folders into a dataset for later analysis','N','DTA','<JobScript Name="DTA_Import"><Step Number="1" Tool="DTA_Import" Special="Job_Results" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (26,'XTandem_DTA_Import','This is the standard script for the "XTandem" DMS tool, except that it can do DTA import also','N','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="7" Tool="DTA_Import"><Depends_On Step_Number="1" /></Step><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /><Depends_On Step_Number="7" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step><Step Number="9" Tool="Results_Transfer"><Depends_On Step_Number="7" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (27,'Sequest_UseExistingExternalDTA','This script runs the "Sequest" DMS tool, but assumes that an External DTA folder already exist in the Dataset folder; intended for use with FinniganDefSettings_ExternalDTA.xml or a similar settings file.  The settings file should have an entry like: item key="ExternalDTAFolderName" value="DTA_Manual_01"','Y','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Sequest"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (28,'XTandem_UseExistingExternalDTA','This script runs the "X!Tandem" DMS tool, but assumes that an External DTA folder already exist in the Dataset folder; intended for use with FinniganDefSettings_ExternalDTA.xml or a similar settings file.  The settings file should have an entry like: item key="ExternalDTAFolderName" value="DTA_Manual_01"','Y','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (29,'Decon2LS_V2','This script runs the DeconToolsAutoProcessor, which supports IMS data and RAPID.  Following Decon2LS, the LCMSFeatureFinder processes the Decon2LS results.  The Settings file must contain an LCMSFeatureFinder section (with LCMSFeatureFinderIniFile defining the Feature Finder .Ini file to use)','Y','DLS','<JobScript Name="Decon2LS_V2"><Step Number="1" Tool="Decon2LS_V2" /><Step Number="2" Tool="LCMSFeatureFinder"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (30,'OMSSA','This is the standard script for the "OMSSA" DMS tool','Y','OMS','<JobScript Name="OMSSA"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="OMSSA"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (31,'LCMSFeatureFinder_UseExistingResults','This script runs the LCMSFeatureFinder against existing Decon2LS results.  The Settings file must contain an LCMSFeatureFinder section (with LCMSFeatureFinderIniFile defining the Feature Finder .Ini file to use)','Y','DLS','<JobScript Name="Decon2LS"><Step Number="3" Tool="LCMSFeatureFinder"><Depends_On Step_Number="1" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="3" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (32,'Sequest_DTARefinery','This script uses DTARefinery to refine the DTAs before running "Sequest" (conditional data extraction dependency)','Y','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="DTA_Refinery"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="Sequest"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="MSGF"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="2" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="9" Tool="Results_Transfer"><Depends_On Step_Number="6" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (33,'XTandem_HPC','This script runs "XTandem" on the Chinook high-performance computer','Y','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="DTA_Split"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="XTandem_HPC"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="MSGF"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="6" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (34,'XTandem_DTARefinery','This script uses DTARefinery to refine the DTAs before running "XTandem" (conditional data extraction dependency)','Y','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="DTA_Refinery"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="XTandem"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="MSGF"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="2" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="9" Tool="Results_Transfer"><Depends_On Step_Number="6" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (35,'Inspect_UseExistingExternalDTA','This script runs "Inspect", but assumes that an External DTA folder already exists in the Dataset folder; intended for use with Inspect_ExternalDTA_x1.xml or a similar settings file.  The settings file should have an entry like: item key="ExternalDTAFolderName" value="DTA_Manual_01"','Y','INS','<JobScript Name="Inspect"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="DTA_Split"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="Inspect" Special="Clone"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="InspectResultsAssembly"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="DataExtractor"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="MSGF"><Depends_On Step_Number="6" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (36,'PRIDE_mzXML','Aggregates mzXML results from multiple mzXML jobs and saves result in data package','Y','PZX','<JobScript Name="PRIDE_mzXML"><Step Number="1" Tool="mzXML_Aggregator" /></JobScript>','<Param Section="JobParameters" Name="DatasetNum" Value="Aggregation" /><Param Section="JobParameters" Name="PRIDEMzXMLInputFile" Value="" /><Param Section="JobParameters" Name="TargetJobFileList" Value="sequest:_syn.txt:copy,msxml_gen:.mzxml:nocopy" /><Param Section="JobParameters" Name="transferFolderPath" Value="" />',1)
INSERT INTO [T_Scripts] VALUES (37,'Phospho_FDR_Aggregator','"Standard" processing for DMS tool','Y','PFA','<JobScript Name="Phospho_FDR_Aggregator"><Step Number="1" Tool="Phospho_FDR_Aggregator" /></JobScript>','<Param Section="JobParameters" Name="AScoreCIDParamFile" Value="xxx_ascore_cid.par" Reqd="No" /><Param Section="JobParameters" Name="AScoreETDParamFile" Value="xxx_ascore_etd.par" Reqd="No" /><Param Section="JobParameters" Name="AScoreHCDParamFile" Value="xxx_ascore_hcd.par" Reqd="No" /><Param Section="JobParameters" Name="DatasetNum" Value="Aggregation" Reqd="Yes" /><Param Section="JobParameters" Name="TargetJobFileList" Value="sequest:_syn.txt:nocopy,sequest:_fht.txt:nocopy,sequest:_dta.zip:nocopy,masic_finnigan:_reporterions.txt:copy,masic_finnigan:_ScanStatsEx.txt:nocopy" Reqd="Yes" /><Param Section="JobParameters" Name="transferFolderPath" Value="" Reqd="Yes" />',1)
INSERT INTO [T_Scripts] VALUES (38,'Sequest_Extend_MSGF','This script should be used to process existing Sequest results to process them with MSGF','Y','Seq','<JobScript Name="Sequest_AddMSGFToExisting"><Step Number="7" Tool="MSGF"><Depends_On Step_Number="6" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (39,'Sequest_No_MSGF','This is the standard script for the "Sequest" DMS tool.  This applies to jobs that ran sequest but did not use MSGF','Y','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Sequest"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (40,'LCMSFeature_Finder','This script runs the LCMSFeatureFinder to process the Decon2LS results.  This is a case where a job targets another job.  Use the text SourceJob:0000 in the job''s Special_Processing parameters to define the parent DeconTools job.  Alternatively, use a job match spec, e.g.: SourceJob:Auto{Tool = "Decon2LS_V2" AND Settings_File = "Decon2LS_FF_IMS_0.15Fit_0.3IScore_20ppm_500Int_DaCorrect_2011-01-24.xml" AND [Parm File] = "IMS_UIMF_PeakBR4_PeptideBR4_SN3_SumScans4_SumFrames3_noFit_Thrash_2009-11-02.xml"}','Y','LFF','<JobScript Name="LCMSFeature_Finder"><Step Number="1" Tool="LCMSFeatureFinder" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (41,'XTandem_No_MSGF','This is the standard script for the "XTandem" DMS tool. This applies to jobs that ran X!Tandem but did not use MSGF','Y','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (42,'XTandem_Extend_MSGF','This script should be used to process existing X!Tandem results to process them with MSGF','Y','XTM','<JobScript Name="XTandem_AddMSGFToExisting"><Step Number="7" Tool="MSGF"><Depends_On Step_Number="6" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (43,'Inspect_Single','This is the non-parallelized script for the "Inspect" DMS tool','Y','INS','<JobScript Name="Inspect"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Inspect"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="InspectResultsAssembly"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="MSGF"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="6" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (44,'Sequest_DTARefinery_No_MSGF','This script uses DTARefinery to refine the DTAs before running "Sequest" (conditional data extraction dependency); this was used prior to MSGF','Y','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="DTA_Refinery"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="Sequest"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="2" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (45,'Sequest_DTARefinery_Extend_MSGF','This script should be used to process existing Sequest DTARefinery results to process them with MSGF','Y','Seq','<JobScript Name="Sequest_DTARefinery_AddMSGFToExisting"><Step Number="9" Tool="MSGF"><Depends_On Step_Number="8" /></Step><Step Number="10" Tool="Results_Transfer"><Depends_On Step_Number="9" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (46,'MSXML_Bruker','Uses the CompassXport tool to creates mzXML or mzML files from Bruker .D folders','Y','XML','<JobScript Name="MSXML_Bruker"><Step Number="1" Tool="MSXML_Bruker" Special="Job_Results" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (47,'MultiAlign','This script runs MultiAlign on a single job against a given AMT tag database.  Specify the AMT tag database to use using the Special_Processing parameters, e.g. AMTDB:MT_Shewanella_ProdTest_Formic_P460.  Use the text SourceJob:0000 in the job''s Special_Processing parameters to define the parent DeconTools job.  Alternatively, use a job match spec, e.g.: SourceJob:Auto{Tool = "Decon2LS_V2" ORDER BY Job Desc}.','Y','MAL','<JobScript Name="MultiAlign"><Step Number="1" Tool="MultiAlign" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (48,'MultiAlign_Aggregator','This script runs MultiAlign on a set of jobs (optionally align to an AMT tag database).  Specify the AMT tag database to use using the Special_Processing parameters, e.g. AMTDB:MT_Shewanella_ProdTest_Formic_P460.  Define the source jobs by associating with a data package','Y','MAA','<JobScript Name="MultiAlign_Aggregator"><Step Number="1" Tool="MultiAlign_Aggregator" Special="ExtractSourceJobFromComment" /></JobScript>','<Param Section="JobParameters" Name="DatasetNum" Value="Aggregation" Reqd="Yes" /><Param Section="JobParameters" Name="ParmFileName" Value="" Reqd="Yes" /><Param Section="JobParameters" Name="AlignmentDataset" Value="" Reqd="No" /><Param Section="JobParameters" Name="AMTDB" Value="" Reqd="No" /><Param Section="JobParameters" Name="AMTDBServer" Value="" Reqd="No" /><Param Section="JobParameters" Name="ResultFilename" Value="Aggregation" Reqd="Yes" /><Param Section="JobParameters" Name="TargetJobFileList" Value="decon2ls_v2:_LCMSFeatures.txt:nocopy,lcmsfeature_finder:_LCMSFeatures.txt:nocopy" Reqd="Yes" /><Param Section="JobParameters" Name="transferFolderPath" Value="" Reqd="Yes" />',1)
INSERT INTO [T_Scripts] VALUES (49,'MSGFDB','This is the standard script for the "MSGFDB" DMS tool','Y','MSG','<JobScript Name="MSGFDB"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="MSGFDB"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (50,'MSGFDB_DTARefinery','This script uses DTARefinery to refine the DTAs before running "MSGFDB"','Y','MSG','<JobScript Name="MSGFDB"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="DTA_Refinery"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="MSGFDB"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="MSGF"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="2" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="9" Tool="Results_Transfer"><Depends_On Step_Number="6" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (51,'MSAlign','This is the standard script for the "MSAlign" DMS tool.  Use this script with Thermo instruments','Y','MSA','<JobScript Name="MSAlign"><Step Number="1" Tool="MSXML_Gen" /><Step Number="2" Tool="MSDeconv"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="MSAlign"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="3" Enable_Only="1" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="3" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (52,'MAC_Spectral_Counting','MAC Script for spectral counting','Y','SCo','<JobScript Name="MAC_Spectral_Counting"><Step Number="1" Tool="Mage"><Description>Extract DMS results and 
metadata into cache database</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Filters data by iterating over MSGF and PPM
to determine FDRs of 0.1%, 1%, 5%, and 10% based
on forward/reverse database searches.</Description></Step><Step Number="3" Tool="Cyclops"><Depends_On Step_Number="2" /><Description>Plots the data and performs a Beta-binomial model
analysis on the data to determine significant changes
between factors for spectral count results.</Description></Step></JobScript>','<Param Section="JobParameters" Name="transferFolderPath" Value="" /><Param Section="JobParameters" Name="AnalysisType" Value="SpectralCounting" Reqd="Yes" /><Param Section="JobParameters" Name="ResultsBaseName" Value="Results" Reqd="Yes" /><Param Section="1_Mage" Name="MageOperations" Value="ExtractFromJobs, GetFactors, GetFDRTables" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="MageOperations" Value="ExtractFromJobs, GetFactors, GetFDRTables" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="ExtractionSource" Value="JobsFromDataPackageID" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="ExtractionType" Value="Sequest First Hits" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="KeepAllResults" Value="Yes" Reqd="No" Step="1" /><Param Section="1_Mage" Name="ResultFilterSetID" Value="All Pass" Reqd="No" Step="1" /><Param Section="1_Mage" Name="MSGFCutoff" Value="All Pass" Reqd="No" Step="1" /><Param Section="1_Mage" Name="FactorsSource" Value="FactorsFromDataPackageID" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="MageFDRFiles" Value="" Reqd="No" Step="1" /><Param Section="2_Ape" Name="ApeWorkflowName" Value="20111024_FDR_workflow.xml" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeOperations" Value="RunWorkflow" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeWorflowStepList" Value="all" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeCompactDatabase" Value="True" Reqd="Yes" Step="2" /><Param Section="3_Cyclops" Name="CyclopsWorkflowName" Value="Cyclops_SpectralCount_WF.xml" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="RunProteinProphet" Value="False" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="Consolidation_Factor" Value="" Reqd="No" Step="3" /><Param Section="3_Cyclops" Name="Fixed_Effect" Value="" Reqd="No" Step="3" />',1)
INSERT INTO [T_Scripts] VALUES (53,'MAC_IMPROV','MAC Script for building IMPROV database','Y','IPV','<JobScript Name="MAC_IMPROV"><Step Number="1" Tool="APE"><Description>Import features from 
MT database into cache database
</Description></Step><Step Number="2" Tool="Mage"><Depends_On Step_Number="1" /><Description>Import contents of files 
from data package to cache database
</Description></Step></JobScript>','<Param Section="JobParameters" Name="transferFolderPath" Value="" /><Param Section="JobParameters" Name="ResultsBaseName" Value="Results" Reqd="Yes" /><Param Section="1_Ape" Name="ApeOperations" Value="GetImprovResults" Reqd="Yes" Step="1" /><Param Section="1_Ape" Name="ApeMTSServer" Value="Albert" Reqd="Yes" Step="1" /><Param Section="1_Ape" Name="ApeMTSDatabase" Value="MT_SeaSediments_ERB_P744" Reqd="Yes" Step="1" /><Param Section="1_Ape" Name="ImprovMinPMTQuality" Value="1.0" Reqd="Yes" Step="1" /><Param Section="2_Mage" Name="MageOperations" Value="ImportDataPackageFiles" Reqd="Yes" Step="2" /><Param Section="2_Mage" Name="DataPackageSourceFolderName" Value="ImportFiles" Reqd="Yes" Step="2" />',1)
INSERT INTO [T_Scripts] VALUES (55,'SMAQC_MSMS','This script runs SMAQC to generate QC metrics for LC-MS/MS datasets.  This scripts requires that an existing MASIC and X!Tandem job exist for the dataset.  Use the text SourceJob:0000 in the job''s Special_Processing parameters to define the parent X!Tandem job (the parent MASIC job is auto-determined).  Alternatively, use a job match spec, e.g.: SourceJob:Auto{Tool = "XTandem" AND Settings_File = "IonTrapDefSettings_DeconMSN.xm" AND [Parm File] = "xtandem_Rnd1PartTryp_Rnd2DynMetOx.xml"}','Y','SQC','<JobScript Name="SMAQC_MSMS"><Step Number="1" Tool="SMAQC" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (56,'MSGFDB_MzXml','Search mzXML files with "MSGFDB" DMS tool.  Appropriate for datasets with high resolution MS/MS spectra','Y','MSG','<JobScript Name="MSGFDB_MzXml"><Step Number="1" Tool="MSXML_Gen" /><Step Number="2" Tool="MSGFDB"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="DataExtractor"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="MSGF"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (57,'MSAlign_Bruker','Processes Bruker .D folders with MSAlign','Y','MSA','<JobScript Name="MSAlign_Bruker"><Step Number="1" Tool="MSXML_Bruker" /><Step Number="2" Tool="MSDeconv"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="MSAlign"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="3" Enable_Only="1" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="3" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (58,'MSDeconv_Bruker','Processes Bruker .D folders with MSDeconv','Y','MSA','<JobScript Name="MSDeconv_Bruker"><Step Number="1" Tool="MSXML_Bruker" /><Step Number="2" Tool="MSDeconv"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="2" Enable_Only="1" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (59,'MSGFDB_Bruker','Search Bruker mzXML files with "MSGFDB" DMS tool','Y','MSG','<JobScript Name="MSGFDB_MzXml"><Step Number="1" Tool="MSXML_Bruker" /><Step Number="2" Tool="MSGFDB"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="DataExtractor"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="MSGF"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (60,'MAC_Label_Free','MAC Script for building Label Free database','Y','LBF','<JobScript Name="MAC_Label_Free"><Step Number="1" Tool="Mage"><Description>Import Factors, Data Package from data package to cache database
</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Import features from MT database into cache database
</Description></Step><Step Number="3" Tool="Cyclops"><Depends_On Step_Number="2" /><Description>Plots the data and performs a Beta-binomial model analysis on the data to determine significant changes between factors for spectral count results.
</Description></Step></JobScript>','<Param Section="JobParameters" Name="transferFolderPath" Value="" /><Param Section="JobParameters" Name="AnalysisType" Value="LabelFree" Reqd="Yes" /><Param Section="JobParameters" Name="ResultsBaseName" Value="Results" Reqd="Yes" /><Param Section="1_Mage" Name="MageOperations" Value="GetFactors,ImportJobList" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="FactorsSource" Value="FactorsFromDataPackageID" Reqd="Yes" Step="1" /><Param Section="2_Ape" Name="ApeOperations" Value="GetViperResults,RunWorkflow" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeMTSServer" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeMTSDatabase" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeMDState" Value="2" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeMDIniFilename" Value="" Reqd="No" Step="" /><Param Section="2_Ape" Name="ApeWorkflowName" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeWorflowStepList" Value="all" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeCompactDatabase" Value="True" Reqd="Yes" Step="2" /><Param Section="3_Cyclops" Name="CyclopsWorkflowName" Value="" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="RunProteinProphet" Value="False" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="Consolidation_Factor" Value="" Reqd="No" Step="3" /><Param Section="3_Cyclops" Name="Fixed_Effect" Value="" Reqd="No" Step="3" />',1)
INSERT INTO [T_Scripts] VALUES (61,'Sequest_Extend_IDPicker','This script should be used to process existing Sequest results to process them with IDPicker','Y','Seq','<JobScript Name="Sequest_Extend_IDPicker"><Step Number="8" Tool="IDPicker"><Depends_On Step_Number="5" /></Step><Step Number="9" Tool="Results_Transfer"><Depends_On Step_Number="8" /></Step></JobScript>','',0)
INSERT INTO [T_Scripts] VALUES (62,'MAC_iTRAQ','MAC Script for processing iTRAQ data with interference consideration','Y','ITQ','<JobScript Name="MAC_iTRAQ"><Step Number="1" Tool="AScore"><Description>Run AScore on multiple datasets individually and import resultsinto cache database
</Description></Step><Step Number="2" Tool="Mage"><Depends_On Step_Number="1" /><Description>Import Factors, Data Package from data package to cache database
</Description></Step><Step Number="3" Tool="IDM"><Depends_On Step_Number="2" /><Description>Calculates interference percentage in MS data
</Description></Step><Step Number="4" Tool="APE"><Depends_On Step_Number="3" /><Description>Filters iTRAQ results
</Description></Step><Step Number="5" Tool="Cyclops"><Depends_On Step_Number="4" /><Description>Plots the data and performs a Beta-binomial model analysis on the data to determine significant changes between factors for spectral count results.
</Description></Step></JobScript>','<Param Section="JobParameters" Name="transferFolderPath" Value="" /><Param Section="JobParameters" Name="AnalysisType" Value="iTRAQ" Reqd="Yes" /><Param Section="JobParameters" Name="ResultsBaseName" Value="Results" Reqd="Yes" /><Param Section="1_AScore" Name="AScoreParamFilenames" Value="" Reqd="No" Step="1" /><Param Section="1_AScore" Name="AScoreSearchType" Value="sequest" Reqd="No" Step="1" /><Param Section="1_AScore" Name="ExtractionType" Value="Sequest First Hits" Reqd="No" Step="1" /><Param Section="2_Mage" Name="MageOperations" Value="GetFactors, ExtractFromJobs, ImportRawFileList" Reqd="Yes" Step="2" /><Param Section="2_Mage" Name="ExtractionSource" Value="JobsFromDataPackageID" Reqd="Yes" Step="2" /><Param Section="2_Mage" Name="ExtractionType" Value="Sequest First Hits" Reqd="No" Step="2" /><Param Section="2_Mage" Name="KeepAllResults" Value="Yes" Reqd="No" Step="2" /><Param Section="2_Mage" Name="MSGFcutoff" Value="All Pass" Reqd="No" Step="2" /><Param Section="2_Mage" Name="ResultFilterSetID" Value="All Pass" Reqd="No" Step="2" /><Param Section="2_Mage" Name="FactorsSource" Value="FactorsFromDataPackageID" Reqd="Yes" Step="2" /><Param Section="2_Mage" Name="ReporterIonSource" Value="JobsFromDataPackageIDForTool" Reqd="Yes" Step="2" /><Param Section="4_Ape" Name="ApeOperations" Value="RunWorkflow" Reqd="Yes" Step="4" /><Param Section="4_Ape" Name="ApeWorkflowName" Value="" Reqd="Yes" Step="4" /><Param Section="4_Ape" Name="ApeWorflowStepList" Value="all" Reqd="Yes" Step="4" /><Param Section="4_Ape" Name="ApeCompactDatabase" Value="True" Reqd="Yes" Step="4" /><Param Section="5_Cyclops" Name="CyclopsWorkflowName" Value="" Reqd="Yes" Step="5" /><Param Section="5_Cyclops" Name="RunProteinProphet" Value="False" Reqd="Yes" Step="5" /><Param Section="5_Cyclops" Name="Consolidation_Factor" Value="" Reqd="No" Step="5" /><Param Section="5_Cyclops" Name="Fixed_Effect" Value="" Reqd="No" Step="5" />',1)
