/****** Object:  Table [T_Scripts_History] ******/
/****** RowCount: 149 ******/
SET IDENTITY_INSERT [T_Scripts_History] ON
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (1,0,'(none)','','','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (2,1,'Sequest','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Sequest"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (3,2,'ICR2LS','ICR','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (4,4,'TIC_ICR','TIC','<JobScript Name="TIC_ICR"><Step Number="1" Tool="Bogus" /></JobScript>','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (5,5,'TIC_LCQ','TIC','','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (6,6,'QTOFSequest','','','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (7,7,'QTOFPek','','','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (8,8,'DeNovoID','','','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (9,9,'AgilentSequest','Seq','','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (10,10,'MLynxPek','ICR','','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (11,11,'AgilentTOFPek','ICR','','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (12,12,'LTQ_FTPek','ICR','','',,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (13,13,'MASIC_Finnigan','SIC','<JobScript Name="MASIC_Finnigan"><Step Number="1" Tool="MASIC_Finnigan" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (14,14,'MASIC_Agilent','SIC','<JobScript Name="MASIC_Agilent"><Step Number="1" Tool="MASIC_Agilent" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (15,15,'XTandem','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (16,16,'Decon2LS','DLS','<JobScript Name="Decon2LS"><Step Number="1" Tool="Decon2LS" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (17,17,'TIC_D2L','TDL','<JobScript Name="TIC_D2L"><Step Number="1" Tool="TIC_D2L" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (18,18,'Decon2LS_Agilent','DLS','<JobScript Name="Decon2LS_Agilent"><Step Number="1" Tool="Decon2LS_Agilent" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (19,19,'TIC_D2L_Agilent','TDL','<JobScript Name="TIC_D2L_Agilent"><Step Number="1" Tool="TIC_D2L_Agilent" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (20,20,'Inspect','INS','<JobScript Name="Inspect"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="DTA_Split"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="Inspect" Special="Clone"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="InspectResultsAssembly"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="DataExtractor"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="6" /></Step></JobScript>','',,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (21,21,'XTandemSplice','XTS','<JobScript Name="XTandemSplice"><Step Number="10" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="11" Tool="DataExtractor"><Depends_On Step_Number="10" /></Step><Step Number="12" Tool="Results_Transfer"><Depends_On Step_Number="11" /></Step></JobScript>','',,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (22,22,'MSXML_Gen','XML','<JobScript Name="MSXML_Gen"><Step Number="1" Tool="MSXML_Gen" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (23,23,'DTA_Gen','DTA','<JobScript Name="DTA_Gen"><Step Number="1" Tool="DTA_Gen" Special="Job_Results" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',0,'3/20/2009 10:51:22 AM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (24,22,'MSXML_Gen','XML','<JobScript Name="MSXML_Gen"><Step Number="1" Tool="MSXML_Gen" Special="Job_Results" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'3/24/2009 2:20:58 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (25,24,'MSClusterDAT_Gen','DAT','<JobScript Name="MSClusterDAT_Gen"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSClusterDTAtoDAT"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',,'5/22/2009 6:20:04 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (26,24,'MSClusterDAT_Gen','DAT','<JobScript Name="MSClusterDAT_Gen"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSClusterDTAtoDAT"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="2" Enable_Only="1" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',,'5/22/2009 6:21:32 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (27,24,'MSClusterDAT_Gen','DATddd','<JobScript Name="MSClusterDAT_Gen"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSClusterDTAtoDAT"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="2" Enable_Only="1" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',,'5/23/2009 4:16:51 PM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (28,24,'MSClusterDAT_Gen','DAT','<JobScript Name="MSClusterDAT_Gen"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSClusterDTAtoDAT"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="2" Enable_Only="1" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',,'5/23/2009 4:16:52 PM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (29,24,'MSClusterDAT_Gen','MSCD','<JobScript Name="MSClusterDAT_Gen"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSClusterDTAtoDAT"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="2" Enable_Only="1" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',,'5/23/2009 4:17:33 PM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (30,25,'DTA_Import','DTA','<JobScript Name="DTA_Import"><Step Number="1" Tool="DTA_Import" Special="Job_Results" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'6/4/2009 10:10:50 PM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (31,26,'XTandem_DTA_Import','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="7" Tool="DTA_Import"><Depends_On Step_Number="1" /></Step><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /><Depends_On Step_Number="7" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step></JobScript>','',,'6/4/2009 10:10:50 PM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (32,2,'ICR2LS','ICR','<JobScript Name="ICR2LS"><Step Number="1" Tool="ICR2LS" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'6/4/2009 10:11:05 PM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (33,12,'LTQ_FTPek','ICR','<JobScript Name="LTQ_FTPek"><Step Number="1" Tool="LTQ_FTPek" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'6/4/2009 10:11:05 PM','PNL\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (34,27,'Sequest_UseExistingExternalDTA','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Sequest"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',,'7/29/2009 4:18:12 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (35,24,'MSClusterDAT_Gen','MSCD','<JobScript Name="MSClusterDAT_Gen"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSClusterDTAtoDAT"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="2" Enable_Only="1" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',,'8/24/2009 11:41:33 AM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (36,28,'XTandem_UseExistingExternalDTA','XTM','','',,'10/7/2009 11:16:10 PM','pnl\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (37,28,'XTandem_UseExistingExternalDTA','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',,'10/8/2009 7:53:47 AM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (38,29,'Decon2LS_V2','DLS','<JobScript Name="Decon2LS_V2"><Step Number="1" Tool="Decon2LS_V2" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'11/2/2009 2:01:38 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (39,30,'OMSSA','OMS','<JobScript Name="OMSSA"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="OMSSA"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',,'11/13/2009 3:03:42 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (40,29,'Decon2LS_V2','DLS','<JobScript Name="Decon2LS_V2"><Step Number="1" Tool="Decon2LS_V2" /><Step Number="2" Tool="LCMSFeatureFinder" /><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',,'12/21/2009 2:59:35 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (41,29,'Decon2LS_V2','DLS','<JobScript Name="Decon2LS_V2"><Step Number="1" Tool="Decon2LS_V2" /><Step Number="2" Tool="LCMSFeatureFinder"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',,'12/21/2009 3:00:19 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (42,29,'Decon2LS_V2','DLS','<JobScript Name="Decon2LS_V2"><Step Number="1" Tool="Decon2LS_V2" /><Step Number="2" Tool="LCMSFeatureFinder"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',,'1/5/2010 12:51:57 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (43,16,'Decon2LS','DLS','<JobScript Name="Decon2LS"><Step Number="1" Tool="Decon2LS" /><Step Number="2" Tool="LCMSFeatureFinder"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',,'1/5/2010 12:52:07 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (44,31,'LCMSFeatureFinder_UseExistingResults','DLS','<JobScript Name="Decon2LS"><Step Number="4" Tool="LCMSFeatureFinder"><Depends_On Step_Number="1" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',,'1/5/2010 1:03:21 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (45,16,'Decon2LS','DLS','<JobScript Name="Decon2LS"><Step Number="1" Tool="Decon2LS" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'1/5/2010 1:04:23 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (46,31,'LCMSFeatureFinder_UseExistingResults','DLS','<JobScript Name="Decon2LS"><Step Number="3" Tool="LCMSFeatureFinder"><Depends_On Step_Number="1" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="3" /></Step></JobScript>','',,'1/5/2010 1:04:48 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (47,29,'Decon2LS_V2','DLS','<JobScript Name="Decon2LS_V2"><Step Number="1" Tool="Decon2LS_V2" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'1/6/2010 6:43:27 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (48,32,'Sequest_DTARefinery','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="DTA_Refinery"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="Sequest"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="2" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'2/23/2010 5:49:01 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (49,33,'XTandem_HPC','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem_HPC"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',,'3/1/2010 8:12:44 PM','pnl\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (50,34,'XTandem_DTARefinery','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="DTA_Refinery"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="XTandem"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="2" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'3/13/2010 8:57:19 AM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (51,33,'XTandem_HPC','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="DTA_Split"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="XTandem_HPC"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'3/15/2010 5:12:24 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (52,29,'Decon2LS_V2','DLS','<JobScript Name="Decon2LS_V2"><Step Number="1" Tool="Decon2LS_V2" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="LCMSFeatureFinder"><Depends_On Step_Number="1" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="3" /></Step></JobScript>','',,'4/5/2010 4:52:17 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (53,35,'Inspect_UseExistingExternalDTA','INS','<JobScript Name="Inspect"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="DTA_Split"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="Inspect" Special="Clone"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="InspectResultsAssembly"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="DataExtractor"><Depends_On Step_Number="5" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="6" /></Step></JobScript>','',,'4/7/2010 5:14:07 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (54,35,'Inspect_UseExistingExternalDTA','INS','<JobScript Name="Inspect"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="DTA_Split"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="Inspect" Special="Clone"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="InspectResultsAssembly"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="DataExtractor"><Depends_On Step_Number="5" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="6" /></Step></JobScript>','',,'4/7/2010 5:14:36 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (55,29,'Decon2LS_V2','DLS','<JobScript Name="Decon2LS_V2"><Step Number="1" Tool="Decon2LS_V2" /><Step Number="2" Tool="LCMSFeatureFinder"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',,'5/19/2010 6:29:16 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (56,36,'PRIDE_mzXML','PZX','<JobScript Name="PRIDE_mzXML"><Step Number="1" Tool="mzXML_Aggregator" /></JobScript>','',,'5/26/2010 10:28:19 AM','PNL\D3J410')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (57,37,'Phospho_FDR_Aggregator','PFA','<JobScript Name="Phospho_FDR_Aggregator"><Step Number="1" Tool="Phospho_FDR_Aggregator" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'6/15/2010 2:36:13 PM','pnl\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (58,37,'Phospho_FDR_Aggregator','PFA','<JobScript Name="Phospho_FDR_Aggregator"><Step Number="1" Tool="Phospho_FDR_Aggregator" /></JobScript>','',,'7/13/2010 4:10:18 PM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (59,1,'Sequest','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Sequest"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'7/22/2010 5:34:19 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (60,32,'Sequest_DTARefinery','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="DTA_Refinery"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="Sequest"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="MSGF"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="2" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="9" Tool="Results_Transfer"><Depends_On Step_Number="6" /></Step></JobScript>','',,'7/22/2010 5:35:24 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (61,27,'Sequest_UseExistingExternalDTA','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Sequest"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'7/22/2010 5:37:23 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (62,15,'XTandem','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'7/22/2010 5:39:03 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (63,26,'XTandem_DTA_Import','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="7" Tool="DTA_Import"><Depends_On Step_Number="1" /></Step><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /><Depends_On Step_Number="7" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step></JobScript>','',,'7/22/2010 6:01:52 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (64,25,'DTA_Import','DTA','<JobScript Name="DTA_Import"><Step Number="1" Tool="DTA_Import" Special="Job_Results" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'7/22/2010 6:04:00 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (65,26,'XTandem_DTA_Import','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="7" Tool="DTA_Import"><Depends_On Step_Number="1" /></Step><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /><Depends_On Step_Number="7" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step><Step Number="9" Tool="Results_Transfer"><Depends_On Step_Number="7" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step></JobScript>','',,'7/22/2010 6:04:31 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (66,34,'XTandem_DTARefinery','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="DTA_Refinery"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="XTandem"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="MSGF"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="2" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="9" Tool="Results_Transfer"><Depends_On Step_Number="6" /></Step></JobScript>','',,'7/22/2010 6:05:11 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (67,33,'XTandem_HPC','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="DTA_Split"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="XTandem_HPC"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="DataExtractor"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="6" /></Step></JobScript>','',,'7/22/2010 6:05:41 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (68,33,'XTandem_HPC','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="DTA_Split"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="XTandem_HPC"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="MSGF"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="6" /></Step></JobScript>','',,'7/22/2010 6:05:59 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (69,21,'XTandemSplice','XTS','<JobScript Name="XTandemSplice"><Step Number="10" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="11" Tool="DataExtractor"><Depends_On Step_Number="10" /></Step><Step Number="12" Tool="Results_Transfer"><Depends_On Step_Number="11" /></Step></JobScript>','',,'7/22/2010 6:06:31 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (70,27,'Sequest_UseExistingExternalDTA','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Sequest"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'7/22/2010 6:06:54 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (71,28,'XTandem_UseExistingExternalDTA','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'7/22/2010 6:07:54 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (72,28,'XTandem_UseExistingExternalDTA','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'7/22/2010 6:09:06 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (73,28,'XTandem_UseExistingExternalDTA','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'7/22/2010 6:09:35 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (74,27,'Sequest_UseExistingExternalDTA','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Sequest"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'7/22/2010 6:09:47 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (75,35,'Inspect_UseExistingExternalDTA','INS','<JobScript Name="Inspect"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="DTA_Split"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="Inspect" Special="Clone"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="InspectResultsAssembly"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="DataExtractor"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="MSGF"><Depends_On Step_Number="6" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',,'7/22/2010 6:10:30 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (76,20,'Inspect','INS','<JobScript Name="Inspect"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="DTA_Split"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="Inspect" Special="Clone"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="InspectResultsAssembly"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="DataExtractor"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="MSGF"><Depends_On Step_Number="6" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="7" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',,'7/22/2010 6:11:27 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (77,20,'Inspect','INS','<JobScript Name="Inspect"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="DTA_Split"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="Inspect" Special="Clone"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="InspectResultsAssembly"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="DataExtractor"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="MSGF"><Depends_On Step_Number="6" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="7" Enable_Only="1" /></Step><Step Number="9" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',,'7/22/2010 6:11:52 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (78,29,'Decon2LS_V2','DLS','<JobScript Name="Decon2LS_V2"><Step Number="1" Tool="Decon2LS_V2" /><Step Number="2" Tool="LCMSFeatureFinder"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',,'8/4/2010 1:32:50 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (79,37,'Phospho_FDR_Aggregator','PFA','<JobScript Name="Phospho_FDR_Aggregator"><Step Number="1" Tool="Phospho_FDR_Aggregator" /></JobScript>','',,'10/7/2010 12:42:05 PM','D3J410 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (80,36,'PRIDE_mzXML','PZX','<JobScript Name="PRIDE_mzXML"><Step Number="1" Tool="mzXML_Aggregator" /></JobScript>','',,'10/7/2010 12:42:36 PM','D3J410 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (81,37,'Phospho_FDR_Aggregator','PFA','<JobScript Name="Phospho_FDR_Aggregator"><Step Number="1" Tool="Phospho_FDR_Aggregator" /></JobScript>','',,'10/15/2010 2:05:44 PM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (82,37,'Phospho_FDR_Aggregator','PFA','<JobScript Name="Phospho_FDR_Aggregator"><Step Number="1" Tool="Phospho_FDR_Aggregator" /></JobScript>','',,'10/15/2010 2:29:18 PM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (83,38,'Sequest_Extend_MSGF','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Sequest"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step><Step Number="7" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',,'10/22/2010 10:12:32 AM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (84,38,'Sequest_Extend_MSGF','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Sequest"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step><Step Number="7" Tool="MSGF"><Depends_On Step_Number="6" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',,'10/22/2010 10:12:59 AM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (85,38,'Sequest_Extend_MSGF','Seq','<JobScript Name="Sequest_AddMSGFToExisting"><Step Number="7" Tool="MSGF"><Depends_On Step_Number="6" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',,'10/22/2010 10:18:45 AM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (86,38,'Sequest_Extend_MSGF','Seq','<JobScript Name="Sequest_AddMSGFToExisting"><Step Number="7" Tool="MSGF" /><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',,'10/22/2010 10:19:03 AM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (87,38,'Sequest_Extend_MSGF','Seq','<JobScript Name="Sequest_AddMSGFToExisting"><Step Number="8" Tool="MSGF" /><Step Number="9" Tool="Results_Transfer"><Depends_On Step_Number="8" /></Step></JobScript>','',,'10/22/2010 10:20:49 AM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (88,39,'Sequest_No_MSGF','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Sequest"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',,'10/22/2010 1:18:40 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (89,38,'Sequest_Extend_MSGF','Seq','<JobScript Name="Sequest_AddMSGFToExisting"><Step Number="8" Tool="MSGF" /><Step Number="9" Tool="Results_Transfer"><Depends_On Step_Number="8" /></Step></JobScript>','',,'10/22/2010 1:22:41 PM','pnl\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (90,38,'Sequest_Extend_MSGF','Seq','<JobScript Name="Sequest_AddMSGFToExisting"><Step Number="7" Tool="MSGF" /><Depends_On Step_Number="6" /><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',,'10/22/2010 1:23:00 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (91,38,'Sequest_Extend_MSGF','Seq','<JobScript Name="Sequest_AddMSGFToExisting"><Step Number="7" Tool="MSGF" /><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',,'10/22/2010 1:24:07 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (92,38,'Sequest_Extend_MSGF','Seq','<JobScript Name="Sequest_AddMSGFToExisting"><Step Number="7" Tool="MSGF" /><Depends_On Step_Number="6" /><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',,'10/22/2010 1:25:48 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (93,38,'Sequest_Extend_MSGF','Seq','<JobScript Name="Sequest_AddMSGFToExisting"><Step Number="7" Tool="MSGF"><Depends_On Step_Number="6" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',,'10/22/2010 1:31:44 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (94,40,'LCMSFeature_Finder','LFF','<JobScript Name="LCMSFeature_Finder"><Step Number="1" Tool="LCMSFeatureFinder" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'11/3/2010 6:05:43 PM','pnl\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (95,41,'XTandem_No_MSGF','XTM','<JobScript Name="XTandem"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="XTandem"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',,'12/2/2010 4:53:51 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (96,42,'XTandem_Extend_MSGF','XTM','<JobScript Name="XTandem_AddMSGFToExisting"><Step Number="7" Tool="MSGF"><Depends_On Step_Number="6" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="7" /></Step></JobScript>','',,'12/2/2010 4:58:31 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (97,43,'Inspect_Single','INS','<JobScript Name="Inspect"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="Inspect"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="InspectResultsAssembly"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="MSGF"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="6" /></Step></JobScript>','',,'1/31/2011 10:12:08 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (98,44,'Sequest_DTARefinery_No_MSGF','Seq','<JobScript Name="Sequest"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="DTA_Refinery"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="Sequest"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="2" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'3/16/2011 6:18:10 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (99,45,'Sequest_DTARefinery_Extend_MSGF','Seq','<JobScript Name="Sequest_DTARefinery_AddMSGFToExisting"><Step Number="9" Tool="MSGF"><Depends_On Step_Number="8" /></Step><Step Number="10" Tool="Results_Transfer"><Depends_On Step_Number="9" /></Step></JobScript>','',,'3/16/2011 6:21:49 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (100,40,'LCMSFeature_Finder','LFF','<JobScript Name="LCMSFeature_Finder"><Step Number="1" Tool="LCMSFeatureFinder" Special="ExtractJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'3/21/2011 12:54:09 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (101,40,'LCMSFeature_Finder','LFF','<JobScript Name="LCMSFeature_Finder"><Step Number="1" Tool="LCMSFeatureFinder" Special="ExtractJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'3/21/2011 12:55:03 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (102,40,'LCMSFeature_Finder','LFF','<JobScript Name="LCMSFeature_Finder"><Step Number="1" Tool="LCMSFeatureFinder" Special="ExtractJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'3/21/2011 12:55:21 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (103,40,'LCMSFeature_Finder','LFF','<JobScript Name="LCMSFeature_Finder"><Step Number="1" Tool="LCMSFeatureFinder" Special="ExtractJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'3/21/2011 1:06:38 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (104,40,'LCMSFeature_Finder','LFF','<JobScript Name="LCMSFeature_Finder"><Step Number="1" Tool="LCMSFeatureFinder" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'3/21/2011 2:34:30 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (105,46,'MSXML_Bruker','XML','<JobScript Name="MSXML_Bruker"><Step Number="1" Tool="MSXML_Bruker" Special="Job_Results" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'3/30/2011 6:02:19 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (106,40,'LCMSFeature_Finder','LFF','<JobScript Name="LCMSFeature_Finder"><Step Number="1" Tool="LCMSFeatureFinder" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'4/4/2011 7:54:34 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (107,40,'LCMSFeature_Finder','LFF','<JobScript Name="LCMSFeature_Finder"><Step Number="1" Tool="LCMSFeatureFinder" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'4/4/2011 7:54:47 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (108,47,'MultiAlign','MA','<JobScript Name="MultiAlign"><Step Number="1" Tool="MultiAlign" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'4/18/2011 2:43:10 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (109,48,'MultiAlign_Aggregator','MA','','',,'4/18/2011 3:09:06 PM','pnl\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (110,48,'MultiAlign_Aggregator','MA','<JobScript Name="MultiAlign"><Step Number="1" Tool="MultiAlign" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'4/18/2011 3:09:28 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (111,48,'MultiAlign_Aggregator','MA','<JobScript Name="MultiAlign"><Step Number="1" Tool="MultiAlign" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'4/18/2011 3:10:03 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (112,47,'MultiAlign','MAL','<JobScript Name="MultiAlign"><Step Number="1" Tool="MultiAlign" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'4/20/2011 12:22:00 PM','pnl\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (113,48,'MultiAlign_Aggregator','MAL','<JobScript Name="MultiAlign"><Step Number="1" Tool="MultiAlign" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'4/20/2011 12:22:00 PM','pnl\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (114,48,'MultiAlign_Aggregator','MAA','<JobScript Name="MultiAlign_Aggregator"><Step Number="1" Tool="MultiAlign_Aggregator" Special="ExtractSourceJobFromComment" /></JobScript>','',,'4/29/2011 7:51:09 AM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (115,36,'PRIDE_mzXML','PZX','<JobScript Name="PRIDE_mzXML"><Step Number="1" Tool="mzXML_Aggregator" /></JobScript>','',,'5/5/2011 1:46:24 PM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (116,49,'MSGFDB','MSG','<JobScript Name="MSGFDB"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="MSGFDB"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'7/29/2011 4:52:26 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (117,50,'MSGFDB_DTARefinery','MSG','<JobScript Name="MSGFDB"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="DTA_Refinery"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="2" Test="No_Parameters" /></Step><Step Number="4" Tool="MSGFDB"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="DataExtractor"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="MSGF"><Depends_On Step_Number="5" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="8" Tool="Results_Transfer"><Depends_On Step_Number="2" Test="Target_Skipped" /><Depends_On Step_Number="6" Enable_Only="1" /></Step><Step Number="9" Tool="Results_Transfer"><Depends_On Step_Number="6" /></Step></JobScript>','',,'7/29/2011 4:53:48 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (118,51,'MSAlign','MSA','<JobScript Name="MSAlign"><Step Number="1" Tool="MSXML_Gen" /><Step Number="2" Tool="MSDeconv"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="MSAlign"><Depends_On Step_Number="2" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="3" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="3" /></Step></JobScript>','',,'10/13/2011 2:51:30 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (119,52,'MAC_Spectral_Counting','SCo','<JobScript Name="MAC_Spectral_Counting"><Step Number="1" Tool="Mage"><Description>Extract DMS results and 
metadata into cache database</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Filters data by iterating over MSGF and PPM
to determine FDRs of 0.1%, 1%, 5%, and 10% based
on forward/reverse database searches.</Description></Step><Step Number="3" Tool="Cyclops"><Depends_On Step_Number="2" /><Description>Plots the data and performs a Beta-binomial model
analysis on the data to determine significant changes
between factors for spectral count results.</Description></Step></JobScript>','',,'11/3/2011 7:29:38 PM','pnl\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (120,53,'MAC_IMPROV','IPV','<JobScript Name="MAC_IMPROV"><Step Number="1" Tool="APE" /><Step Number="2" Tool="Mage"><Depends_On Step_Number="1" /></Step></JobScript>','',,'11/3/2011 7:29:38 PM','pnl\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (121,52,'MAC_Spectral_Counting','SCo','<JobScript Name="MAC_Spectral_Counting"><Step Number="1" Tool="Mage"><Description>Extract DMS results and 
metadata into cache database</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Filters data by iterating over MSGF and PPM
to determine FDRs of 0.1%, 1%, 5%, and 10% based
on forward/reverse database searches.</Description></Step><Step Number="3" Tool="Cyclops"><Depends_On Step_Number="2" /><Description>Plots the data and performs a Beta-binomial model
analysis on the data to determine significant changes
between factors for spectral count results.</Description></Step></JobScript>','',,'11/4/2011 2:50:38 PM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (122,51,'MSAlign','MSA','<JobScript Name="MSAlign"><Step Number="1" Tool="MSXML_Gen" /><Step Number="2" Tool="MSDeconv"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="MSAlign"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="3" Enable_Only="1" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="3" /></Step></JobScript>','',,'11/7/2011 12:05:03 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (123,53,'MAC_IMPROV','IPV','<JobScript Name="MAC_IMPROV"><Step Number="1" Tool="APE"><Description>Import features from 
MT database into cache database
</Description></Step><Step Number="2" Tool="Mage"><Depends_On Step_Number="1" /><Description>Import contents of files 
from data package to cache database
</Description></Step></JobScript>','',,'11/7/2011 7:49:56 PM','pnl\D3L243')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (124,52,'MAC_Spectral_Counting','SCo','<JobScript Name="MAC_Spectral_Counting"><Step Number="1" Tool="Mage"><Description>Extract DMS results and 
metadata into cache database</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Filters data by iterating over MSGF and PPM
to determine FDRs of 0.1%, 1%, 5%, and 10% based
on forward/reverse database searches.</Description></Step><Step Number="3" Tool="Cyclops"><Depends_On Step_Number="2" /><Description>Plots the data and performs a Beta-binomial model
analysis on the data to determine significant changes
between factors for spectral count results.</Description></Step></JobScript>','',,'11/8/2011 12:39:24 PM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (125,54,'MSGFDB_MzXml','MSG','<JobScript Name="MSGFDB_MzXml"><Step Number="1" Tool="MSXML_Gen" /><Step Number="2" Tool="MSGFDB"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="DataExtractor"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="MSGF"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',,'11/20/2011 4:26:56 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (126,51,'MSAlign','MSA','<JobScript Name="MSAlign"><Step Number="1" Tool="MSXML_Gen" /><Step Number="2" Tool="MSDeconv"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="MSAlign"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="3" Enable_Only="1" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="3" /></Step></JobScript>','',,'11/23/2011 4:59:47 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (127,55,'MSAlign_Bruker','MSA','<JobScript Name="MSAlign_Bruker"><Step Number="1" Tool="MSXML_Bruker" /><Step Number="2" Tool="MSDeconv"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="MSAlign"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="3" Enable_Only="1" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="3" /></Step></JobScript>','',,'11/23/2011 5:01:34 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (128,52,'MAC_Spectral_Counting','SCo','<JobScript Name="MAC_Spectral_Counting"><Step Number="1" Tool="Mage"><Description>Extract DMS results and 
metadata into cache database</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Filters data by iterating over MSGF and PPM
to determine FDRs of 0.1%, 1%, 5%, and 10% based
on forward/reverse database searches.</Description></Step><Step Number="3" Tool="Cyclops"><Depends_On Step_Number="2" /><Description>Plots the data and performs a Beta-binomial model
analysis on the data to determine significant changes
between factors for spectral count results.</Description></Step></JobScript>','',,'12/1/2011 8:06:53 AM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (129,56,'SMAQC_MSMS','SQC','<JobScript Name="SMAQC_MSMS"><Step Number="1" Tool="SMAQC" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'12/1/2011 11:35:52 AM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (130,56,'SMAQC_MSMS','SQC','<JobScript Name="SMAQC_MSMS"><Step Number="1" Tool="SMAQC" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'12/1/2011 11:44:59 AM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (131,52,'MAC_Spectral_Counting','SCo','<JobScript Name="MAC_Spectral_Counting"><Step Number="1" Tool="Mage"><Description>Extract DMS results and 
metadata into cache database</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Filters data by iterating over MSGF and PPM
to determine FDRs of 0.1%, 1%, 5%, and 10% based
on forward/reverse database searches.</Description></Step><Step Number="3" Tool="Cyclops"><Depends_On Step_Number="2" /><Description>Plots the data and performs a Beta-binomial model
analysis on the data to determine significant changes
between factors for spectral count results.</Description></Step></JobScript>','',,'12/2/2011 9:08:07 AM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (132,56,'SMAQC_MSMS','SQC','<JobScript Name="SMAQC_MSMS"><Step Number="1" Tool="SMAQC" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'12/2/2011 4:00:25 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (133,56,'SMAQC_MSMS','SQC','<JobScript Name="SMAQC_MSMS"><Step Number="1" Tool="SMAQC" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'12/2/2011 5:18:23 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (134,56,'SMAQC_MSMS','SQC','<JobScript Name="SMAQC_MSMS"><Step Number="1" Tool="SMAQC" Special="ExtractSourceJobFromComment" /><Step Number="2" Tool="Results_Transfer"><Depends_On Step_Number="1" /></Step></JobScript>','',,'12/2/2011 5:19:06 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (135,49,'MSGFDB','MSG','<JobScript Name="MSGFDB"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="MSGFDB"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" Test="No_Parameters" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'1/8/2012 10:45:14 AM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (136,49,'MSGFDB','MSG','<JobScript Name="MSGFDB"><Step Number="1" Tool="DTA_Gen" /><Step Number="2" Tool="MSMSSpectraPreprocessor"><Depends_On Step_Number="1" Test="No_Parameters" /></Step><Step Number="3" Tool="MSGFDB"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="DataExtractor"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="MSGF"><Depends_On Step_Number="4" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="5" Enable_Only="1" /></Step><Step Number="7" Tool="Results_Transfer"><Depends_On Step_Number="5" /></Step></JobScript>','',,'1/8/2012 12:59:36 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (137,58,'MSDeconv_Bruker','MSA','<JobScript Name="MSDeconv_Bruker"><Step Number="1" Tool="MSXML_Bruker" /><Step Number="2" Tool="MSDeconv"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="2" Enable_Only="1" /></Step><Step Number="4" Tool="Results_Transfer"><Depends_On Step_Number="2" /></Step></JobScript>','',0,'1/12/2012 7:52:18 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (138,59,'MSGFDB_Bruker','MSG','<JobScript Name="MSGFDB_MzXml"><Step Number="1" Tool="MSXML_Bruker" /><Step Number="2" Tool="MSGFDB"><Depends_On Step_Number="1" /></Step><Step Number="3" Tool="DataExtractor"><Depends_On Step_Number="2" /></Step><Step Number="4" Tool="MSGF"><Depends_On Step_Number="3" /></Step><Step Number="5" Tool="Results_Transfer"><Depends_On Step_Number="1" Test="Target_Skipped" /><Depends_On Step_Number="4" Enable_Only="1" /></Step><Step Number="6" Tool="Results_Transfer"><Depends_On Step_Number="4" /></Step></JobScript>','',0,'1/31/2012 2:01:43 PM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (139,60,'MAC_Label_Free','LBF','<JobScript Name="MAC_Label_Free"><Step Number="1" Tool="Mage"><Description>Import Factors, Data Package from data package to cache database

</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Import features from MT database into cache database

</Description></Step></JobScript>','<Param Section="JobParameters" Name="transferFolderPath" Value="" /><Param Section="JobParameters" Name="ResultsBaseName" Value="Results" Reqd="Yes" /><Param Section="1_Mage" Name="MageOperations" Value="GetFactors,ImportJobList" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="FactorsSource" Value="FactorsFromDataPackageID" Reqd="Yes" Step="1" /><Param Section="2_Ape" Name="ApeOperations" Value="GetQRollupResults" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="QRollupMTSServer" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="QRollupMTSDatabase" Value="" Reqd="Yes" Step="2" /><Param Section="3_Cyclops" Name="CyclopsWorkflowName" Value="" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="Consolidation_Factor" Value="" Reqd="No" Step="3" /><Param Section="3_Cyclops" Name="Fixed_Effect" Value="" Reqd="No" Step="3" />',1,'2/1/2012 8:30:32 AM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (140,60,'MAC_Label_Free','LBF','<JobScript Name="MAC_Label_Free"><Step Number="1" Tool="Mage"><Description>Import Factors, Data Package from data package to cache database
</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Import features from MT database into cache database
</Description></Step></JobScript>','<Param Section="JobParameters" Name="transferFolderPath" Value="" /><Param Section="JobParameters" Name="AnalysisType" Value="LabelFree" Reqd="Yes" /><Param Section="JobParameters" Name="ResultsBaseName" Value="Results" Reqd="Yes" /><Param Section="1_Mage" Name="MageOperations" Value="GetFactors,ImportJobList" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="FactorsSource" Value="FactorsFromDataPackageID" Reqd="Yes" Step="1" /><Param Section="2_Ape" Name="ApeOperations" Value="GetQRollupResults,RunWorkflow" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="QRollupMTSServer" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="QRollupMTSDatabase" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeWorflowStepList" Value="all" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeCompactDatabase" Value="True" Reqd="Yes" Step="2" /><Param Section="3_Cyclops" Name="CyclopsWorkflowName" Value="" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="Consolidation_Factor" Value="" Reqd="No" Step="3" /><Param Section="3_Cyclops" Name="Fixed_Effect" Value="" Reqd="No" Step="3" />',1,'2/1/2012 12:09:43 PM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (141,60,'MAC_Label_Free','LBF','<JobScript Name="MAC_Label_Free"><Step Number="1" Tool="Mage"><Description>Import Factors, Data Package from data package to cache database
</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Import features from MT database into cache database
</Description></Step></JobScript>','<Param Section="JobParameters" Name="transferFolderPath" Value="" /><Param Section="JobParameters" Name="AnalysisType" Value="LabelFree" Reqd="Yes" /><Param Section="JobParameters" Name="ResultsBaseName" Value="Results" Reqd="Yes" /><Param Section="1_Mage" Name="MageOperations" Value="GetFactors,ImportJobList" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="FactorsSource" Value="FactorsFromDataPackageID" Reqd="Yes" Step="1" /><Param Section="2_Ape" Name="ApeOperations" Value="GetQRollupResults,RunWorkflow" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="QRollupMTSServer" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="QRollupMTSDatabase" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeWorkflowName" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeWorflowStepList" Value="all" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeCompactDatabase" Value="True" Reqd="Yes" Step="2" /><Param Section="3_Cyclops" Name="CyclopsWorkflowName" Value="" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="Consolidation_Factor" Value="" Reqd="No" Step="3" /><Param Section="3_Cyclops" Name="Fixed_Effect" Value="" Reqd="No" Step="3" />',1,'2/1/2012 12:13:22 PM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (142,60,'MAC_Label_Free','LBF','<JobScript Name="MAC_Label_Free"><Step Number="1" Tool="Mage"><Description>Import Factors, Data Package from data package to cache database
</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Import features from MT database into cache database
</Description></Step><Step Number="3" Tool="Cyclops"><Depends_On Step_Number="2" /><Description>Plots the data and performs a Beta-binomial model analysis on the data to determine significant changes between factors for spectral count results.
</Description></Step></JobScript>','<Param Section="JobParameters" Name="transferFolderPath" Value="" /><Param Section="JobParameters" Name="AnalysisType" Value="LabelFree" Reqd="Yes" /><Param Section="JobParameters" Name="ResultsBaseName" Value="Results" Reqd="Yes" /><Param Section="1_Mage" Name="MageOperations" Value="GetFactors,ImportJobList" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="FactorsSource" Value="FactorsFromDataPackageID" Reqd="Yes" Step="1" /><Param Section="2_Ape" Name="ApeOperations" Value="GetQRollupResults,RunWorkflow" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="QRollupMTSServer" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="QRollupMTSDatabase" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeWorkflowName" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeWorflowStepList" Value="all" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeCompactDatabase" Value="True" Reqd="Yes" Step="2" /><Param Section="3_Cyclops" Name="CyclopsWorkflowName" Value="" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="Consolidation_Factor" Value="" Reqd="No" Step="3" /><Param Section="3_Cyclops" Name="Fixed_Effect" Value="" Reqd="No" Step="3" />',1,'2/1/2012 3:17:36 PM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (143,60,'MAC_Label_Free','LBF','<JobScript Name="MAC_Label_Free"><Step Number="1" Tool="Mage"><Description>Import Factors, Data Package from data package to cache database
</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Import features from MT database into cache database
</Description></Step><Step Number="3" Tool="Cyclops"><Depends_On Step_Number="2" /><Description>Plots the data and performs a Beta-binomial model analysis on the data to determine significant changes between factors for spectral count results.
</Description></Step></JobScript>','<Param Section="JobParameters" Name="transferFolderPath" Value="" /><Param Section="JobParameters" Name="AnalysisType" Value="LabelFree" Reqd="Yes" /><Param Section="JobParameters" Name="ResultsBaseName" Value="Results" Reqd="Yes" /><Param Section="1_Mage" Name="MageOperations" Value="GetFactors,ImportJobList" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="FactorsSource" Value="FactorsFromDataPackageID" Reqd="Yes" Step="1" /><Param Section="2_Ape" Name="ApeOperations" Value="GetQRollupResults,RunWorkflow" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="QRollupMTSServer" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="QRollupMTSDatabase" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeWorkflowName" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeWorflowStepList" Value="all" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeCompactDatabase" Value="True" Reqd="Yes" Step="2" /><Param Section="3_Cyclops" Name="CyclopsWorkflowName" Value="" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="RunProteinProphet" Value="False" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="Consolidation_Factor" Value="" Reqd="No" Step="3" /><Param Section="3_Cyclops" Name="Fixed_Effect" Value="" Reqd="No" Step="3" />',1,'3/15/2012 4:07:28 PM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (144,52,'MAC_Spectral_Counting','SCo','<JobScript Name="MAC_Spectral_Counting"><Step Number="1" Tool="Mage"><Description>Extract DMS results and 
metadata into cache database</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Filters data by iterating over MSGF and PPM
to determine FDRs of 0.1%, 1%, 5%, and 10% based
on forward/reverse database searches.</Description></Step><Step Number="3" Tool="Cyclops"><Depends_On Step_Number="2" /><Description>Plots the data and performs a Beta-binomial model
analysis on the data to determine significant changes
between factors for spectral count results.</Description></Step></JobScript>','<Param Section="JobParameters" Name="transferFolderPath" Value="" /><Param Section="JobParameters" Name="AnalysisType" Value="SpectralCounting" Reqd="Yes" /><Param Section="JobParameters" Name="ResultsBaseName" Value="Results" Reqd="Yes" /><Param Section="1_Mage" Name="MageOperations" Value="ExtractFromJobs, GetFactors, GetFDRTables" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="MageOperations" Value="ExtractFromJobs, GetFactors, GetFDRTables" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="ExtractionSource" Value="JobsFromDataPackageID" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="ExtractionType" Value="Sequest First Hits" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="KeepAllResults" Value="Yes" Reqd="No" Step="1" /><Param Section="1_Mage" Name="ResultFilterSetID" Value="All Pass" Reqd="No" Step="1" /><Param Section="1_Mage" Name="MSGFCutoff" Value="All Pass" Reqd="No" Step="1" /><Param Section="1_Mage" Name="FactorsSource" Value="FactorsFromDataPackageID" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="MageFDRFiles" Value="" Reqd="No" Step="1" /><Param Section="2_Ape" Name="ApeWorkflowName" Value="20111024_FDR_workflow.xml" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeOperations" Value="RunWorkflow" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeWorflowStepList" Value="all" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeCompactDatabase" Value="True" Reqd="Yes" Step="2" /><Param Section="3_Cyclops" Name="CyclopsWorkflowName" Value="Cyclops_SpectralCount_WF.xml" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="RunProteinProphet" Value="False" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="Consolidation_Factor" Value="" Reqd="No" Step="3" /><Param Section="3_Cyclops" Name="Fixed_Effect" Value="" Reqd="No" Step="3" />',1,'3/15/2012 4:08:52 PM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (145,53,'MAC_IMPROV','IPV','<JobScript Name="MAC_IMPROV"><Step Number="1" Tool="APE"><Description>Import features from 
MT database into cache database
</Description></Step><Step Number="2" Tool="Mage"><Depends_On Step_Number="1" /><Description>Import contents of files 
from data package to cache database
</Description></Step></JobScript>','<Param Section="JobParameters" Name="transferFolderPath" Value="" /><Param Section="JobParameters" Name="ResultsBaseName" Value="Results" Reqd="Yes" /><Param Section="1_Ape" Name="ApeOperations" Value="GetImprovResults" Reqd="Yes" Step="1" /><Param Section="1_Ape" Name="ApeMTSServer" Value="Albert" Reqd="Yes" Step="1" /><Param Section="1_Ape" Name="ApeMTSDatabase" Value="MT_SeaSediments_ERB_P744" Reqd="Yes" Step="1" /><Param Section="1_Ape" Name="ImprovMinPMTQuality" Value="1.0" Reqd="Yes" Step="1" /><Param Section="2_Mage" Name="MageOperations" Value="ImportDataPackageFiles" Reqd="Yes" Step="2" /><Param Section="2_Mage" Name="DataPackageSourceFolderName" Value="ImportFiles" Reqd="Yes" Step="2" />',1,'3/26/2012 5:30:35 PM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (146,60,'MAC_Label_Free','LBF','<JobScript Name="MAC_Label_Free"><Step Number="1" Tool="Mage"><Description>Import Factors, Data Package from data package to cache database
</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Import features from MT database into cache database
</Description></Step><Step Number="3" Tool="Cyclops"><Depends_On Step_Number="2" /><Description>Plots the data and performs a Beta-binomial model analysis on the data to determine significant changes between factors for spectral count results.
</Description></Step></JobScript>','<Param Section="JobParameters" Name="transferFolderPath" Value="" /><Param Section="JobParameters" Name="AnalysisType" Value="LabelFree" Reqd="Yes" /><Param Section="JobParameters" Name="ResultsBaseName" Value="Results" Reqd="Yes" /><Param Section="1_Mage" Name="MageOperations" Value="GetFactors,ImportJobList" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="FactorsSource" Value="FactorsFromDataPackageID" Reqd="Yes" Step="1" /><Param Section="2_Ape" Name="ApeOperations" Value="GetQRollupResults,RunWorkflow" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeMTSServer" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeMTSDatabase" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeMDState" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeMDIniFilename" Value="" Reqd="No" Step="" /><Param Section="2_Ape" Name="ApeWorkflowName" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeWorflowStepList" Value="all" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeCompactDatabase" Value="True" Reqd="Yes" Step="2" /><Param Section="3_Cyclops" Name="CyclopsWorkflowName" Value="" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="RunProteinProphet" Value="False" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="Consolidation_Factor" Value="" Reqd="No" Step="3" /><Param Section="3_Cyclops" Name="Fixed_Effect" Value="" Reqd="No" Step="3" />',1,'3/26/2012 5:31:06 PM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (147,60,'MAC_Label_Free','LBF','<JobScript Name="MAC_Label_Free"><Step Number="1" Tool="Mage"><Description>Import Factors, Data Package from data package to cache database
</Description></Step><Step Number="2" Tool="APE"><Depends_On Step_Number="1" /><Description>Import features from MT database into cache database
</Description></Step><Step Number="3" Tool="Cyclops"><Depends_On Step_Number="2" /><Description>Plots the data and performs a Beta-binomial model analysis on the data to determine significant changes between factors for spectral count results.
</Description></Step></JobScript>','<Param Section="JobParameters" Name="transferFolderPath" Value="" /><Param Section="JobParameters" Name="AnalysisType" Value="LabelFree" Reqd="Yes" /><Param Section="JobParameters" Name="ResultsBaseName" Value="Results" Reqd="Yes" /><Param Section="1_Mage" Name="MageOperations" Value="GetFactors,ImportJobList" Reqd="Yes" Step="1" /><Param Section="1_Mage" Name="FactorsSource" Value="FactorsFromDataPackageID" Reqd="Yes" Step="1" /><Param Section="2_Ape" Name="ApeOperations" Value="GetViperResults,RunWorkflow" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeMTSServer" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeMTSDatabase" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeMDState" Value="2" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeMDIniFilename" Value="" Reqd="No" Step="" /><Param Section="2_Ape" Name="ApeWorkflowName" Value="" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeWorflowStepList" Value="all" Reqd="Yes" Step="2" /><Param Section="2_Ape" Name="ApeCompactDatabase" Value="True" Reqd="Yes" Step="2" /><Param Section="3_Cyclops" Name="CyclopsWorkflowName" Value="" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="RunProteinProphet" Value="False" Reqd="Yes" Step="3" /><Param Section="3_Cyclops" Name="Consolidation_Factor" Value="" Reqd="No" Step="3" /><Param Section="3_Cyclops" Name="Fixed_Effect" Value="" Reqd="No" Step="3" />',1,'3/27/2012 1:21:19 PM','D3M480 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (148,61,'Sequest_Extend_IDPicker','Seq','<JobScript Name="Sequest_Extend_IDPicker"><Step Number="8" Tool="IDPicker"><Depends_On Step_Number="5" /></Step><Step Number="9" Tool="Results_Transfer"><Depends_On Step_Number="8" /></Step></JobScript>','',0,'5/9/2012 10:27:12 AM','D3L243 (via DMSWebUser)')
INSERT INTO [T_Scripts_History] (Entry_ID, ID, Script, Results_Tag, Contents, Parameters, Backfill_to_DMS, Entered, Entered_By) VALUES (149,62,'MAC_iTRAQ','ITQ','<JobScript Name="MAC_iTRAQ"><Step Number="1" Tool="AScore"><Description>Run AScore on multiple datasets individually and import resultsinto cache database
</Description></Step><Step Number="2" Tool="Mage"><Depends_On Step_Number="1" /><Description>Import Factors, Data Package from data package to cache database
</Description></Step><Step Number="3" Tool="IDM"><Depends_On Step_Number="2" /><Description>Calculates interference percentage in MS data
</Description></Step><Step Number="4" Tool="APE"><Depends_On Step_Number="3" /><Description>Filters iTRAQ results
</Description></Step><Step Number="5" Tool="Cyclops"><Depends_On Step_Number="4" /><Description>Plots the data and performs a Beta-binomial model analysis on the data to determine significant changes between factors for spectral count results.
</Description></Step></JobScript>','<Param Section="JobParameters" Name="transferFolderPath" Value="" /><Param Section="JobParameters" Name="AnalysisType" Value="iTRAQ" Reqd="Yes" /><Param Section="JobParameters" Name="ResultsBaseName" Value="Results" Reqd="Yes" /><Param Section="1_AScore" Name="AScoreParamFilenames" Value="" Reqd="No" Step="1" /><Param Section="1_AScore" Name="AScoreSearchType" Value="sequest" Reqd="No" Step="1" /><Param Section="1_AScore" Name="ExtractionType" Value="Sequest First Hits" Reqd="No" Step="1" /><Param Section="2_Mage" Name="MageOperations" Value="GetFactors, ExtractFromJobs, ImportRawFileList" Reqd="Yes" Step="2" /><Param Section="2_Mage" Name="ExtractionSource" Value="JobsFromDataPackageID" Reqd="Yes" Step="2" /><Param Section="2_Mage" Name="ExtractionType" Value="Sequest First Hits" Reqd="No" Step="2" /><Param Section="2_Mage" Name="KeepAllResults" Value="Yes" Reqd="No" Step="2" /><Param Section="2_Mage" Name="MSGFcutoff" Value="All Pass" Reqd="No" Step="2" /><Param Section="2_Mage" Name="ResultFilterSetID" Value="All Pass" Reqd="No" Step="2" /><Param Section="2_Mage" Name="FactorsSource" Value="FactorsFromDataPackageID" Reqd="Yes" Step="2" /><Param Section="2_Mage" Name="ReporterIonSource" Value="JobsFromDataPackageIDForTool" Reqd="Yes" Step="2" /><Param Section="4_Ape" Name="ApeOperations" Value="RunWorkflow" Reqd="Yes" Step="4" /><Param Section="4_Ape" Name="ApeWorkflowName" Value="" Reqd="Yes" Step="4" /><Param Section="4_Ape" Name="ApeWorflowStepList" Value="all" Reqd="Yes" Step="4" /><Param Section="4_Ape" Name="ApeCompactDatabase" Value="True" Reqd="Yes" Step="4" /><Param Section="5_Cyclops" Name="CyclopsWorkflowName" Value="" Reqd="Yes" Step="5" /><Param Section="5_Cyclops" Name="RunProteinProphet" Value="False" Reqd="Yes" Step="5" /><Param Section="5_Cyclops" Name="Consolidation_Factor" Value="" Reqd="No" Step="5" /><Param Section="5_Cyclops" Name="Fixed_Effect" Value="" Reqd="No" Step="5" />',1,'5/11/2012 2:23:36 PM','D3M480 (via DMSWebUser)')
SET IDENTITY_INSERT [T_Scripts_History] OFF
