/****** Object:  Database [DMS5] ******/
CREATE DATABASE [DMS5] ON  PRIMARY 
( NAME = N'DMS4_dat', FILENAME = N'C:\DMS Database Files\DMS5_data.mdf' , SIZE = 487680KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'DMS4_log', FILENAME = N'C:\DMS Database Files\DMS5_log.ldf' , SIZE = 24832KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'DMS5', @new_cmptlevel=80
GO
ALTER DATABASE [DMS5] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DMS5] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DMS5] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DMS5] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DMS5] SET ARITHABORT OFF 
GO
ALTER DATABASE [DMS5] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DMS5] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [DMS5] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DMS5] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DMS5] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DMS5] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DMS5] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DMS5] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DMS5] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DMS5] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DMS5] SET  READ_WRITE 
GO
ALTER DATABASE [DMS5] SET RECOVERY FULL 
GO
ALTER DATABASE [DMS5] SET  MULTI_USER 
GO
ALTER DATABASE [DMS5] SET TORN_PAGE_DETECTION OFF 
GO
