/****** Object:  Database [DMS5] ******/
CREATE DATABASE [DMS5] ON  PRIMARY 
( NAME = N'DMS4_dat', FILENAME = N'C:\DMS Database Files\DMS5_data.mdf' , SIZE = 615296KB , MAXSIZE = UNLIMITED, FILEGROWTH = 80KB )
 LOG ON 
( NAME = N'DMS4_log', FILENAME = N'C:\DMS Database Files\DMS5_log.ldf' , SIZE = 13632KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'DMS5', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DMS5].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [DMS5] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [DMS5] SET ANSI_NULLS ON 
GO
ALTER DATABASE [DMS5] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DMS5] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [DMS5] SET ARITHABORT OFF 
GO
ALTER DATABASE [DMS5] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DMS5] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [DMS5] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DMS5] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DMS5] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DMS5] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DMS5] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DMS5] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DMS5] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DMS5] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DMS5] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DMS5] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DMS5] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DMS5] SET TRUSTWORTHY ON 
GO
ALTER DATABASE [DMS5] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DMS5] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DMS5] SET  READ_WRITE 
GO
ALTER DATABASE [DMS5] SET RECOVERY FULL 
GO
ALTER DATABASE [DMS5] SET  MULTI_USER 
GO
ALTER DATABASE [DMS5] SET PAGE_VERIFY NONE  
GO
ALTER DATABASE [DMS5] SET DB_CHAINING OFF 
GO
GRANT CONNECT TO [BUILTIN\Administrators]
GO
GRANT ALTER TO [D3L243]
GO
GRANT CONNECT TO [D3L243]
GO
GRANT SHOWPLAN TO [D3L243]
GO
GRANT CONNECT TO [DMSReader]
GO
GRANT CONNECT TO [DMSWebUser]
GO
GRANT CONNECT TO [LOC-DMS_Archive_Admin]
GO
GRANT CONNECT TO [LOC-DMS_Archive_Restore]
GO
GRANT CONNECT TO [LOC-DMS_DS_Entry]
GO
GRANT CONNECT TO [LOC-DMS_EUS_Admin]
GO
GRANT CONNECT TO [LOC-DMS_Experiment_Entry]
GO
GRANT CONNECT TO [LOC-DMS_Instrument_Admin]
GO
GRANT CONNECT TO [LOC-DMS_LC_Column_Admin]
GO
GRANT CONNECT TO [LOC-DMS_Ops_Admin]
GO
GRANT CONNECT TO [LOC-DMS_Org_Database_Admin]
GO
GRANT CONNECT TO [LOC-DMS_ParamFile_Admin]
GO
GRANT CONNECT TO [LOC-DMS_Sample_Prep_Admin]
GO
GRANT CONNECT TO [LOC-DMS_Storage_Admin]
GO
GRANT CONNECT TO [LOC-DMS_Web_Run_Scheduler]
GO
GRANT CONNECT TO [nwfs_samba_user]
GO
GRANT CONNECT TO [PNL\D3M480]
GO
GRANT CONNECT TO [PNL\D3M578]
GO
GRANT SHOWPLAN TO [PNL\D3M578]
GO
GRANT CONNECT TO [PNL\D3M580]
GO
GRANT SHOWPLAN TO [PNL\D3M580]
GO
GRANT CONNECT TO [pnl\mtsadmin]
GO
GRANT CONNECT TO [RBAC-Analysis_Job_Runner]
GO
GRANT CONNECT TO [RBAC-DMS_Guest]
GO
GRANT CONNECT TO [RBAC-DMS_User]
GO
GRANT SHOWPLAN TO [RBAC-DMS_User]
GO
GRANT CONNECT TO [RBAC-Web_Analysis]
GO
