/****** Object:  Table [T_AuxInfo_Description] ******/
/****** RowCount: 174 ******/
SET IDENTITY_INSERT [T_AuxInfo_Description] ON
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (45,'Genotype of Bacterium',244,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (46,'General Description of Experimental Test',244,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (47,'Date Started',245,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (48,'Date Completed',245,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (49,'Growth Media Recipe',245,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (50,'Source of Innoculum',245,4,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (51,'Volume of Culture',245,5,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (52,'Vessel used for Culture',245,6,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (53,'Growth Temperature',245,7,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (54,'Shaker Rate',245,8,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (55,'Duration of Incubation',245,9,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (56,'Comments',245,10,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (57,'Date Started',246,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (58,'Date Completed',246,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (59,'Growth Media Recipe',246,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (60,'Label (N14/N15)',246,4,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (61,'Volume of Culture',246,5,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (62,'Vessel used for Culture',246,6,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (63,'Growth Temperature',246,7,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (64,'Shaker Rate',246,8,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (65,'Duration of Incubation',246,9,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (66,'Harvest Time (after stress)',246,10,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (67,'Final OD at 600 (<1 for accuracy)',246,12,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (68,'Cell Count',246,13,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (69,'Harvest Growth Phase',246,14,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (70,'Harvest Conditions',246,15,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (71,'Stress Description',246,16,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (72,'Comments',246,17,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (73,'Centrifugation (G force, duration, temperature)',247,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (74,'Sample Wash',247,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (75,'Sample Fractionation',247,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (76,'Method',248,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (77,'Ratio',248,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (78,'Note',248,3,256,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (79,'Beads',249,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (80,'Centrifuge After',249,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (81,'Repetition',249,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (82,'Rpm',249,4,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (83,'Time',249,5,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (84,'Chemical',250,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (85,'Time',250,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (86,'Temperature',251,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (87,'Time',251,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (88,'Temperature',252,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (89,'Time',252,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (90,'Setting',253,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (91,'Time',253,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (92,'Centrifuge Name',254,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (93,'Centrifuge Time',254,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (94,'Centrifuge Speed (RPM)',254,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (96,'Procedure Name',255,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (97,'Column Type',256,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (98,'Buffer A',256,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (99,'Buffer B',256,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (100,'Gradient',256,4,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (101,'Time',256,5,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (102,'Reagent Type',257,1,64,'Y')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (103,'Concentration',257,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (104,'Time',257,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (105,'Reagent Type',258,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (106,'Concentration',258,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (107,'Time',258,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (108,'Reagent Type',259,1,64,'Y')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (109,'Concentration',259,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (110,'Time',259,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (111,'Type',260,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (112,'Concentration',260,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (113,'Alkylation Agent',261,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (114,'Temperature',261,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (115,'Time',261,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (116,'Labeling Procedure',262,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (117,'Buffer Type',263,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (118,'Concentration (mM)',263,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (119,'PH',263,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (120,'Column or Method',264,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (121,'Enzyme Type',265,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (122,'Enzyme to Protein ratio',265,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (123,'Time',265,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (124,'Antibody Affinity',266,4,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (125,'Column Type',267,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (126,'MWCO',268,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (127,'Buffer',268,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (128,'Membrane',268,4,120,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (129,'Concentration',269,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (130,'Lyophilization',269,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (131,'Volume',269,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (132,'Room',270,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (133,'Freezer',270,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (134,'Shelf',270,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (135,'Drawer',270,4,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (136,'Row',270,5,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (137,'Box',270,6,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (138,'Volume of buffer used',268,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (139,'Solvent System',271,1,32,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (140,'Packing Material',271,2,32,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (141,'Column Length',271,3,32,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (142,'Pump System',271,4,32,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (143,'Column In-service Date',271,5,32,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (144,'Column Inner Dia.',271,6,32,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (145,'(placeholder)',272,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (146,'(placeholder)',273,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (148,'Oxidation (PhIAT)',262,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (149,'Oxidizing Agent',262,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (150,'Oxidation Incubation Time',262,4,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (151,'Molar Excess of Label Over Cys Residues',262,5,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (152,'Labelling Incubation Time',262,6,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (153,'Type of Column',275,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (154,'Bed Volume / Size of Column',275,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (155,'Size of Fractions Collected',275,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (157,'Bed Volume',276,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (158,'Elution Buffer Used',276,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (159,'Size of Fractions Collected',276,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (160,'Time',277,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (161,'Temperature',277,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (162,'Incubation Time',260,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (163,'Incubation Conditions',260,4,256,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (164,'Column Outer Dia.',271,7,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (165,'Gradient Program',271,8,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (166,'Comment',271,9,256,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (167,'Source',278,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (168,'Proposal Number',278,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (169,'Comment',249,6,256,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (170,'Amount of Cells',249,7,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (171,'Incubation Temperature',265,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (172,'RPM',279,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (173,'Time',279,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (174,'Temperature',279,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (175,'Volume of Labeling Agent',262,7,32,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (176,'Room',280,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (177,'Freezer',280,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (178,'Shelf',280,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (179,'Drawer',280,4,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (180,'Row',280,5,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (181,'Box',280,6,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (182,'Replicate of (sample name)',281,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (183,'Cultivation Method',281,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (184,'Medium Name',281,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (185,'Medium Component Varion(s) (name, conc)',281,4,256,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (186,'Aerobicity',281,5,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (187,'Dissolved Oxygen (% air sat.)',281,6,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (188,'Electro Donor(s) (name, conc)',281,7,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (189,'Electron Acceptor(s) (name, conc)',281,8,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (190,'Dilution Rate (h -1)',281,9,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (191,'Growth Rate (h -1)',281,10,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (192,'Carbon Source (name, conc)',281,11,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (193,'Growth Limiting Nutrient (name, conc)',281,12,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (194,'Liquid Volume of Culture (L)',281,13,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (195,'Gas Composition',281,14,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (196,'Gas Flow Rate (L/min)',281,15,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (197,'Temperature (C)',281,16,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (198,'pH',281,17,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (199,'Agitation (RPM)',281,18,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (200,'Column type',282,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (201,'Buffer A',282,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (202,'Buffer B',282,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (203,'Gradient',282,4,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (204,'Time',282,5,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (205,'Num. Fractions',282,6,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (206,'Fraction Size',282,7,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (207,'Room',283,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (208,'Freezer',283,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (209,'Shelf',283,3,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (210,'Drawer',283,4,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (211,'Row',283,5,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (212,'Box',283,6,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (213,'Mandated by',284,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (214,'Specific Hazards',284,2,256,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (215,'Protective Equipment Required',284,3,128,'Y')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (216,'Other Comments',284,4,256,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (217,'Type',285,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (218,'Buffer used',285,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (219,'Plate',286,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (220,'Well',286,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (221,'Number of Cycles',287,1,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (222,'Pressure',287,2,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (224,'Time',287,4,64,'N')
INSERT INTO [T_AuxInfo_Description] (ID, Name, Parent_ID, Sequence, DataSize, HelperAppend) VALUES (225,'Time at Ambient Pressure',287,5,64,'N')
SET IDENTITY_INSERT [T_AuxInfo_Description] OFF
