/****** Object:  Table [T_AuxInfo_Subcategory] ******/
/****** RowCount: 43 ******/
SET IDENTITY_INSERT [T_AuxInfo_Subcategory] ON
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (244,'General',1011,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (245,'Starter Culture Conditions',1011,2)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (246,'Sample Culture Growth Conditions',1011,3)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (247,'Protein Preparation',1011,4)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (248,'Procedure',1013,0)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (249,'Bead Beating',1000,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (250,'Enzymatic Digest',1000,2)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (251,'Freeze/Thaw',1000,3)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (252,'French Press',1000,4)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (253,'Sonication',1000,5)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (254,'Centrifugation',1004,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (255,'Membrane Procedure',1004,2)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (256,'Protein Separation',1004,3)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (257,'Inorganic Reagent',1001,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (258,'Organic Reagent',1001,2)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (259,'Surfactant',1001,3)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (260,'Reagents',1002,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (261,'Alkylation',1003,2)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (262,'Labeling',1003,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (263,'Buffer',1005,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (264,'Desalt',1005,2)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (265,'Enzyme',1005,3)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (266,'Purification',1007,0)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (267,'SPE',1006,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (268,'Dialysis',1006,2)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (269,'Conditions',1008,0)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (270,'Location',1009,0)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (271,'General',1014,0)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (272,'(placeholder)',1012,0)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (273,'(placeholder)',1015,0)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (275,'Size Exclusion',1006,3)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (276,'Avidin',1006,4)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (277,'Thermal',1001,4)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (278,'Funding',1016,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (279,'Ultracenterfuge',1008,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (280,'Location',1017,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (281,'MCDL Sample Descriptions',1011,5)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (282,'Fractionation',1007,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (283,'Location',1018,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (284,'BSL2',1019,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (285,'Homogenization',1000,6)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (286,'Well Plate',1009,1)
INSERT INTO [T_AuxInfo_Subcategory] (ID, Name, Parent_ID, Sequence) VALUES (287,'Barocycler',1000,7)
SET IDENTITY_INSERT [T_AuxInfo_Subcategory] OFF
