/****** Object:  Table [T_AuxInfo_Allowed_Values] ******/
/****** RowCount: 95 ******/
/****** Columns: AuxInfoID, Value ******/
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (102,'carbonate')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (102,'Guanidine HCL')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (102,'sodium')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (102,'thiourea')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (102,'urea')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (105,'ethanol')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (105,'Methanol')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (105,'n-propanol')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (108,'Chaps')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (108,'SDS')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (108,'Triton-X')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (111,'DTT')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (111,'TBP')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (111,'TCEP')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (116,'ICAT')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (116,'PEO/Biotin')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (116,'PhIAT')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (117,'Ammonium Bicarbonate (NH4HCO3)')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (117,'Trizma')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (120,'G-25')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (120,'PD-10')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (121,'arg-N')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (121,'lys-C')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (121,'Trypsin')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (124,'No')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (124,'Yes')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (125,'C-18')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (125,'SCX')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (128,'cellulose')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (128,'Cellulose')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (128,'float-a-lyzer')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (128,'float-a-lyzer')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (128,'slide-a-lyzer')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (128,'slide-a-lyzer')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (130,'No')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (130,'Yes')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (139,'A:0.1%Formic acid, balance water/B: 90%Acetonitrile, 0.1%Formic acid, balance water')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (139,'A:0.2%HOAc, 0.05%TFA, balance water/B:90%Acetonitrile, 0.05%TFA, balance water')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (140,'C-5-Jupiter')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (140,'C18-Jupiter')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (142,'Agilent')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (142,'Isco')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (142,'Shmidazu')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (144,'150 uM')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (144,'50 uM')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (149,'Performic Acid')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (164,'300 uM')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (60,'N14 Labeled')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (60,'N15 Labeled')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (69,'Late Log')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (69,'Mid Log')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (76,'Dry Weight')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (76,'Equal Concentration')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (76,'Wet Weight')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (79,'0.1 zirconia/silica')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (79,'glass')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (84,'lysosyme')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (97,'HIC')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (97,'HILIC')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (97,'SAX')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (97,'SCX')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (97,'SEC')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (167,'User')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (167,'Program')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (170,'volume')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (170,'wet weight')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (170,'dry weight')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (170,'cell number')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (111,'Imm. TCEP')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (116,'O18')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (69,'Steady State')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (120,'10X dilution w/Buffer')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (108,'Rapigest')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (105,'TFE')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (226,'IgY-12')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (200,'Phenomenex, JUPITER RP C18, 250x2.0 mm (5um 300Å)')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (200,'Phenomenex, JUPITER RP C18, 250x4.6 mm (5um 300Å)')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (200,'PolyLC, PolySULFOETHYL A, 200x2.1 mm (5um 300Å)')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (200,'PolyLC, PolySULFOETHYL A, 200x4.6 mm (5um 300Å)')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (200,'PolyLC, PolySULFOETHYL A, 35x2.1 mm (3um 300Å)')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (201,'0.05% TFA, 0.2% HOAc in H2O')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (201,'10 mM Ammonium Formate, pH 3.0; 25% ACN')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (202,'0.1% TFA, 90% ACN')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (202,'500 mM Ammonium Formate, pH 6.8; 25% ACN')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (226,'IgY-14')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (226,'SuperMix')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (226,'MARS-Human')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (226,'MARS-Mouse')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (226,'IgY-R7')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (226,'HIC')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (226,'HILIC')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (226,'SAX')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (226,'SCX')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (226,'SEC')
INSERT INTO [T_AuxInfo_Allowed_Values] VALUES (121,'Imm. Trypsin')
