/****** Object:  Table [T_EMSL_Instrument_Category_Assignment] ******/
/****** RowCount: 26 ******/
/****** Columns: Category_Name, Instrument_Name ******/
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Fourier-Transform Ion Cyclotron Resonance','12T_FTICR')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Fourier-Transform Ion Cyclotron Resonance','15T_FTICR')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Fourier-Transform Ion Cyclotron Resonance','9T_FTICR')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Ion Mobility Time of Flight','IMS_TOF_1')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Ion Mobility Time of Flight','IMS_TOF_2')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Ion Mobility Time of Flight','IMS_TOF_3')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Linear Ion trap (LTQ)','LTQ_1')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Linear Ion trap (LTQ)','LTQ_2')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Linear Ion trap (LTQ)','LTQ_3')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Linear Ion trap (LTQ)','LTQ_4')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Linear Ion trap (LTQ)','LTQ_ETD_1')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Orbitrap','Agilent_TOF1')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Orbitrap','Agilent_TOF2')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Orbitrap','Exact01')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Orbitrap','Exact02')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Orbitrap','Exact03')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Orbitrap','LTQ_Orb_1')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Orbitrap','LTQ_Orb_2')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Orbitrap','LTQ_Orb_3')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Orbitrap','VOrbiETD01')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Orbitrap','VOrbiETD02')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Orbitrap','VOrbiETD03')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Orbitrap','VOrbiETD04')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Triple Quadrupole','TSQ_1')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Triple Quadrupole','TSQ_2')
INSERT INTO [T_EMSL_Instrument_Category_Assignment] VALUES ('Triple Quadrupole','TSQ_3')
