/****** Object:  Table [T_Enzymes] ******/
/****** RowCount: 15 ******/
SET IDENTITY_INSERT [T_Enzymes] ON
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (0,'na','Not a real value','na','na','na','na','na',0,,'')
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (1,'No_Enzyme','no digestive enzyme was used','na','na','na','na','na',0,0,'')
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (10,'Trypsin','Standard tryptic digest','KR-','na','KR-','na','Standard',1,1,'Tryp_Pig')
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (11,'GluC','Endoproteinase GluC (aka V8)','ED-','na','ED-','na','Standard',1,12,'')
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (12,'LysC','Endoproteinase LysC','K-','na','K-','na','Standard',1,13,'')
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (13,'CnBR','Cyanogen Bromide','M-','na','M-','na','Standard',1,6,'')
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (14,'Proteinase_K','Proteinase K','GAVLIMCFW-','na','GAVLIMCFWW-','na','Standard',1,15,'')
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (15,'Trypsin_K','Trypsin, after K only','K-','P','K-','P','Standard',1,10,'Tryp_Pig')
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (16,'Elastase/Tryp/Chymo','Elastase, Trypsin, & Chymotrypsin','ALIVKRWFY-','P','ALIVKRWFY-','P','Standard',1,16,'Tryp_Pig')
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (17,'Trypsin_Modified','Modified Trypsin','KRLNH-','na','KRLNH-','na','Standard',1,2,'Tryp_Pig')
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (18,'AspN','AspN','D-','na','D-','na','Standard',0,14,'')
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (19,'Trypsin_R','Trypsin, after R only aka ArgC','R-','P','R-','P','Standard',1,11,'Tryp_Pig')
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (20,'Chymotrypsin','Chymotrypsin','FWYL-','na','FWYL-','na','Standard',1,3,'')
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (21,'ArgC','Endoproteinase ArgC','R-','na','R-','na','Standard',1,17,'')
INSERT INTO [T_Enzymes] (Enzyme_ID, Enzyme_Name, Description, P1, P1_Exception, P2, P2_Exception, Cleavage_Method, Cleavage_Offset, Sequest_Enzyme_Index, Protein_Collection_Name) VALUES (22,'Do_not_cleave','No cleavage anywhere; used when .Fasta is peptides, not proteins','B','na','B','na','Standard',1,18,'')
SET IDENTITY_INSERT [T_Enzymes] OFF
