/****** Object:  Table [T_Instrument_Name_Bkup] ******/
/****** RowCount: 51 ******/
/****** Columns: IN_name, Instrument_ID, IN_class, IN_source_path_ID, IN_storage_path_ID, IN_capture_method, IN_default_CDburn_sched, IN_Room_Number, IN_Description ******/
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LCQ_C2',1,'Finnigan_Ion_Trap',4,127,'secfso','','EMSL RM 1526','LCQ-C2')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LCQ_C1',2,'Finnigan_Ion_Trap',6,126,'secfso','','EMSL RM 1526','LCQ-C1')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('7T_FTICR',3,'Finnigan_FTICR',8,89,'secfso','','EMSL RM 1621','7 T FTICR')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('11T_FTICR',4,'Finnigan_FTICR',10,88,'ftp','','EMSL RM 1621','11.5 T FTICR')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('3T_FTICR',6,'Finnigan_FTICR',12,34,'ftp','','EMSL RM 1621','3.5 T FTICR')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('SW_TEST_LCQ',7,'Finnigan_Ion_Trap',16,195,'fso','','2228','LCQ TEST')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('SW_TEST_FTICR',8,'Finnigan_FTICR',18,176,'secfso','','2228','FTICR TEST')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LCQ_D1',9,'Finnigan_Ion_Trap',37,130,'secfso','','EMSL RM 1326','LCQ-DUO1')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LCQ_D2',10,'Finnigan_Ion_Trap',40,131,'secfso','','EMSL RM 1526','LCQ-DUO2')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('QTOF_1322',11,'QStar_QTOF',42,134,'fso','','EMSL RM 1521','QTOF-1322')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LCQ_XP1',12,'Finnigan_Ion_Trap',44,132,'secfso','','EMSL RM 1617','LCQ_DECA_XP1')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('9T_FTICR',13,'BRUKERFTMS',46,174,'secfso','','EMSL RM 1526','9.4T Bruker FTICR')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LCQ_XP2',14,'Finnigan_Ion_Trap',51,133,'secfso','','EMSL RM 1526','LCQ_DECA_XP2')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LCQ_C3',15,'Finnigan_Ion_Trap',56,128,'fso','','BLDG 331','LCQ_CLASSIC_3')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('SW_Test_Bruker',16,'BRUKERFTMS',87,177,'fso','','1553','Bruker SW Test Data')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('Agilent_SL1',17,'Agilent_Ion_Trap',94,123,'fso','','EMSL RM 1326','Agilent 1100 SL 1')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('QTOF_MM1',18,'Micromass_QTOF',96,135,'secfso','','EMSL RM 1526','Micromass QTOF 1')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('Agilent_XCT1',19,'Agilent_Ion_Trap',99,125,'fso','','EMSL RM 1326','Agilent 1100 LC/MSD XCT 1')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('Agilent_TOF1',20,'Agilent_TOF',101,124,'fso','','EMSL RM 1326','Agilent LC/MSD TOF 1')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('9T_FTICR_Q',21,'BRUKERFTMS',103,173,'fso','','EMSL RM 1326','9.4T Bruker w/special quad')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('11T_FTICR_B',22,'BRUKERFTMS',106,105,'secfso','','EMSL RM 1621','11T w/Bruker WS')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LTQ_1',23,'Finnigan_Ion_Trap',108,207,'secfso','','EMSL RM 1621','Finnigan LTQ #1')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('QC_LCQ',24,'Finnigan_Ion_Trap',110,189,'fso','','EMSL RM 1553','LCQ-type instrument for QC Process')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('QC_Bruker_ICR',25,'BRUKERFTMS',112,175,'fso','','EMSL RM 1553','Bruker-type instrument for QC Process')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('QC_Ag_XCT',26,'Agilent_Ion_Trap',114,113,'fso','','EMSL RM 1553','Agilent XCT-type instrument for QC Process')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('QC_Ag_TOF',27,'Agilent_TOF',116,188,'fso','','EMSL RM 1553','Agilent TOF-type instrument for QC Process')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('QC_MM_TOF',28,'Micromass_QTOF',118,117,'fso','','EMSL RM 1553','Micromass TOF-type instrument for QC Process')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('QC_LTQ',29,'Finnigan_Ion_Trap',120,190,'fso','','EMSL RM 1553','LTQ-type instrument for QC Process')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('QC_Fin_ICR',30,'Finnigan_FTICR',122,121,'fso','','EMSL RM 1553','Finnigan FTICR-type instrument for QC Process')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LCQ_JA_GTL',31,'Finnigan_Ion_Trap',137,136,'fso','','EMSL RM 2588','Virtual Instrument for GTL_Core')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LTQ_FT1',32,'LTQ_FT',139,211,'secfso','','EMSL RM 1444','LTQ-FT 1 (LTQ3QFVL41)')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LTQ_2',33,'Finnigan_Ion_Trap',141,208,'secfso','','EMSL RM 1621','Finnigan LTQ #2')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LTQ_3',34,'Finnigan_Ion_Trap',143,209,'secfso','','EMSL RM 1526','Finnigan LTQ #3')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('11T_Aux2',35,'BRUKERFTMS',145,144,'secfso','','EMSL RM 1621','Virtual 11T FTICR')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('12T_FTICR',36,'BRUKERFTMS',147,198,'fso','','EMSL RM 1521','12T FTICR')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('Agilent_TOF2',37,'Agilent_TOF',151,150,'secfso','','EMSL RM 1326','Agilent LC/MSD TOF2')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LTQ_FB1',38,'Finnigan_Ion_Trap',153,152,'secfso','','PSL RM 522','Agilent LC/Thermo LTQ (Fungal)')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LTQ_4',39,'Finnigan_Ion_Trap',156,210,'secfso','','EMSL RM 1444','Finnigan LTQ #4')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('QC_LTQ_FT',40,'LTQ_FT',158,191,'fso','','EMSL RM 1553','QC Process LTQ_FT')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('QC_LTQ_Orbitrap',41,'LTQ_FT',165,192,'fso','','EMSL RM 1553','Orbitrap Test Data')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('FHCRC_LTQ1',42,'Finnigan_Ion_Trap',167,166,'fso','','FHCRC, Seattle, WA','Fred Hutchinson Cancer Research Center Data')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LTQ_RITE',43,'Finnigan_Ion_Trap',169,168,'fso','','None','Virtual instrument for relocated RITE data')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LTQ_Orb_1',44,'LTQ_FT',171,172,'fso','','EMSL RM 1444','LTQ-Orbitrap 1')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('IMS_SCIEX_TOF',45,'IMS_Sciex_TOF',200,199,'secfso','','EMSL RM 1521','IMS QSTAR')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('IMS_BIOSPECT_TOF',46,'IMS_Biospect_TOF',202,201,'secfso','','EMSL RM 1521','IMS BOTOF')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('IMS_AGILENT_TOF1',47,'IMS_Agilent_TOF',204,203,'fso','','EMSL RM 1521','IMS AGILENT TOF')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LTQ_Orb_2',48,'LTQ_FT',206,205,'secfso','','EMSL RM 1444','LTQ-Orbitrap 2')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('TSQ_1',49,'Triple_Quad',213,212,'secfso','','EMSL RM 1621','TSQ_Quantum for MRM-based experiments')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('Broad_Orb1',50,'LTQ_FT',218,219,'fso','','MIT, Massachusets','Broad Institute LTQ-Orbitrap')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LTQ_Orb_3',51,'LTQ_FT',217,216,'secfso','','EMSL RM 1444','LTQ-Orbitrap 3')
INSERT INTO [T_Instrument_Name_Bkup] VALUES ('LTQ_ETD_1',52,'Finnigan_Ion_Trap',221,220,'secfso','','EMSL RM 1444','LTQ-ETD 1')
