/****** Object:  Table [T_Internal_Std_Composition] ******/
/****** RowCount: 27 ******/
/****** Columns: Component_ID, Mix_ID, Concentration ******/
INSERT INTO [T_Internal_Std_Composition] VALUES (10,2,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (11,2,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (12,2,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (13,2,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (14,2,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (58,3,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (59,3,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (61,3,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (62,3,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (63,3,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (10,4,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (11,4,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (12,4,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (13,4,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (14,4,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (58,4,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (61,4,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (63,4,'')
INSERT INTO [T_Internal_Std_Composition] VALUES (58,5,'0.21 mg/mL (5.9 µM)')
INSERT INTO [T_Internal_Std_Composition] VALUES (61,5,'1.00 mg/mL (59 µM)')
INSERT INTO [T_Internal_Std_Composition] VALUES (63,5,'0.363 mg/mL (3.1 µM)')
INSERT INTO [T_Internal_Std_Composition] VALUES (58,6,'0.21 mg/mL (5.9 µM)')
INSERT INTO [T_Internal_Std_Composition] VALUES (61,6,'1.00 mg/mL (59 µM)')
INSERT INTO [T_Internal_Std_Composition] VALUES (63,6,'0.363 mg/mL (3.1 µM)')
INSERT INTO [T_Internal_Std_Composition] VALUES (58,7,'0.21 mg/mL (5.9 µM)')
INSERT INTO [T_Internal_Std_Composition] VALUES (61,7,'1.00 mg/mL (59 µM)')
INSERT INTO [T_Internal_Std_Composition] VALUES (63,7,'0.363 mg/mL (3.1 µM)')
