/****** Object:  Table [T_Instrument_Group] ******/
/****** RowCount: 24 ******/
/****** Columns: IN_Group, Usage, Comment, Active, Default_Dataset_Type ******/
INSERT INTO [T_Instrument_Group] VALUES ('11T','Research','',0,1)
INSERT INTO [T_Instrument_Group] VALUES ('Agilent_GC-MS','Metabolomics','',1,18)
INSERT INTO [T_Instrument_Group] VALUES ('Agilent_Ion_Trap','Research','',0,2)
INSERT INTO [T_Instrument_Group] VALUES ('Agilent_TOF','Research','',0,1)
INSERT INTO [T_Instrument_Group] VALUES ('Agilent_TOF_V2','Research','',1,3)
INSERT INTO [T_Instrument_Group] VALUES ('Bruker_FTMS','Research','',1,1)
INSERT INTO [T_Instrument_Group] VALUES ('Bruker_QTOF','Research','',1,5)
INSERT INTO [T_Instrument_Group] VALUES ('Exactive','LC-HMS (no MS/MS)','',1,1)
INSERT INTO [T_Instrument_Group] VALUES ('FT_ZippedSFolders','Research','',0,1)
INSERT INTO [T_Instrument_Group] VALUES ('GC-TSQ','Metabolomics','',1,9)
INSERT INTO [T_Instrument_Group] VALUES ('IMS','Ion-mobility LC-IMS-MS','',1,6)
INSERT INTO [T_Instrument_Group] VALUES ('LCQ','Low res MS/MS','',1,2)
INSERT INTO [T_Instrument_Group] VALUES ('LTQ','Low res MS/MS','',1,2)
INSERT INTO [T_Instrument_Group] VALUES ('LTQ-ETD','Low res MS/MS ETD','',1,2)
INSERT INTO [T_Instrument_Group] VALUES ('LTQ-FT','LC-HMS with MS/MS','',1,3)
INSERT INTO [T_Instrument_Group] VALUES ('MALDI-Imaging','MALDI Imaging','',1,26)
INSERT INTO [T_Instrument_Group] VALUES ('MALDI-TOF','MALDI Spot','',1,26)
INSERT INTO [T_Instrument_Group] VALUES ('Micromass_TOF','Research','',0,1)
INSERT INTO [T_Instrument_Group] VALUES ('Orbitrap','LC-HMS with MS/MS','',1,3)
INSERT INTO [T_Instrument_Group] VALUES ('Orbitrap-HCD','LC-HMS with MS/MS; optionally HCD','',1,3)
INSERT INTO [T_Instrument_Group] VALUES ('Other','Research','',1,)
INSERT INTO [T_Instrument_Group] VALUES ('QTrap','Research','',1,3)
INSERT INTO [T_Instrument_Group] VALUES ('TSQ','MRM','',1,9)
INSERT INTO [T_Instrument_Group] VALUES ('VelosOrbi','LC-HMS with MS/MS; optionally ETD','',1,3)
