/****** Object:  Table [T_LC_Cart_Positions] ******/
/****** RowCount: 34 ******/
/****** Columns: ID, Name, Component_Type, Comment ******/
INSERT INTO [T_LC_Cart_Positions] VALUES (1,'Vinj1',20,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (2,'Vss1',32,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (3,'Vcs1',23,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (4,'Vmp1',36,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (5,'Vinj2',20,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (6,'Vss2',32,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (7,'Vcs2',23,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (8,'Vmp2',36,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (9,'VrefillA1',31,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (10,'VrefillA2',31,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (11,'VrefillB',31,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (12,'PumpA',10,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (13,'PumpB',10,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (14,'PumpC',10,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (15,'Controller',29,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (16,'PAL',28,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (17,'Newport',27,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (18,'Syringe',35,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (19,'Laptop',25,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (20,'Split_Sys1',33,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (21,'Split_Sys2',33,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (22,'Purge_Sys1',30,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (23,'Purge_Sys2',30,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (24,'Stir Motor_Sys1',34,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (25,'Stir Motor_Sys2',34,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (26,'Degasser',24,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (27,'Col1',22,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (28,'Col2',22,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (29,'Col3',22,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (30,'Col4',22,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (31,'Mixer_Sys1',26,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (32,'Mixer_Sys2',26,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (33,'Cart',37,'')
INSERT INTO [T_LC_Cart_Positions] VALUES (34,'Vse',38,'Single emitter valve')
