/****** Object:  Table [T_LC_Cart_Settings_History] ******/
/****** RowCount: 9 ******/
SET IDENTITY_INSERT [T_LC_Cart_Settings_History] ON
INSERT INTO [T_LC_Cart_Settings_History] (ID, Cart_ID, Valve_To_Column_Extension, Operating_Pressure, Interface_Configuration, Valve_To_Column_Extension_Dimensions, Mixer_Volume, Sample_Loop_Volume, Sample_Loading_Time, Split_Flow_Rate, Split_Column_Dimensions, Purge_Flow_Rate, Purge_Column_Dimensions, Purge_Volume, Acquisition_Time, Solvent_A, Solvent_B, Comment, Date_Of_Change, Entered, EnteredBy) VALUES (1,13,'ss tubing','10K psi','4-column / 4-emitter','','2.5 mL','5 uL','','20 uL /min','360 um OD x 15 um ID x 28.5 cm L','~ 2 mL /min','360 um OD x 50 um ID x 30 cm L','5 mL','100 min','Water w/ 0.2% HOAC; 0.05% TFA','ACN /Water (90/10) w/ 0.1% TFA','Currently running on Orbi_1.','10/21/2008 12:00:00 AM','10/21/2008 12:44:49 PM','D3G909')
INSERT INTO [T_LC_Cart_Settings_History] (ID, Cart_ID, Valve_To_Column_Extension, Operating_Pressure, Interface_Configuration, Valve_To_Column_Extension_Dimensions, Mixer_Volume, Sample_Loop_Volume, Sample_Loading_Time, Split_Flow_Rate, Split_Column_Dimensions, Purge_Flow_Rate, Purge_Column_Dimensions, Purge_Volume, Acquisition_Time, Solvent_A, Solvent_B, Comment, Date_Of_Change, Entered, EnteredBy) VALUES (2,11,'ss tubing','10K psi','XDK','','2.5 mL','5 uL','','20 uL /min','360 um OD x 15 um ID x 28.5 cm L','~ 2 mL /min','360 um OD x 50 um ID x 30 cm L','5 mL','100 min','0.1 % Formic acid in water','0.1 % Formic acid in ACN','Currently on 9T instrument.','10/21/2008 12:00:00 AM','10/21/2008 12:45:32 PM','D3G909')
INSERT INTO [T_LC_Cart_Settings_History] (ID, Cart_ID, Valve_To_Column_Extension, Operating_Pressure, Interface_Configuration, Valve_To_Column_Extension_Dimensions, Mixer_Volume, Sample_Loop_Volume, Sample_Loading_Time, Split_Flow_Rate, Split_Column_Dimensions, Purge_Flow_Rate, Purge_Column_Dimensions, Purge_Volume, Acquisition_Time, Solvent_A, Solvent_B, Comment, Date_Of_Change, Entered, EnteredBy) VALUES (3,12,'Yes','10,000 psi','A tip for each column','','2.5 mL','20uL','','2uL/min SCX 20uL/min anlytical','','2mL/min','','8mL','','Water 0.1% Formic Acid','ACN 0.1% Formic Acid','This is the 2 Dimensional Separation cart.  The transfer line between the injection valve and the 6 port column select valve is an SCX column.  The column select valve allows for the SCX fractions to be collected on an SPE column and then loaded to the analytical column','10/22/2008 12:00:00 AM','10/21/2008 12:54:21 PM','D3M957')
INSERT INTO [T_LC_Cart_Settings_History] (ID, Cart_ID, Valve_To_Column_Extension, Operating_Pressure, Interface_Configuration, Valve_To_Column_Extension_Dimensions, Mixer_Volume, Sample_Loop_Volume, Sample_Loading_Time, Split_Flow_Rate, Split_Column_Dimensions, Purge_Flow_Rate, Purge_Column_Dimensions, Purge_Volume, Acquisition_Time, Solvent_A, Solvent_B, Comment, Date_Of_Change, Entered, EnteredBy) VALUES (4,29,'No','10K psi','2 system, 4-column','No','2.5mL','5uL','','~20 uL/min','360u od x 15u id, 30 cm','~2 mL/min','360u od x 50u id, 30 cm','','80 minutes','0.1% formic acid in water','0.1% formic acid in acetonitrile','80 minute gradient: like the 100 gradient but the last 20 minutes are not acquired','10/27/2008 12:00:00 AM','10/27/2008 3:04:09 PM','D3P639')
INSERT INTO [T_LC_Cart_Settings_History] (ID, Cart_ID, Valve_To_Column_Extension, Operating_Pressure, Interface_Configuration, Valve_To_Column_Extension_Dimensions, Mixer_Volume, Sample_Loop_Volume, Sample_Loading_Time, Split_Flow_Rate, Split_Column_Dimensions, Purge_Flow_Rate, Purge_Column_Dimensions, Purge_Volume, Acquisition_Time, Solvent_A, Solvent_B, Comment, Date_Of_Change, Entered, EnteredBy) VALUES (5,29,'No','10K psi','4 column 2 system','No','2.5mL','5uL','','~20uL/min','360um x 15um x 30cm','~2mL/min','360um x 50um x 30cm','~10mL','80min','0.1% formic acid in water','0.1% formic acid in acetonitrile','80 minute gradient: like the 100 minute gradient but the last 20 minutes are not acquired','10/27/2008 12:00:00 AM','10/27/2008 4:42:11 PM','D3P639')
INSERT INTO [T_LC_Cart_Settings_History] (ID, Cart_ID, Valve_To_Column_Extension, Operating_Pressure, Interface_Configuration, Valve_To_Column_Extension_Dimensions, Mixer_Volume, Sample_Loop_Volume, Sample_Loading_Time, Split_Flow_Rate, Split_Column_Dimensions, Purge_Flow_Rate, Purge_Column_Dimensions, Purge_Volume, Acquisition_Time, Solvent_A, Solvent_B, Comment, Date_Of_Change, Entered, EnteredBy) VALUES (6,29,'','','','','','','','~17uL/min','360um x 15um x 40cm','','','','','','','Added B.O.B. to both systems','10/27/2008 12:00:00 AM','10/27/2008 4:43:23 PM','D3P639')
INSERT INTO [T_LC_Cart_Settings_History] (ID, Cart_ID, Valve_To_Column_Extension, Operating_Pressure, Interface_Configuration, Valve_To_Column_Extension_Dimensions, Mixer_Volume, Sample_Loop_Volume, Sample_Loading_Time, Split_Flow_Rate, Split_Column_Dimensions, Purge_Flow_Rate, Purge_Column_Dimensions, Purge_Volume, Acquisition_Time, Solvent_A, Solvent_B, Comment, Date_Of_Change, Entered, EnteredBy) VALUES (7,34,'Yes, for current monitoring','10,000 psi','single emitter','360x75um','2.5mL','5uL','50min','20ul/min','','2mL','','3mL B 8mL A','100min','TFA STD','TFA STD','This system has BOB installed on both systems as of today.  Voltage is being applied at both the head and tail of the column for more accurate current monitoring.','10/28/2008 12:00:00 AM','10/28/2008 12:59:12 PM','d3p704')
INSERT INTO [T_LC_Cart_Settings_History] (ID, Cart_ID, Valve_To_Column_Extension, Operating_Pressure, Interface_Configuration, Valve_To_Column_Extension_Dimensions, Mixer_Volume, Sample_Loop_Volume, Sample_Loading_Time, Split_Flow_Rate, Split_Column_Dimensions, Purge_Flow_Rate, Purge_Column_Dimensions, Purge_Volume, Acquisition_Time, Solvent_A, Solvent_B, Comment, Date_Of_Change, Entered, EnteredBy) VALUES (8,13,'','10,000 psi','','','2.5 mL','5 mL','50 min','20 uL/min','360 um OD x 15 um ID x 28.5 cm L','1.8 mL/min','360 um OD x 50 um ID x 30 cm L','','99 min','water w/0.2% HOAc and 0.05% TFA','ACN/Water (90/10) w/0.1% TFA','"BOB" installed.','10/28/2008 12:00:00 AM','10/28/2008 4:05:56 PM','d3g909')
INSERT INTO [T_LC_Cart_Settings_History] (ID, Cart_ID, Valve_To_Column_Extension, Operating_Pressure, Interface_Configuration, Valve_To_Column_Extension_Dimensions, Mixer_Volume, Sample_Loop_Volume, Sample_Loading_Time, Split_Flow_Rate, Split_Column_Dimensions, Purge_Flow_Rate, Purge_Column_Dimensions, Purge_Volume, Acquisition_Time, Solvent_A, Solvent_B, Comment, Date_Of_Change, Entered, EnteredBy) VALUES (9,18,'n/a','10Kpsi','standard atmospheric pressure','n/a','2.5mL','5uL','50 min','~20uL/min','360u x 15u x 30cm','~1.5 mL/min','360u x 50 u x 30 cm','5mL','100 min','0.2% HOAC, 0.05% TFA, balance water','90% ACN, 0.1% TFA, balance water','','11/3/2008 12:00:00 AM','11/3/2008 1:56:51 PM','d3c492')
SET IDENTITY_INSERT [T_LC_Cart_Settings_History] OFF
