/****** Object:  Table [T_Peptide_Synopsis_Reports_Sorting] ******/
/****** RowCount: 40 ******/
SET IDENTITY_INSERT [T_Peptide_Synopsis_Reports_Sorting] ON
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (1,'','No sort specified')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (3,'Dataset_Name DESC','')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (4,'Dataset_Name ASC','')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (5,'FileID ASC','Job #')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (6,'FileID DESC','Job #')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (7,'Records_Imported ASC','Total Peptides - Total')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (8,'Records_Imported DESC','Total Peptides - Total')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (9,'Unique_Peptides ASC','Total Peptides - Unique')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (10,'Unique_Peptides DESC','Total Peptides - Unique')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (11,'Peptides_Passed_Primary_Filter ASC','Filter Passing - Total')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (12,'Peptides_Passed_Primary_Filter DESC','Filter Passing - Total')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (13,'Unique_Peptides_Passed_Primary_Filter ASC','Filter Passing - Unique')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (14,'Unique_Peptides_Passed_Primary_Filter DESC','Filter Passing - Unique')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (15,'Peptide_Overlap_Overlap ASC','Peptide Overlap - Overlap')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (16,'Peptide_Overlap_Overlap DESC','Peptide Overlap - Overlap')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (17,'Peptide_Overlap_Master_Only ASC','Peptide Overlap - Master Job Only')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (18,'Peptide_Overlap_Master_Only DESC','Peptide Overlap - Master Job Only')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (19,'Peptide_Overlap_Job_Only ASC','Peptide Overlap - Job Only')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (20,'Peptide_Overlap_Job_Only DESC','Peptide Overlap - Job Only')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (21,'Peptide_Overlap_Total ASC','Peptide Overlap - Total')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (22,'Peptide_Overlap_Total DESC','Peptide Overlap - Total')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (23,'Unique_Proteins ASC','Proteins - Total')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (24,'Unique_Proteins DESC','Proteins - Total')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (25,'Unique_Proteins_With_1Plus_Passed_Peptides ASC','Proteins - With 1+ Filter Passing Peptides')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (26,'Unique_Proteins_With_1Plus_Passed_Peptides DESC','Proteins - With 1+ Filter Passing Peptides')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (27,'Unique_Proteins_With_Required_Passed_Peptides ASC','Proteins - With Required Filter Passing Peptides')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (28,'Unique_Proteins_With_Required_Passed_Peptides DESC','Proteins - With Required Filter Passing Peptides')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (29,'Protein_Overlap_Overlap ASC','Protein Overlap - Overlap')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (30,'Protein_Overlap_Overlap DESC','Protein Overlap - Overlap')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (31,'Protein_Overlap_Master_Only ASC','Protein Overlap - Master Only')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (32,'Protein_Overlap_Master_Only DESC','Protein Overlap - Master Only')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (33,'Protein_Overlap_Job_Only ASC','Protein Overlap - Job Only')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (34,'Protein_Overlap_Job_Only DESC','Protein Overlap - Job Only')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (35,'Protein_Overlap_Total ASC','Protein Overlap - Total')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (36,'Protein_Overlap_Total DESC','Protein Overlap - Total')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (37,'Dataset_Created ASC','Dataset Created')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (38,'Dataset_Created DESC','Dataset Created')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (39,'Job_Finished ASC','Job Run')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (40,'Job_Finished DESC','Job Run')
INSERT INTO [T_Peptide_Synopsis_Reports_Sorting] (Report_Sort_ID, Report_Sort_Value, Report_Sort_Comment) VALUES (41,'Protein_Overlap_Job_Only DESC, Dataset_Created ASC, Job_Finished ASC','Combine Test')
SET IDENTITY_INSERT [T_Peptide_Synopsis_Reports_Sorting] OFF
