/****** Object:  Table [T_Settings_Files] ******/
/****** RowCount: 36 ******/
SET IDENTITY_INSERT [T_Settings_Files] ON
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (1,'AgilentTOFPek','AgTofDefSettings.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (5,'ICR2LS','BrukerTICBaseSettings.txt','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (6,'ICR2LS','FTICRDefSettings.txt','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (7,'ICR2LS','TIC_ICR_DefSettings.txt','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (8,'LTQ_FTPek','LTQ_FTDefSettings.txt','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (9,'LTQ_FTPek','LTQ_FT_100Scans.txt','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (10,'MLynxPek','MMTofDefSettings.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (11,'QTOFPek','QTOFPekDefSettings.txt','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (12,'Sequest','30scans.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (13,'Sequest','30scans_ExtractMsn_Test.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (14,'Sequest','Agilent30scans.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (15,'Sequest','AgilentDefSettings.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (16,'Sequest','AgilentDefSettings_Create1,2,3,4Plus.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (17,'Sequest','Fiirst_100_scans.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (18,'Sequest','FinniganDefSettings.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (19,'Sequest','FinniganDefSettings_4_5PlusOnly.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (20,'Sequest','FinniganDefSettings_Add4Plus.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (21,'Sequest','FinniganDefSettings_Add4_5Plus.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (22,'Sequest','FinniganDefSettings_Create1,2,3,4,5Plus.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (23,'Sequest','FinniganDefSettings_Create1,2,3,4Plus.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (24,'Sequest','FinniganDefSettings_DAC_Test.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (25,'Sequest','FinniganDefSettings_DeconMSN.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (26,'Sequest','FinniganDefSettings_MS3Only.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (27,'Sequest','FinniganDefSettings_MS3Only_100Scans.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (28,'Sequest','FinniganDefSettings_PhosphoNeutralLoss.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (29,'Sequest','FinniganDefSettings_Yufeng01.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (30,'Sequest','LCQDefSettings.txt','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (31,'XTandem','IonTrapDefSettings.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (32,'XTandem','IonTrapDefSettings_DAC_Short.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (33,'XTandem','IonTrapDefSettings_DeconMSN.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (34,'XTandem','IonTrapDefSettings_MEM_Short_PhosphoNeutralLoss.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (35,'XTandem','IonTrapDefSettings_PhosphoNeutralLoss.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (36,'XTandem','SWTestSettingsFile.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (37,'XTandem','SWTestSettingsFileAllScans.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (38,'Sequest','FinniganDefSettings_NoGrouping.xml','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active) VALUES (39,'Sequest','FinniganDefSettings_NoGrouping_StartScan5.xml','',1)
SET IDENTITY_INSERT [T_Settings_Files] OFF
