/****** Object:  Table [T_Secondary_Sep] ******/
/****** RowCount: 27 ******/
/****** Columns: SS_name, SS_ID, SS_comment, SS_active ******/
INSERT INTO [T_Secondary_Sep] VALUES ('none',1,'',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-ISCO-Standard',2,'Standard solvents (TFA), 100 to 180 minute separation',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-Agilent',3,'',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-ISCO-Special',4,'',1)
INSERT INTO [T_Secondary_Sep] VALUES ('CIEF',5,'',1)
INSERT INTO [T_Secondary_Sep] VALUES ('CE',6,'',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-ORNL-Standard',7,'',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-Agilent-Special',8,'',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-FHCRC-Standard',9,'',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-Broad-Standard',10,'',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-ISCO-Formic_35minute',11,'Formic acid solvent, 35 minute separation',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-ISCO-Formic_15minute',12,'Formic acid solvent, 15 minute separation',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-ISCO-Standard_15minute',13,'Standard solvents (TFA), 15 minute separation',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-ISCO-Metabolomics_WaterSoluble',14,'',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-ISCO-Metabolomics_LipidSoluble',15,'',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-ISCO-Standard_35minute',16,'Standard solvents (TFA), 35 minute separation (50 or 75 um column)',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-ISCO-Standard_50minute',17,'Standard solvents (TFA), 50 minute separation (150 um column)',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-ISCO-Formic_100minute',18,'Formic acid solvent, 100 minute separation',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-ISCO-Phospho',19,'General setting for Phospho cart work',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-ISCO-Formic_80minute',20,'Formic acid solvent, 80 minute separation',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-KoreaU-Standard',21,'',1)
INSERT INTO [T_Secondary_Sep] VALUES ('GC-Agilent-Fiehn',22,'Agilent GC Fiehn',1)
INSERT INTO [T_Secondary_Sep] VALUES ('GC-Agilent-Special',23,'Agilent GC special',1)
INSERT INTO [T_Secondary_Sep] VALUES ('RPLC_HILIC',24,'Online 2D separation using RPLC then HILIC',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-Agilent-Formic_100minute',25,'Agilent constant flow, 100 minute separation',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-Agilent-Formic_30minute',26,'Agilent constant flow, 30 minute separation',1)
INSERT INTO [T_Secondary_Sep] VALUES ('LC-Agilent-Formic_15minute',27,'Agilent constant flow, 15 minute separation',1)
