/****** Object:  Table [T_Settings_Files] ******/
/****** RowCount: 42 ******/
SET IDENTITY_INSERT [T_Settings_Files] ON
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (1,'AgilentTOFPek','AgTofDefSettings.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (5,'ICR2LS','BrukerTICBaseSettings.txt','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (6,'ICR2LS','FTICRDefSettings.txt','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (7,'ICR2LS','TIC_ICR_DefSettings.txt','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (8,'LTQ_FTPek','LTQ_FTDefSettings.txt','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (9,'LTQ_FTPek','LTQ_FT_100Scans.txt','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (10,'MLynxPek','MMTofDefSettings.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (11,'QTOFPek','QTOFPekDefSettings.txt','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (12,'Sequest','30scans.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (13,'Sequest','30scans_ExtractMsn_Test.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (14,'Sequest','Agilent30scans.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (15,'Sequest','AgilentDefSettings.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (16,'Sequest','AgilentDefSettings_Create1,2,3,4Plus.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (17,'Sequest','First_100_scans.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (18,'Sequest','FinniganDefSettings.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (19,'Sequest','FinniganDefSettings_4_5PlusOnly.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (20,'Sequest','FinniganDefSettings_Add4Plus.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (21,'Sequest','FinniganDefSettings_Add4_5Plus.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (22,'Sequest','FinniganDefSettings_Create1,2,3,4,5Plus.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (23,'Sequest','FinniganDefSettings_Create1,2,3,4Plus.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (24,'Sequest','FinniganDefSettings_DAC_Test.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (25,'Sequest','FinniganDefSettings_DeconMSN.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (26,'Sequest','FinniganDefSettings_MS3Only.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (27,'Sequest','FinniganDefSettings_MS3Only_100Scans.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (28,'Sequest','FinniganDefSettings_PhosphoNeutralLoss.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (29,'Sequest','FinniganDefSettings_20000UpperMH.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (30,'Sequest','LCQDefSettings.txt','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (31,'XTandem','IonTrapDefSettings.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (32,'XTandem','IonTrapDefSettings_DAC_Short.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (33,'XTandem','IonTrapDefSettings_DeconMSN.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (34,'XTandem','IonTrapDefSettings_MEM_Short_PhosphoNeutralLoss.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (35,'XTandem','IonTrapDefSettings_PhosphoNeutralLoss.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (36,'XTandem','SWTestSettingsFile.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (37,'XTandem','SWTestSettingsFileAllScans.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (38,'Sequest','FinniganDefSettings_NoGrouping.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (39,'Sequest','FinniganDefSettings_NoGrouping_StartScan5.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (40,'Sequest','FinniganDefSettings_Add4to6Plus_NoGrouping.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (43,'XTandem','IonTrapDefSettings_Add4to6Plus_NoGrouping.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (44,'Sequest','FinniganDefSettings_Add4Plus_NoGrouping.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (45,'XTandem','FinniganDefSettings_Add4Plus_NoGrouping.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (51,'Sequest','FinniganDefSettings_Scans10000-11000.xml','',1,'','')
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents) VALUES (52,'XTandem','FinniganDefSettings_Scans10000-11000.xml','',1,'','')
SET IDENTITY_INSERT [T_Settings_Files] OFF
