/****** Object:  Table [T_Settings_Files] ******/
/****** RowCount: 49 ******/
SET IDENTITY_INSERT [T_Settings_Files] ON
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (1,'AgilentTOFPek','AgTofDefSettings.xml','',1,'','',279)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (5,'ICR2LS','BrukerTICBaseSettings.txt','',1,'','',10283)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (6,'ICR2LS','FTICRDefSettings.txt','',1,'','',13476)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (7,'ICR2LS','TIC_ICR_DefSettings.txt','',1,'','',0)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (8,'LTQ_FTPek','LTQ_FTDefSettings.txt','',1,'','',8673)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (9,'LTQ_FTPek','LTQ_FT_100Scans.txt','',1,'','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (10,'MLynxPek','MMTofDefSettings.xml','',1,'','',602)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (11,'QTOFPek','QTOFPekDefSettings.txt','',1,'','',172)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (12,'Sequest','30scans.xml','',1,'','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (13,'Sequest','30scans_ExtractMsn_Test.xml','',1,'','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (14,'Sequest','Agilent30scans.xml','',1,'','',0)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (15,'Sequest','AgilentDefSettings.xml','',1,'','',604)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (16,'Sequest','AgilentDefSettings_Create1,2,3,4Plus.xml','',1,'','',0)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (17,'Sequest','First_100_scans.xml','',1,'','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (18,'Sequest','FinniganDefSettings.xml','',1,'','',39843)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (19,'Sequest','FinniganDefSettings_4_5PlusOnly.xml','',1,'','',42)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (20,'Sequest','FinniganDefSettings_Add4Plus.xml','',1,'','',74)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (21,'Sequest','FinniganDefSettings_Add4_5Plus.xml','',1,'','',48)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (22,'Sequest','FinniganDefSettings_Create1,2,3,4,5Plus.xml','',1,'','',0)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (23,'Sequest','FinniganDefSettings_Create1,2,3,4Plus.xml','',1,'','',0)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (24,'Sequest','FinniganDefSettings_DAC_Test.xml','',1,'','',0)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (25,'Sequest','FinniganDefSettings_DeconMSN.xml','',1,'','',3656)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (26,'Sequest','FinniganDefSettings_MS3Only.xml','',1,'','',116)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (27,'Sequest','FinniganDefSettings_MS3Only_100Scans.xml','',1,'','',0)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (28,'Sequest','FinniganDefSettings_PhosphoNeutralLoss.xml','',1,'','',43)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (29,'Sequest','FinniganDefSettings_20000UpperMH.xml','',1,'','',21)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (30,'Sequest','LCQDefSettings.txt','',1,'','',101857)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (31,'XTandem','IonTrapDefSettings.xml','',1,'','',25833)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (32,'XTandem','IonTrapDefSettings_DAC_Short.xml','',1,'','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (33,'XTandem','IonTrapDefSettings_DeconMSN.xml','',1,'','',1745)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (34,'XTandem','IonTrapDefSettings_MEM_Short_PhosphoNeutralLoss.xml','',1,'','',0)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (35,'XTandem','IonTrapDefSettings_PhosphoNeutralLoss.xml','',1,'','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (36,'XTandem','SWTestSettingsFile.xml','',1,'','',21)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (37,'XTandem','SWTestSettingsFileAllScans.xml','',1,'','',0)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (38,'Sequest','FinniganDefSettings_NoGrouping.xml','',1,'','',27)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (39,'Sequest','FinniganDefSettings_NoGrouping_StartScan5.xml','',1,'','',2)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (40,'Sequest','FinniganDefSettings_Add4to6Plus_NoGrouping.xml','',1,'','',130)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (43,'XTandem','IonTrapDefSettings_Add4to6Plus_NoGrouping.xml','',1,'','',29)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (44,'Sequest','FinniganDefSettings_Add4Plus_NoGrouping.xml','',1,'','',97)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (45,'XTandem','FinniganDefSettings_Add4Plus_NoGrouping.xml','',1,'','',97)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (51,'Sequest','FinniganDefSettings_Scans10000-11000.xml','',1,'','',2)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (52,'XTandem','FinniganDefSettings_Scans10000-11000.xml','',1,'','',2)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (53,'Inspect','Inspect_IonTrap_2000Scans.xml','Scans 5000 to 7000',1,'','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (54,'Inspect','Inspect_IonTrap_200Scans.xml','Scans 5000 to 5200',1,'','',0)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (55,'Inspect','Inspect_IonTrap_500Scans.xml','Scans 5000 to 5500',1,'','',1)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (56,'Inspect','Inspect_IonTrapDefSettings.xml','Default',1,'','',91)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (57,'Inspect','Inspect_IonTrap_500Scans_Start17000.xml','Scans 17000 to 17500',1,'','',0)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (58,'Inspect','Inspect_IonTrap_100Scans_Start17000.xml','Scans 17000 to 17100',1,'','',0)
INSERT INTO [T_Settings_Files] (ID, Analysis_Tool, File_Name, Description, Active, Last_Updated, Contents, Job_Usage_Count) VALUES (59,'Sequest','FinniganDefSettings_25000UpperMH.xml','Expanded mass range for USTags work',1,'','',24)
SET IDENTITY_INSERT [T_Settings_Files] OFF
