/****** Object:  Table [t_storage_path_bkup] ******/
/****** RowCount: 132 ******/
/****** Columns: SP_path_ID, SP_path, SP_vol_name_client, SP_vol_name_server, SP_function, SP_instrument_name, SP_code, SP_descripton ******/
INSERT INTO [t_storage_path_bkup] VALUES (2,'(none)','','','','','','(path not assigned)')
INSERT INTO [t_storage_path_bkup] VALUES (199,'IMS_SCIEX_TOF1_DMS1\','\\Proto-9\','H:\','raw-storage','IMS_SCIEX_TOF','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (4,'LCQ_C2_Xfer\','','\\WD37461\','inbox','LCQ_C2','','[DAC] New computer 2-9-2006')
INSERT INTO [t_storage_path_bkup] VALUES (200,'Shared\','(na)','\\WD37289.bionet\','inbox','IMS_SCIEX_TOF','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (6,'LCQ_C1_Xfer\','','\\WD37452.bionet\','inbox','LCQ_C1','','')
INSERT INTO [t_storage_path_bkup] VALUES (96,'DMS_Xfer\','(na)','\\QTOF2.bionet\','inbox','QTOF_MM1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (8,'auto-put\','','\\ftmsvbnw.bionet\','inbox','7T_FTICR','','Moved to Samba 7-16-2004')
INSERT INTO [t_storage_path_bkup] VALUES (201,'IMS_BIOSPECT_TOF1_DMS1\','\\proto-9\','H:\','raw-storage','IMS_BIOSPECT_TOF','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (10,'/usr/share/ftms/tmpdata;/data;/auto-put;/data/auto-put','','ftmscbnw.emsl.pnl.gov','inbox','11T_FTICR','','')
INSERT INTO [t_storage_path_bkup] VALUES (205,'LTQ_Orb2_DMS1\','\\proto-9\','G:\','raw-storage','LTQ_Orb_2','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (12,'/usr/share/ftms/tmpdata;/data1;/data2','','ftmsabnw.emsl.pnl.gov','inbox','3T_FTICR','','')
INSERT INTO [t_storage_path_bkup] VALUES (99,'DMS_Xfer\','(na)','\\Chemstation10\','inbox','Agilent_XCT1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (206,'LTQ_Orbi2_Xfer\','(na)','\\wd55759.bionet\','inbox','LTQ_Orb_2','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (16,'SW_Test_LCQ_Xfer\','','\\PrismDevII\','inbox','SW_TEST_LCQ','','')
INSERT INTO [t_storage_path_bkup] VALUES (207,'LTQ_1_DMS4\','\\Proto-7\','G:\','raw-storage','LTQ_1','','New location 10-25-2006')
INSERT INTO [t_storage_path_bkup] VALUES (18,'auto-put\SW_Test_FTICR\','','\\ftmsvbnw.bionet\','inbox','SW_TEST_FTICR','','')
INSERT INTO [t_storage_path_bkup] VALUES (209,'LTQ_3_DMS4\','\\Proto-7\','G:\','raw-storage','LTQ_3','','New location 10-25-2006')
INSERT INTO [t_storage_path_bkup] VALUES (210,'LTQ_4_DMS4\','\\Proto-7\','G:\','raw-storage','LTQ_4','','New location 10-25-2006')
INSERT INTO [t_storage_path_bkup] VALUES (211,'LTQ_FT1_DMS3\','\\Proto-7\','G:\','raw-storage','LTQ_FT1','','New location 10-25-2006')
INSERT INTO [t_storage_path_bkup] VALUES (212,'TSQ_1_DMS1\','\\proto-9\','G:\','raw-storage','TSQ_1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (213,'TSQ_1_Xfer\','(na)','\\R106016.bionet\','inbox','TSQ_1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (32,'11T_DMS2\','\\proto-3\','G:\','old-storage','11T_FTICR','','Moved to Proto-3 07-01-03')
INSERT INTO [t_storage_path_bkup] VALUES (214,'9T_DMS_TMP\','\\Proto-9\','H:\','old-storage','9T_FTICR','','Temp storage while Proto-4 array out of service')
INSERT INTO [t_storage_path_bkup] VALUES (34,'3T_DMS1\','\\Proto-3\','G:\','raw-storage','3T_FTICR','','Moved to Proto-3 06-30-03')
INSERT INTO [t_storage_path_bkup] VALUES (105,'11T_DMS9\','\\Proto-5\','D:\','raw-storage','11T_FTICR_B','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (215,'SWT_LCQ3\','\\Proto-3\','G:\','old-storage','SW_TEST_LCQ','','Software test storage area')
INSERT INTO [t_storage_path_bkup] VALUES (37,'LCQ_D1_XFER\','','\\WD37185.bionet\','inbox','LCQ_D1','','Computer change 2-4-2004;Computer change 4-3-2006;Computer change 5-25-2006;Computer change 7-17-2007')
INSERT INTO [t_storage_path_bkup] VALUES (216,'LTQ_Orb3_DMS1\','\\proto-9\','G:\','raw-storage','LTQ_orb_3','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (108,'LTQ_1_xfer\','(na)','\\wd45279.bionet\','inbox','LTQ_1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (40,'LCQ_D2_XFER\','(na)','\\WD30918.bionet\','inbox','LCQ_D2','(na)','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (42,'QSTAR_Xfer\','(na)','\\Wd37289\','inbox','QTOF_1322','(na)','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (44,'LCQ_XP1_Xfer\','(na)','\\N830442.bionet\','inbox','LCQ_XP1','(na)','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (51,'LCQ_XP2_Xfer\','(na)','\\WD40090.bionet\','inbox','LCQ_XP2','(na)','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (56,'LCQ_C3_Xfer\','(na)','\\WV04886.bionet\','inbox','LCQ_C3','(na)','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (217,'LTQ_Orb3_Xfer\','(na)','\\R104164.bionet\','inbox','LTQ_orb_3','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (113,'QC_Ag_XCT\','\\Proto-4\','G:\','raw-storage','QC_Ag_XCT','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (218,'Broad_ORB1_Xfer\','(na)','\\Proto-5\','inbox','Broad_Orb1','','Dataset transfer folder for virtual Broad Orbitrap')
INSERT INTO [t_storage_path_bkup] VALUES (46,'LCMS_Data_Storage\','(na)','\\we10857.bionet\','inbox','9T_FTICR','(na)','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (219,'Broad_Orb1_DMS1\','\\Proto-9\','G:\','raw-storage','Broad_Orb1','','Storage for Broad Orbitrap virtual instrument')
INSERT INTO [t_storage_path_bkup] VALUES (110,'QC_LCQ_Xfer\','(na)','\\PrismDevII\','inbox','QC_LCQ','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (220,'LTQ_ETD1_DMS1\','\\proto-9\','H:\','raw-storage','LTQ_ETD_1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (114,'QC_Ag_XCT_Xfer\','(na)','\\PrismDevII\','inbox','QC_Ag_XCT','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (221,'LTQ_ETD1_xfer\','(na)','\\WD54753.bionet\','inbox','LTQ_ETD_1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (116,'QC_Ag_TOF_Xfer\','(na)','\\PrismDevII\','inbox','QC_Ag_TOF','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (117,'QC_MM_TOF\','\\Proto-4\','G:\','raw-storage','QC_MM_TOF','','New array 3-7-06)')
INSERT INTO [t_storage_path_bkup] VALUES (118,'QC_MM_TOF_Xfer\','(na)','\\PrismDevII\','inbox','QC_MM_TOF','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (59,'9T_DMS6\','\\proto-4\','H:\','old-storage','9T_FTICR','','Moved to Proto-4 7-23-2003. New array 3-2-2006')
INSERT INTO [t_storage_path_bkup] VALUES (120,'QC_LTQ_Xfer\','(na)','\\PrismDevII\','inbox','QC_LTQ','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (64,'9T_DMS7\','\\proto-4\','H:\','old-storage','9T_FTICR','','Moved to Proto-4 7-23-2003. New array 3-2-2006')
INSERT INTO [t_storage_path_bkup] VALUES (121,'QC_Fin_ICR\','\\Proto-3\','G:\','raw-storage','QC_Fin_ICR','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (122,'QC_Fin_ICR_Xfer\','(na)','\\PrismDevII\','inbox','QC_Fin_ICR','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (123,'Agilent_SL1_DMS2\','\\Proto-6\','F:\','raw-storage','Agilent_SL1','','New storage server 9/20/2004')
INSERT INTO [t_storage_path_bkup] VALUES (124,'Agilent_TOF1_DMS2\','\\Proto-6\','F:\','raw-storage','Agilent_TOF1','','New storage server 9/20/2004')
INSERT INTO [t_storage_path_bkup] VALUES (125,'Agilent_XCT1_DMS2\','\\Proto-6\','F:\','raw-storage','Agilent_XCT1','','New storage server 9/20/2004')
INSERT INTO [t_storage_path_bkup] VALUES (126,'C1_DMS2\','\\proto-6\','F:\','raw-storage','LCQ_C1','','New storage server 9/20/2004')
INSERT INTO [t_storage_path_bkup] VALUES (127,'C2_DMS2\','\\Proto-6\','F:\','raw-storage','LCQ_C2','','New storage server 9/20/2004')
INSERT INTO [t_storage_path_bkup] VALUES (128,'C3_DMS2\','\\Proto-6\','F:\','raw-storage','LCQ_C3','','New storage server 9/20/2004')
INSERT INTO [t_storage_path_bkup] VALUES (136,'LCQ_JA_GTL_DMS1\','\\Proto-6\','F:\','raw-storage','LCQ_JA_GTL','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (137,'GTL_XFER\','(na)','\\WD37512\','inbox','LCQ_JA_GTL','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (138,'LTQ_FT1_DMS1\','\\Proto-6\','G:\','old-storage','LTQ_FT1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (139,'FT1_Xfer\','(na)','\\LTQ3QFVL41.bionet\','inbox','LTQ_FT1','','Added bionet qualifier 6-27-06')
INSERT INTO [t_storage_path_bkup] VALUES (140,'LTQ_2_DMS2\','\\Proto-6\','G:\','old-storage','LTQ_2','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (141,'LTQ_2_Xfer\','(na)','\\LTQ_2.bionet\','inbox','LTQ_2','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (87,'SW_Test_9T_Xfer\','(na)','\\PrismDevII\','inbox','SW_Test_Bruker','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (144,'11T_Aux2\','\\Proto-5\','D:\','raw-storage','11T_Aux2','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (145,'11T_Aux2_Data\','(na)','\\ftms11taux2\','inbox','11T_Aux2','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (150,'Agilent_TOF2_DMS2\','\\Proto-6\','F:\','raw-storage','Agilent_TOF2','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (151,'DMS_Xfer\','(na)','\\chemstation01.bionet\','inbox','Agilent_TOF2','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (152,'LTQ_FB1_DMS1\','\\Proto-8\','G:\','raw-storage','LTQ_FB1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (153,'DMS_Xfer\','(na)','\\LTQ10440\','inbox','LTQ_FB1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (88,'11T_DMS8\','\\Proto-3\','G:\','raw-storage','11T_FTICR','','Moved to new server 05-01-03')
INSERT INTO [t_storage_path_bkup] VALUES (89,'7T_DMS8\','\\Proto-3\','G:\','raw-storage','7T_FTICR','','Moved to new server 05-01-03')
INSERT INTO [t_storage_path_bkup] VALUES (198,'12T_DMS2\','\\Proto-7\','G:\','raw-storage','12T_FTICR','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (94,'DMS_Xfer\','(na)','\\chemstation1326\','inbox','Agilent_SL1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (101,'DMS_Xfer\','(na)','\\Chemstation03\','inbox','Agilent_TOF1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (106,'11t_temp_ds\','(na)','\\FTMS11T.bionet\','inbox','11T_FTICR_B','','Path changer per Queue Request #185')
INSERT INTO [t_storage_path_bkup] VALUES (112,'QC_Bruker_ICR_Xfer\','(na)','\\PrismDevII\','inbox','QC_Bruker_ICR','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (129,'LTQ_1_DMS2\','\\Proto-6\','G:\','old-storage','LTQ_1','','New storage server 9/20/2004')
INSERT INTO [t_storage_path_bkup] VALUES (142,'LTQ_3_DMS2\','\\Proto-6\','G:\','old-storage','LTQ_3','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (143,'LTQ_3_Xfer\','(na)','\\LTQ_3\','inbox','LTQ_3','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (146,'12T_DMS1\','\\Proto-7\','F:\','old-storage','12T_FTICR','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (147,'12T_FTICR_data\','(na)','\\pnnl2\','inbox','12T_FTICR','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (202,'Shared\','(na)','\\botof201a.bionet\','inbox','IMS_BIOSPECT_TOF','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (155,'LTQ_4_DMS1\','\\Proto-6\','G:\','old-storage','LTQ_4','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (156,'LTQ_4_xfer\','(na)','\\wd41441.bionet\','inbox','LTQ_4','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (158,'QC_LTQ_FT_Xfer\','(na)','\\PrismdevII\','inbox','QC_LTQ_FT','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (159,'LTQ_1_DMS3\','\\Proto-7\','F:\','old-storage','LTQ_1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (160,'LTQ_2_DMS3\','\\Proto-7\','F:\','old-storage','LTQ_2','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (161,'LTQ_3_DMS3\','\\Proto-7\','F:\','old-storage','LTQ_3','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (162,'LTQ_4_DMS3\','\\Proto-7\','F:\','old-storage','LTQ_4','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (163,'LTQ_FT1_DMS2\','\\Proto-7\','F:\','old-storage','LTQ_FT1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (165,'SW_Test_Orbitrap_Xfer\','(na)','\\prismdevii\','inbox','QC_LTQ_Orbitrap','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (166,'FHCRC_LTQ1_DMS1\','\\proto-7\','F:\','raw-storage','FHCRC_LTQ1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (167,'FHCRC_LTQ1_Xfer\','(na)','\\prismdevii\','inbox','FHCRC_LTQ1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (168,'LTQ_RITE_DMS1\','\\proto-7\','G:\','raw-storage','LTQ_RITE','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (169,'LTQ_RITE_Xfer\','(na)','\\prismdevii\','inbox','LTQ_RITE','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (171,'LTQ_Orbi1_Xfer\','(na)','\\LTQ10726\','inbox','LTQ_Orb_1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (172,'LTQ_Orb1_DMS2\','\\proto-9\','G:\','raw-storage','LTQ_Orb_1','','New server 3/1/2006')
INSERT INTO [t_storage_path_bkup] VALUES (173,'9T_Q_DMS3\','\\Proto-4\','H:\','raw-storage','9T_FTICR_Q','','New array 3-2-06')
INSERT INTO [t_storage_path_bkup] VALUES (174,'9T_DMS1\','\\proto-4\','H:\','raw-storage','9T_FTICR','','New array 3-2-06')
INSERT INTO [t_storage_path_bkup] VALUES (175,'QC_Bruker_ICR\','\\Proto-4\','H:\','raw-storage','QC_Bruker_ICR','','New array 3-2-06')
INSERT INTO [t_storage_path_bkup] VALUES (177,'SWT_ICR2\','\\Proto-4\','H:\','raw-storage','SW_Test_Bruker','','New array 3-2-06')
INSERT INTO [t_storage_path_bkup] VALUES (182,'C1_DMS1\','\\proto-4\','G:\','old-storage','LCQ_C1','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (183,'C2_DMS1\','\\proto-4\','G:\','old-storage','LCQ_C2','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (186,'D2_DMS1\','\\proto-4\','G:\','old-storage','LCQ_D2','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (187,'LTQ_1_DMS1\','\\Proto-4\','G:\','old-storage','LTQ_1','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (188,'QC_Ag_TOF\','\\Proto-4\','G:\','raw-storage','QC_Ag_TOF','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (191,'QC_LTQ_FT\','\\proto-4\','G:\','raw-storage','QC_LTQ_FT','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (193,'QT1_DMS2\','\\proto-4\','G:\','old-storage','QTOF_1322','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (194,'QTMM1_DMS3\','\\Proto-4\','G:\','old-storage','QTOF_MM1','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (195,'SWT_LCQ2\','\\proto-4\','G:\','raw-storage','SW_TEST_LCQ','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (196,'XP1_DMS1\','\\proto-4\','G:\','old-storage','LCQ_XP1','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (197,'XP2_DMS3\','\\proto-4\','G:\','old-storage','LCQ_XP2','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (208,'LTQ_2_DMS4\','\\Proto-7\','G:\','raw-storage','LTQ_2','','New location 10-25-2006')
INSERT INTO [t_storage_path_bkup] VALUES (103,'LC_FTICR_data\','(na)','\\pnnl2\','inbox','9T_FTICR_Q','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (130,'D1_DMS2\','\\proto-6\','F:\','raw-storage','LCQ_D1','','New storage server 9/20/2004')
INSERT INTO [t_storage_path_bkup] VALUES (131,'D2_DMS2\','\\proto-6\','F:\','raw-storage','LCQ_D2','','New storage server 9/20/2004')
INSERT INTO [t_storage_path_bkup] VALUES (132,'XP1_DMS2\','\\proto-6\','F:\','raw-storage','LCQ_XP1','','New storage server 9/20/2004')
INSERT INTO [t_storage_path_bkup] VALUES (133,'XP2_DMS2\','\\proto-6\','F:\','raw-storage','LCQ_XP2','','New storage server 9/20/2004')
INSERT INTO [t_storage_path_bkup] VALUES (134,'QT1_DMS1\','\\proto-6\','F:\','raw-storage','QTOF_1322','','New storage server 9/20/2004')
INSERT INTO [t_storage_path_bkup] VALUES (135,'QTMM1_DMS2\','\\Proto-6\','F:\','raw-storage','QTOF_MM1','','New storage server 9/20/2004')
INSERT INTO [t_storage_path_bkup] VALUES (184,'C3_DMS1\','\\Proto-4\','G:\','old-storage','LCQ_C3','','New array 3-6-06')
INSERT INTO [t_storage_path_bkup] VALUES (192,'QC_LTQ_Orbitrap_DMS1\','\\proto-4\','G:\','raw-storage','QC_LTQ_Orbitrap','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (176,'SWT_ICR2\','\\proto-4\','H:\','raw-storage','SW_TEST_FTICR','','New array 3-2-06')
INSERT INTO [t_storage_path_bkup] VALUES (178,'9T_DMS8\','\\proto-4\','H:\','old-storage','9T_FTICR','','New array 03-02-06')
INSERT INTO [t_storage_path_bkup] VALUES (179,'Agilent_SL1_DMS1\','\\Proto-4\','G:\','old-storage','Agilent_SL1','','Moved from Proto-2 on 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (180,'Agilent_XCT1_DMS1\','\\Proto-4\','G:\','old-storage','Agilent_XCT1','','Moved from Proto-2 on 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (185,'D1_DMS1\','\\proto-4\','G:\','old-storage','LCQ_D1','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (189,'QC_LCQ\','\\Proto-4\','G:\','raw-storage','QC_LCQ','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (203,'IMS_AGILENT_TOF1_DMS1\','\\proto-9\','H:\','raw-storage','IMS_AGILENT_TOF1','','(na)')
INSERT INTO [t_storage_path_bkup] VALUES (190,'QC_LTQ\','\\Proto-4\','G:\','raw-storage','QC_LTQ','','New array 3-7-06')
INSERT INTO [t_storage_path_bkup] VALUES (204,'Shared\','(na)','\\TOFSYS01.bionet\','inbox','IMS_AGILENT_TOF1','','(na)')
