/****** Object:  Table [T_Task_State_Name] ******/
/****** RowCount: 18 ******/
/****** Columns: ID, Name ******/
INSERT INTO [T_Task_State_Name] VALUES (0,'(none)')
INSERT INTO [T_Task_State_Name] VALUES (1,'New')
INSERT INTO [T_Task_State_Name] VALUES (2,'In Progress')
INSERT INTO [T_Task_State_Name] VALUES (3,'Complete')
INSERT INTO [T_Task_State_Name] VALUES (4,'Inactive')
INSERT INTO [T_Task_State_Name] VALUES (5,'Failed')
INSERT INTO [T_Task_State_Name] VALUES (6,'Received')
INSERT INTO [T_Task_State_Name] VALUES (7,'Prep. In Progress')
INSERT INTO [T_Task_State_Name] VALUES (8,'Preparation Failed')
INSERT INTO [T_Task_State_Name] VALUES (9,'Not Ready')
INSERT INTO [T_Task_State_Name] VALUES (10,'Restore Required')
INSERT INTO [T_Task_State_Name] VALUES (11,'Restore In Progress')
INSERT INTO [T_Task_State_Name] VALUES (12,'Restore Failed')
INSERT INTO [T_Task_State_Name] VALUES (14,'Failed, Ignore Job Step States')
INSERT INTO [T_Task_State_Name] VALUES (15,'Skipped')
INSERT INTO [T_Task_State_Name] VALUES (20,'Resuming')
INSERT INTO [T_Task_State_Name] VALUES (100,'Hold')
INSERT INTO [T_Task_State_Name] VALUES (101,'Ignore')
