/****** Object:  Database [DMS_Data_Package] ******/
CREATE DATABASE [DMS_Data_Package] ON  PRIMARY 
( NAME = N'DMS_Data_Package', FILENAME = N'I:\SQLServerData\DMS_Data_Package.mdf' , SIZE = 402624KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DMS_Data_Package_log', FILENAME = N'G:\SQLServerData\DMS_Data_Package_log.ldf' , SIZE = 2304KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DMS_Data_Package] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DMS_Data_Package].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [DMS_Data_Package] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [DMS_Data_Package] SET ANSI_NULLS ON 
GO
ALTER DATABASE [DMS_Data_Package] SET ANSI_PADDING ON 
GO
ALTER DATABASE [DMS_Data_Package] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [DMS_Data_Package] SET ARITHABORT ON 
GO
ALTER DATABASE [DMS_Data_Package] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DMS_Data_Package] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [DMS_Data_Package] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DMS_Data_Package] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DMS_Data_Package] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DMS_Data_Package] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DMS_Data_Package] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [DMS_Data_Package] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DMS_Data_Package] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [DMS_Data_Package] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DMS_Data_Package] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DMS_Data_Package] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DMS_Data_Package] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DMS_Data_Package] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DMS_Data_Package] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DMS_Data_Package] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DMS_Data_Package] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DMS_Data_Package] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DMS_Data_Package] SET  READ_WRITE 
GO
ALTER DATABASE [DMS_Data_Package] SET RECOVERY FULL 
GO
ALTER DATABASE [DMS_Data_Package] SET  MULTI_USER 
GO
ALTER DATABASE [DMS_Data_Package] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DMS_Data_Package] SET DB_CHAINING OFF 
GO
GRANT CONNECT TO [d3l243] AS [dbo]
GO
GRANT CONNECT TO [d3p214] AS [dbo]
GO
GRANT CONNECT TO [DMSReader] AS [dbo]
GO
GRANT SHOWPLAN TO [DMSReader] AS [dbo]
GO
GRANT CONNECT TO [DMSWebUser] AS [dbo]
GO
GRANT SHOWPLAN TO [DMSWebUser] AS [dbo]
GO
GRANT SHOWPLAN TO [PNL\D3M578] AS [dbo]
GO
GRANT SHOWPLAN TO [PNL\D3M580] AS [dbo]
GO
GRANT CONNECT TO [RBAC-Analysis_Job_Runner] AS [dbo]
GO
GRANT CONNECT TO [RBAC-DMS_Guest] AS [dbo]
GO
GRANT CONNECT TO [RBAC-DMS_User] AS [dbo]
GO
GRANT CONNECT TO [RBAC-Web_Analysis] AS [dbo]
GO
GRANT CONNECT TO [svc-dms] AS [dbo]
GO
