/****** Object:  Table [T_Instrument_Group_Allowed_DS_Type] ******/
/****** RowCount: 77 ******/
/****** Columns: IN_Group, Dataset_Type, Comment ******/
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('11T','HMS','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('11T','HMS-HMSn','Rarely used')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_GC-MS','GC-MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_GC-MS','GC-SIM','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_Ion_Trap','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_Ion_Trap','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_TOF','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_TOF_V2','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_TOF_V2','HMS-HMSn','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_Amazon_Ion_Trap','MS-CID/ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_Amazon_Ion_Trap','MS-ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_Amazon_Ion_Trap','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_FTMS','HMS','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_FTMS','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_QTOF','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_QTOF','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('DataFolders','DataFiles','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Exactive','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('FT_ZippedSFolders','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('GC-TSQ','GC-MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('GC-TSQ','MRM','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('IMS','IMS-HMS','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('IMS','IMS-MSn-HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LCQ','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LCQ','MS-MSn','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ','MS-MSn','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-ETD','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-ETD','MS-CID/ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-ETD','MS-ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-ETD','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-FT','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-FT','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-FT','HMS-MSn','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-FT','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('MALDI-Imaging','MALDI-HMS','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('MALDI-TOF','MALDI-HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Micromass_TOF','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Micromass_TOF','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap','HMS-MSn','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap-HCD','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap-HCD','HMS-HCD-CID-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap-HCD','HMS-HCD-CID-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap-HCD','HMS-HCD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap-HCD','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap-HCD','HMS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap-HCD','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Other','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Other','HMS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Other','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Other','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('QTrap','MRM','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('QTrap','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('QTrap','MS-MSn','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('TSQ','MRM','Use for MRM')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('TSQ','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('TSQ','MS-MSn','Use for MSn')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-CID/ETD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-CID/ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-ETD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HCD-CID-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HCD-CID-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HCD-CID/ETD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HCD-CID/ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HCD-ETD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HCD-ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HCD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-PQD-CID/ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-PQD-ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','MS-MSn','')
