/****** Object:  Table [T_Notification_Entity_User] ******/
/****** RowCount: 16 ******/
/****** Columns: User_ID, Entity_Type_ID ******/
INSERT INTO [T_Notification_Entity_User] VALUES (17,1)
INSERT INTO [T_Notification_Entity_User] VALUES (17,2)
INSERT INTO [T_Notification_Entity_User] VALUES (17,3)
INSERT INTO [T_Notification_Entity_User] VALUES (17,4)
INSERT INTO [T_Notification_Entity_User] VALUES (2086,1)
INSERT INTO [T_Notification_Entity_User] VALUES (2086,2)
INSERT INTO [T_Notification_Entity_User] VALUES (2086,3)
INSERT INTO [T_Notification_Entity_User] VALUES (2086,4)
INSERT INTO [T_Notification_Entity_User] VALUES (2123,1)
INSERT INTO [T_Notification_Entity_User] VALUES (2123,2)
INSERT INTO [T_Notification_Entity_User] VALUES (2123,3)
INSERT INTO [T_Notification_Entity_User] VALUES (2123,4)
INSERT INTO [T_Notification_Entity_User] VALUES (2217,1)
INSERT INTO [T_Notification_Entity_User] VALUES (2217,2)
INSERT INTO [T_Notification_Entity_User] VALUES (2217,4)
INSERT INTO [T_Notification_Entity_User] VALUES (2271,4)
