/****** Object:  Database [DMSHistoricLogPipeline] ******/
CREATE DATABASE [DMSHistoricLogPipeline] ON  PRIMARY 
( NAME = N'DMSHistLogPipeline_dat', FILENAME = N'H:\SQLServerData\DMSHistoricLogPipeline.mdf' , SIZE = 14736640KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'DMSHistLogPipeline_log', FILENAME = N'E:\SQLServerData\DMSHistoricLogPipeline_log.ldf' , SIZE = 13888KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DMSHistoricLogPipeline].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET ANSI_NULLS ON 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET ANSI_PADDING ON 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET ARITHABORT ON 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET  READ_WRITE 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET  MULTI_USER 
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DMSHistoricLogPipeline] SET DB_CHAINING OFF 
GO
