/****** Object:  Database [DMSHistoricLog1] ******/
CREATE DATABASE [DMSHistoricLog1] ON  PRIMARY 
( NAME = N'DMSHistLog1_dat', FILENAME = N'C:\SQLServerData\DMSHistLog1_data.mdf' , SIZE = 14736640KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'DMSHistLog1_log', FILENAME = N'H:\SQLServerData\DMSHistLog1_log.ldf' , SIZE = 5248KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DMSHistoricLog1] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DMSHistoricLog1].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [DMSHistoricLog1] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [DMSHistoricLog1] SET ANSI_NULLS ON 
GO
ALTER DATABASE [DMSHistoricLog1] SET ANSI_PADDING ON 
GO
ALTER DATABASE [DMSHistoricLog1] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [DMSHistoricLog1] SET ARITHABORT OFF 
GO
ALTER DATABASE [DMSHistoricLog1] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DMSHistoricLog1] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [DMSHistoricLog1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DMSHistoricLog1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DMSHistoricLog1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DMSHistoricLog1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DMSHistoricLog1] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [DMSHistoricLog1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DMSHistoricLog1] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [DMSHistoricLog1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DMSHistoricLog1] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DMSHistoricLog1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DMSHistoricLog1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DMSHistoricLog1] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DMSHistoricLog1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DMSHistoricLog1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DMSHistoricLog1] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DMSHistoricLog1] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DMSHistoricLog1] SET  READ_WRITE 
GO
ALTER DATABASE [DMSHistoricLog1] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DMSHistoricLog1] SET  MULTI_USER 
GO
ALTER DATABASE [DMSHistoricLog1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DMSHistoricLog1] SET DB_CHAINING OFF 
GO
GRANT CONNECT TO [DMSWebUser] AS [dbo]
GO
GRANT CONNECT TO [pnl\D3L243] AS [dbo]
GO
GRANT CONNECT TO [pnl\d3m580] AS [dbo]
GO
GRANT CONNECT TO [RBAC-DMS_User] AS [dbo]
GO
