/****** Object:  Database [DMSHistoricLog] ******/
CREATE DATABASE [DMSHistoricLog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DMSHistLog1_dat', FILENAME = N'J:\SQLServerData\DMSHistoricLog.mdf' , SIZE = 3534272KB , MAXSIZE = UNLIMITED, FILEGROWTH = 262144KB )
 LOG ON 
( NAME = N'DMSHistLog1_log', FILENAME = N'H:\SQLServerData\DMSHistoricLog_log.ldf' , SIZE = 3480448KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DMSHistoricLog].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [DMSHistoricLog] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DMSHistoricLog] SET ANSI_NULLS ON 
GO
ALTER DATABASE [DMSHistoricLog] SET ANSI_PADDING ON 
GO
ALTER DATABASE [DMSHistoricLog] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [DMSHistoricLog] SET ARITHABORT ON 
GO
ALTER DATABASE [DMSHistoricLog] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DMSHistoricLog] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DMSHistoricLog] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DMSHistoricLog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DMSHistoricLog] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DMSHistoricLog] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [DMSHistoricLog] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DMSHistoricLog] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [DMSHistoricLog] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DMSHistoricLog] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DMSHistoricLog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DMSHistoricLog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DMSHistoricLog] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DMSHistoricLog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DMSHistoricLog] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DMSHistoricLog] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DMSHistoricLog] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DMSHistoricLog] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DMSHistoricLog] SET  MULTI_USER 
GO
ALTER DATABASE [DMSHistoricLog] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DMSHistoricLog] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DMSHistoricLog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DMSHistoricLog] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DMSHistoricLog] SET DELAYED_DURABILITY = DISABLED 
GO
USE [DMSHistoricLog]
GO
/****** Object:  User [pnl\D3L243] ******/
CREATE USER [pnl\D3L243] FOR LOGIN [PNL\D3L243] WITH DEFAULT_SCHEMA=[pnl\D3L243]
GO
/****** Object:  User [PNL\D3M578] ******/
CREATE USER [PNL\D3M578] FOR LOGIN [PNL\D3M578] WITH DEFAULT_SCHEMA=[PNL\D3M578]
GO
/****** Object:  User [PNL\D3M580] ******/
CREATE USER [PNL\D3M580] FOR LOGIN [PNL\D3M580] WITH DEFAULT_SCHEMA=[PNL\D3M580]
GO
/****** Object:  User [RBAC-DMS_Developer] ******/
CREATE USER [RBAC-DMS_Developer] FOR LOGIN [PNL\EMSL-Prism.Users.Developers]
GO
/****** Object:  User [RBAC-DMS_User] ******/
CREATE USER [RBAC-DMS_User] FOR LOGIN [PNL\EMSL-Prism.Users.DMS_User]
GO
GRANT SHOWPLAN TO [DDL_Viewer] AS [dbo]
GO
GRANT CONNECT TO [DMSWebUser] AS [dbo]
GO
GRANT CONNECT TO [pnl\D3L243] AS [dbo]
GO
GRANT CONNECT TO [RBAC-DMS_Developer] AS [dbo]
GO
GRANT CONNECT TO [RBAC-DMS_User] AS [dbo]
GO
ALTER DATABASE [DMSHistoricLog] SET  READ_WRITE 
GO
