/****** Object:  Table [T_Analysis_State_Name] ******/
/****** RowCount: 20 ******/
/****** Columns: AJS_stateID, AJS_name, Comment ******/
INSERT INTO [T_Analysis_State_Name] VALUES (0,'(none)','State is unknown')
INSERT INTO [T_Analysis_State_Name] VALUES (1,'New','New')
INSERT INTO [T_Analysis_State_Name] VALUES (2,'Job In Progress','In progress')
INSERT INTO [T_Analysis_State_Name] VALUES (3,'Results Received','No longer used')
INSERT INTO [T_Analysis_State_Name] VALUES (4,'Complete','Complete')
INSERT INTO [T_Analysis_State_Name] VALUES (5,'Failed','Failed')
INSERT INTO [T_Analysis_State_Name] VALUES (6,'Transfer Failed','No longer used')
INSERT INTO [T_Analysis_State_Name] VALUES (7,'No Intermediate Files Created','Manually used to indicate no results')
INSERT INTO [T_Analysis_State_Name] VALUES (8,'Holding','On hold')
INSERT INTO [T_Analysis_State_Name] VALUES (9,'Transfer In Progress','No longer used')
INSERT INTO [T_Analysis_State_Name] VALUES (10,'Spectra Required','No longer used')
INSERT INTO [T_Analysis_State_Name] VALUES (11,'Spectra Req. In Progress','No longer used')
INSERT INTO [T_Analysis_State_Name] VALUES (12,'Spectra Req. Failed','No longer used')
INSERT INTO [T_Analysis_State_Name] VALUES (14,'No Export','Completed, but don''t put in MTS')
INSERT INTO [T_Analysis_State_Name] VALUES (15,'SpecialClusterFailed','No longer used')
INSERT INTO [T_Analysis_State_Name] VALUES (16,'Data Extraction Required','No longer used')
INSERT INTO [T_Analysis_State_Name] VALUES (17,'Data Extraction In Progress','No longer used')
INSERT INTO [T_Analysis_State_Name] VALUES (18,'Data Extraction Failed','No longer used')
INSERT INTO [T_Analysis_State_Name] VALUES (19,'Special Proc. Waiting','Waiting for jobs that this job depends on to finish')
INSERT INTO [T_Analysis_State_Name] VALUES (99,'Job Broker Failure','No longer used')
