/****** Object:  Table [T_DatasetTypeName] ******/
/****** RowCount: 47 ******/
/****** Columns: DST_Type_ID, DST_name, DST_Description, DST_Active ******/
INSERT INTO [T_DatasetTypeName] VALUES (32,'C60-SIMS-HMS','C60 SIMS HMS',1)
INSERT INTO [T_DatasetTypeName] VALUES (35,'Chip_Seq','DNA Sequencing Reads',1)
INSERT INTO [T_DatasetTypeName] VALUES (27,'DataFiles','DMS Pipeline Data or Data Packages',0)
INSERT INTO [T_DatasetTypeName] VALUES (41,'EI-HMS','GC EI coupled with high res MS',1)
INSERT INTO [T_DatasetTypeName] VALUES (39,'GC','GC with FID, ECD, TCD, etc. (no MS)',1)
INSERT INTO [T_DatasetTypeName] VALUES (18,'GC-MS','Full scan GC-MS',1)
INSERT INTO [T_DatasetTypeName] VALUES (19,'GC-SIM','SIM scan GC-MS',1)
INSERT INTO [T_DatasetTypeName] VALUES (1,'HMS','High resolution MS spectra only',1)
INSERT INTO [T_DatasetTypeName] VALUES (21,'HMS-CID/ETD-HMSn','High res MS with high res ETD-based MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (12,'HMS-CID/ETD-MSn','High res MS with low res, alternating CID and ETD MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (46,'HMS-ETciD-MSn','High res MS with ETD fragmentation, then further fragmented by CID in the ion trap',1)
INSERT INTO [T_DatasetTypeName] VALUES (25,'HMS-ETD-HMSn','High res MS with high res ETD-based MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (11,'HMS-ETD-MSn','High res MS with low res ETD-based MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (45,'HMS-EThcD-MSn','High res MS with ETD fragmentation, then further fragmented by HCD in the ion routing multipole',1)
INSERT INTO [T_DatasetTypeName] VALUES (24,'HMS-HCD-CID-HMSn','High res MS with high res HCD MSn and high res CID MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (23,'HMS-HCD-CID-MSn','High res MS with high res HCD MSn and low res CID MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (20,'HMS-HCD-CID/ETD-HMSn','High res MS with high res HCD MSn and high res CID or ETD MSn (decision tree)',1)
INSERT INTO [T_DatasetTypeName] VALUES (14,'HMS-HCD-CID/ETD-MSn','High res MS with high res HCD MSn and low res CID or ETD MSn (decision tree)',1)
INSERT INTO [T_DatasetTypeName] VALUES (22,'HMS-HCD-ETD-HMSn','High res MS with high res HCD MSn and high res ETD MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (15,'HMS-HCD-ETD-MSn','High res MS with high res HCD MSn and low res ETD MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (13,'HMS-HCD-HMSn','High res MS with high res HCD MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (5,'HMS-HMSn','High res MS with high res CID MSn (and possibly some low res MSn)',1)
INSERT INTO [T_DatasetTypeName] VALUES (3,'HMS-MSn','High res MS with low res CID MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (16,'HMS-PQD-CID/ETD-MSn','High res MS with low res PQD MSn and low res CID or ETD MSn (decision tree)',1)
INSERT INTO [T_DatasetTypeName] VALUES (17,'HMS-PQD-ETD-MSn','High res MS with low res PQD MSn and low res ETD-based MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (6,'IMS-HMS','Ion mobility sep then high res MS detection',1)
INSERT INTO [T_DatasetTypeName] VALUES (30,'IMS-HMS-HMSn','Ion mobility sep with high res MS, fragmentation of all ions with high res MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (7,'IMS-HMS-MSn','Ion mobility sep, fragmentation of all ions, high res MS',1)
INSERT INTO [T_DatasetTypeName] VALUES (40,'LAESI-HMS','LAESI source coupled to a high res MS detector (Orbitrap or 21T)',1)
INSERT INTO [T_DatasetTypeName] VALUES (26,'MALDI-HMS','MALDI MS',1)
INSERT INTO [T_DatasetTypeName] VALUES (38,'MP_Seq','DNA Sequencing Reads',1)
INSERT INTO [T_DatasetTypeName] VALUES (9,'MRM','Multiple reaction monitoring-triple quad',1)
INSERT INTO [T_DatasetTypeName] VALUES (34,'mRNA_Seq','DNA Sequencing Reads',1)
INSERT INTO [T_DatasetTypeName] VALUES (4,'MS','Low resolution MS spectra only',1)
INSERT INTO [T_DatasetTypeName] VALUES (10,'MS-CID/ETD-MSn','Low res MS, with low res, alternating CID and ETD MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (8,'MS-ETD-MSn','Low res MS with low res ETD-based MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (28,'MS-HCD-CID-MSn','Low res MS with low res, alternating CID and HCD MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (29,'MS-HCD-MSn','Low res MS with low res HCD MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (2,'MS-MSn','Low res MS with low res CID MSn',1)
INSERT INTO [T_DatasetTypeName] VALUES (37,'PE_Seq','DNA Sequencing Reads',1)
INSERT INTO [T_DatasetTypeName] VALUES (33,'RNA_Seq','DNA Sequencing Reads',1)
INSERT INTO [T_DatasetTypeName] VALUES (36,'Target_DNA_Seq','DNA Sequencing Reads',1)
INSERT INTO [T_DatasetTypeName] VALUES (100,'Tracking','Instrument usage tracking only - no capture',1)
INSERT INTO [T_DatasetTypeName] VALUES (31,'UV','UV detector',1)
INSERT INTO [T_DatasetTypeName] VALUES (42,'x_CID-MSn','To be deleted:   Low res CID MSn (no MS1)',0)
INSERT INTO [T_DatasetTypeName] VALUES (44,'x_ETD-MSn','To be deleted:   Low res ETD-based MSn (no MS1)',0)
INSERT INTO [T_DatasetTypeName] VALUES (43,'x_HCD-MSn','To be deleted:   Low res HCD MSn (no MS1)',0)
