/****** Object:  Table [T_Default_PSM_Job_Settings] ******/
/****** RowCount: 40 ******/
SET IDENTITY_INSERT [T_Default_PSM_Job_Settings] ON
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (23,'MSGFPlus','High Res ms1',0,0,'IonTrapDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (29,'MSGFPlus','High Res ms1',0,1,'IonTrapDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (26,'MSGFPlus','High Res ms1',1,0,'IonTrapDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (32,'MSGFPlus','High Res ms1',1,1,'IonTrapDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (24,'MSGFPlus','iTRAQ 4-plex',0,0,'IonTrapDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (30,'MSGFPlus','iTRAQ 4-plex',0,1,'IonTrapDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (27,'MSGFPlus','iTRAQ 4-plex',1,0,'IonTrapDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (33,'MSGFPlus','iTRAQ 4-plex',1,1,'IonTrapDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (22,'MSGFPlus','Low Res ms1',0,0,'IonTrapDefSettings.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (28,'MSGFPlus','Low Res ms1',0,1,'IonTrapDefSettings.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (25,'MSGFPlus','Low Res ms1',1,0,'IonTrapDefSettings.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (31,'MSGFPlus','Low Res ms1',1,1,'IonTrapDefSettings.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (34,'MSGFPlus_DTARefinery','High Res ms1',0,0,'IonTrapDefSettings_DeconMSN_DTARef_NoMods.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (38,'MSGFPlus_DTARefinery','High Res ms1',0,1,'IonTrapDefSettings_DeconMSN_DTARef_phospho.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (36,'MSGFPlus_DTARefinery','High Res ms1',1,0,'IonTrapDefSettings_DeconMSN_DTARef_StatCysAlk.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (40,'MSGFPlus_DTARefinery','High Res ms1',1,1,'IonTrapDefSettings_DeconMSN_DTARef_StatCysAlk_phospho.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (35,'MSGFPlus_DTARefinery','iTRAQ 4-plex',0,0,'IonTrapDefSettings_DeconMSN_DTARef_4plexITRAQ.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (39,'MSGFPlus_DTARefinery','iTRAQ 4-plex',0,1,'IonTrapDefSettings_DeconMSN_DTARef_4plexITRAQ_phospho.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (37,'MSGFPlus_DTARefinery','iTRAQ 4-plex',1,0,'IonTrapDefSettings_DeconMSN_DTARef_StatCysAlk_4plexITRAQ.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (41,'MSGFPlus_DTARefinery','iTRAQ 4-plex',1,1,'IonTrapDefSettings_DeconMSN_DTARef_StatCysAlk_4plexITRAQ_phospho.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (3,'Sequest','High Res ms1',0,0,'FinniganDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (9,'Sequest','High Res ms1',0,1,'FinniganDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (6,'Sequest','High Res ms1',1,0,'FinniganDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (12,'Sequest','High Res ms1',1,1,'FinniganDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (4,'Sequest','iTRAQ 4-plex',0,0,'FinniganDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (10,'Sequest','iTRAQ 4-plex',0,1,'FinniganDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (7,'Sequest','iTRAQ 4-plex',1,0,'FinniganDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (13,'Sequest','iTRAQ 4-plex',1,1,'FinniganDefSettings_DeconMSN.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (1,'Sequest','Low Res ms1',0,0,'FinniganDefSettings.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (8,'Sequest','Low Res ms1',0,1,'FinniganDefSettings.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (5,'Sequest','Low Res ms1',1,0,'FinniganDefSettings.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (11,'Sequest','Low Res ms1',1,1,'FinniganDefSettings.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (14,'Sequest_DTARefinery','High Res ms1',0,0,'FinniganDefSettings_DeconMSN_DTARef_NoMods.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (18,'Sequest_DTARefinery','High Res ms1',0,1,'FinniganDefSettings_DeconMSN_DTARef_phospho.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (16,'Sequest_DTARefinery','High Res ms1',1,0,'FinniganDefSettings_DeconMSN_DTARef_StatCysAlk.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (20,'Sequest_DTARefinery','High Res ms1',1,1,'FinniganDefSettings_DeconMSN_DTARef_StatCysAlk_phospho.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (15,'Sequest_DTARefinery','iTRAQ 4-plex',0,0,'FinniganDefSettings_DeconMSN_DTARef_4plexITRAQ.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (19,'Sequest_DTARefinery','iTRAQ 4-plex',0,1,'FinniganDefSettings_DeconMSN_DTARef_4plexITRAQ_phospho.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (17,'Sequest_DTARefinery','iTRAQ 4-plex',1,0,'FinniganDefSettings_DeconMSN_DTARef_StatCysAlk_4plexITRAQ.xml')
INSERT INTO [T_Default_PSM_Job_Settings] (Entry_ID, Tool_Name, Job_Type_Name, StatCysAlk, DynSTYPhos, Settings_File_Name) VALUES (21,'Sequest_DTARefinery','iTRAQ 4-plex',1,1,'FinniganDefSettings_DeconMSN_DTARef_StatCysAlk_4plexITRAQ_phospho.xml')
SET IDENTITY_INSERT [T_Default_PSM_Job_Settings] OFF
