/****** Object:  Table [T_EUS_Proposal_Type] ******/
/****** RowCount: 31 ******/
/****** Columns: Proposal_Type, Proposal_Type_Name, Abbreviation, Comment ******/
INSERT INTO [T_EUS_Proposal_Type] VALUES ('BRC Research','BRC Research','BRCResearch',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Capability','Capability','Cap',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Capability Research','Capability Research','Cap',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Capacity','Capacity','Capacity',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('CAT','CAT','CAT',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('EMSL','EMSL','EMSL',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('EMSL-ARM Joint Call','EMSL-ARM Joint Call','EMSL-ARM',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Exploratory Research','Exploratory Research','ExploratoryResearch',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('FICUS JGI-EMSL','FICUS JGI-EMSL','FICUS',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('FICUS Research','FICUS Research','FICUS',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('GENERAL','General','General',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('General Cycle','General Cycle','General',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Grand Challenge','Grand Challenge','GrandChal',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Intramural S&T','Intramural S&T','Intramural',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('JGI-EMSL Joint Call','JGI-EMSL Joint Call','JGI-EMSL',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Large-Scale EMSL Research','Large-Scale EMSL Research','LargeScaleEMSL',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Limited Scope','Limited Scope','LimScope',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('LIMITED_SCOPE','Limited Scope','LimScope',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Open','Open','Open',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('PARTNER','Partner','Partner',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('PROPRIETARY','Proprietary','Prop',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('PROPRIETARY_PUBLIC','Proprietary Public','PropPub',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('RAPID','Rapid','Rapid',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Research Campaign','Research Campaign','ResCampn',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Resource Owner','Resource Owner','ResOwnr',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('RESOURCE_OWNER','Resource Owner','ResOwnr',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Science Area Research','Science Area Research','SciResearch',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Science Theme','Science Theme','SciTheme',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Science Theme Research','Science Theme Research','SciTheme',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Special Science','Special Science','SpecialSci',null)
INSERT INTO [T_EUS_Proposal_Type] VALUES ('Staff Time','Staff Time','StaffTime',null)
