/****** Object:  Table [T_Filter_Set_Criteria_Names] ******/
/****** RowCount: 28 ******/
SET IDENTITY_INSERT [T_Filter_Set_Criteria_Names] ON
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (1,'Spectrum_Count','Number of distinct spectra the peptide is observed in, taking into account datasets analyzed multiple times')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (2,'Charge','Peptide charge')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (3,'High_Normalized_Score','Highest normalized score (e.g. XCorr for Sequest) observed')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (4,'Cleavage_State','For trypsin, 2=fully tryptic, 1=partially tryptic, 0=non tryptic')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (5,'Peptide_Length','Number of residues in the peptide')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (6,'Mass','Peptide mass')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (7,'DelCn','DeltaCn value, the normalized difference between the given peptide''s XCorr and the highest scoring peptide''s XCorr')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (8,'DelCn2','DeltaCn2 value, the normalized difference between the given peptide''s XCorr and the next lower scoring peptide''s XCorr (DeltaCN2 for XTandem is Hyperscore-based; DeltaCN2 for Inspect is DeltaNormTotalPRMScore)')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (9,'Discriminant_Score','Sequest-based discriminant score')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (10,'NET_Difference_Absolute','Absolute value of the difference between observed normalized elution time (NET) and predicted NET')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (11,'Discriminant_Initial_Filter','Filter based on Xcorr, DelCN, RankXc and the number of tryptic termini (PassFilt column in synopsis and fht files)')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (12,'Protein_Count','Count of the number of proteins that a given peptide sequence is found in')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (13,'Terminus_State','Non-zero if peptide is at terminus of protein; 1=N-terminus, 2=C-terminus, 3=N and C-terminus')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (14,'XTandem_Hyperscore','XTandem Hyperscore')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (15,'XTandem_LogEValue','XTandem E-Value (base-10 log)')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (16,'Peptide_Prophet_Probability','Sequest-based probability developed by Andrew Keller; for Inspect, use 1-PValue; in both cases, closer to 1 is higher confidence')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (17,'RankScore','The rank of the given peptides score within the given scan; for Sequest, this is RankXc; for Inspect this is RankFScore')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (18,'Inspect_MQScore','Inspect MQScore')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (19,'Inspect_TotalPRMScore','Inspect TotalPRMScore')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (20,'Inspect_FScore','Inspect FScore')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (21,'Inspect_PValue','Inspect PValue')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (22,'MSGF_SpecProb','MSGF Spectrum Probability value; closer to 0 is higher confidence')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (23,'MSGFDB_SpecProb','MSGFDB Spectrum Probability; closer to 0 is higher confidence')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (24,'MSGFDB_PValue','MSGFDB PValue')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (25,'MSGFPlus_QValue','MSGF+ QValue (aka FDR for MSGFDB)')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (26,'MSAlign_PValue','MSAlign PValue')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (27,'MSAlign_FDR','MSAlign FDR')
INSERT INTO [T_Filter_Set_Criteria_Names] (Criterion_ID, Criterion_Name, Criterion_Description) VALUES (28,'MSGFPlus_PepQValue','MSGF+ PepQValue (aka PepFDR for MSGFDB)')
SET IDENTITY_INSERT [T_Filter_Set_Criteria_Names] OFF
