/****** Object:  Table [T_Instrument_Group] ******/
/****** RowCount: 57 ******/
/****** Columns: IN_Group, Usage, Comment, Active, Default_Dataset_Type, Allocation_Tag, Sample_Prep_Visible, Requested_Run_Visible, Target_Instrument_Group ******/
INSERT INTO [T_Instrument_Group] VALUES ('11T','Research','',0,1,null,0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('21T','Research','',1,1,'FT',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('5500XL_SOLiD','Genomic Sequencing',null,0,33,'SEQ',0,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('Agilent_FTMS','Research','',0,1,'FT',0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Agilent_GC','Research','',0,39,'GC',0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Agilent_GC-MS','Metabolomics','',1,18,'GC',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Agilent_Ion_Trap','Research','',0,2,null,0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Agilent_QQQ','MRM','',1,9,'QQQ',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Agilent_TOF','Research','',0,1,null,0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Agilent_TOF_V2','Research','',1,3,'TOF',0,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('Altis','MRM','',0,9,'QQQ',0,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('Ascend','LC-HMS with MS/MS','',1,13,'ORB',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Ascend_Frac','Requested runs with LC-MicroHpH, LC-MicroSCX, LC-NanoHpH, etc.','',1,13,'ORB',0,1,'Ascend')
INSERT INTO [T_Instrument_Group] VALUES ('Bruker_Amazon_Ion_Trap','Research','',0,3,null,0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Bruker_FTMS','Research','',1,1,'FT',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Bruker_QTOF','Research','',0,5,'TOF',0,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('DataFolders','DMS Pipeline Data','',0,27,null,0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Eclipse','LC-HMS with MS/MS','',1,13,'ORB',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Eclipse_Frac','Requested runs with LC-MicroHpH, LC-MicroSCX, LC-NanoHpH, etc.','',1,13,'ORB',0,1,'Eclipse')
INSERT INTO [T_Instrument_Group] VALUES ('Exactive','LC-HMS (no MS/MS)','',0,1,'EXA',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Exploris','LC-HMS with MS/MS; optionally HCD','',1,5,'ORB',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Exploris_Frac','Requested runs with LC-MicroHpH, LC-MicroSCX, LC-NanoHpH, etc.','',1,5,'ORB',0,1,'Exploris')
INSERT INTO [T_Instrument_Group] VALUES ('FT_ZippedSFolders','Research','',0,1,null,0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('GC-QExactive','Metabolomics',null,1,41,'ORB',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('GC-TSQ','Metabolomics','',0,9,'GC',0,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('Illumina','Genomic Sequencing',null,0,33,'SEQ',1,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('IMS','Ion-mobility LC-IMS-MS','',1,6,'IMS',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('LCQ','Low res MS/MS','',0,2,null,0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('LTQ','Low res MS/MS','',1,2,'LTQ',0,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('LTQ-ETD','Low res MS/MS ETD','',0,2,'LTQ',0,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('LTQ-FT','LC-HMS with MS/MS','',0,3,'FT',0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('LTQ-Prep','LTQ in BSF sample prep lab','',0,2,'LTQ',1,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('Lumos','LC-HMS with MS/MS; optionally ETD','',1,5,'ORB',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Lumos_Frac','Requested runs with LC-MicroHpH, LC-MicroSCX, LC-NanoHpH, etc.','',1,5,'ORB',0,1,'Lumos')
INSERT INTO [T_Instrument_Group] VALUES ('MALDI-Imaging','MALDI Imaging','',1,26,'MAL',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('MALDI-TOF','MALDI Spot',null,0,26,'MAL',0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('NMR','Research','For use in sample prep requests',1,51,'NMR',1,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('Orbitrap','LC-HMS with MS/MS','',0,3,'ORB',1,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('Other','Research','',1,null,'None',0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('PrepHPLC','Prep HPLC Data folders','',1,31,'None',0,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('QEHFX','LC-HMS with MS/MS; optionally HCD','',1,5,'ORB',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('QEHFX_Frac','Requested runs with LC-MicroHpH, LC-MicroSCX, LC-NanoHpH, etc.','',1,5,'ORB',0,1,'QEHFX')
INSERT INTO [T_Instrument_Group] VALUES ('QExactive','LC-HMS with MS/MS; optionally HCD','Was originally used by LTQ_Orb_3, but changed LTQ_Orb_3 to the "Orbitrap" group in May 2012.  Renamed this group from Orbitrap-HCD to QExactive in December 2012',1,5,'ORB',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('QExactive-Imaging','QExactive with MALDI source','',1,5,'ORB',0,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('QExactive_Frac','Requested runs with LC-MicroHpH, LC-MicroSCX, LC-NanoHpH, etc.','',1,5,'ORB',0,1,'QExactive')
INSERT INTO [T_Instrument_Group] VALUES ('QTrap','Research','MRM',0,3,'QQQ',0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Sciex_TripleTOF','Research','',0,5,null,0,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('Shimadzu_GC','Real-time atmospheric monitoring','',1,18,'GC',0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('SLIM','Ion-mobility LC-IMS-MS with SLIM','',1,6,'IMS',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Thermo_SII_LC','LC instruments controlled using SII for Xcalibur','SII - Standard Instrument Integration, allows controlling Chromeleon-supported LC modules from Xcalibur',1,31,'None',0,0,null)
INSERT INTO [T_Instrument_Group] VALUES ('timsTOF','LC-IMS-MS with MS/MS','Bruker timsTOF',1,30,'TOF',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('TSQ','MRM','',1,9,'QQQ',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('TSQ_Frac','Requested runs with LC-MicroHpH, LC-MicroSCX, LC-NanoHpH, etc.','',1,9,'QQQ',0,1,'TSQ')
INSERT INTO [T_Instrument_Group] VALUES ('VelosOrbi','LC-HMS with MS/MS; optionally ETD','',1,3,'ORB',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('VelosPro','Ion trap instrument with CID, HCD, PQD, or ETD; No orbitrap','',0,2,'LTQ',0,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Waters_IMS','Waters Synapt IMS','',1,6,'IMS',1,1,null)
INSERT INTO [T_Instrument_Group] VALUES ('Waters_TOF','Research','',1,1,'TOF',0,1,null)
