/****** Object:  Table [T_Instrument_Group_Allowed_DS_Type] ******/
/****** RowCount: 124 ******/
/****** Columns: IN_Group, Dataset_Type, Comment ******/
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('11T','HMS','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('11T','HMS-HMSn','Rarely used')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('5500XL_SOLiD','Chip_Seq','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('5500XL_SOLiD','MP_Seq','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('5500XL_SOLiD','mRNA_Seq','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('5500XL_SOLiD','PE_Seq','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('5500XL_SOLiD','RNA_Seq','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('5500XL_SOLiD','Target_DNA_Seq','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('5500XL_SOLiD','Tracking','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_FTMS','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_GC','GC','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_GC-MS','GC-MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_GC-MS','GC-SIM','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_Ion_Trap','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_Ion_Trap','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_TOF','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_TOF_V2','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_TOF_V2','HMS-HMSn','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Agilent_TOF_V2','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_Amazon_Ion_Trap','MS-CID/ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_Amazon_Ion_Trap','MS-ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_Amazon_Ion_Trap','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_FTMS','C60-SIMS-HMS','Single-scan C60 SIMS')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_FTMS','HMS','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_FTMS','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_FTMS','MALDI-HMS','Single-scan MALDI (not imaging)')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_QTOF','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_QTOF','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Bruker_QTOF','MALDI-HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('DataFolders','DataFiles','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Exactive','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('FT_ZippedSFolders','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('GC-QExactive','EI-HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('GC-TSQ','GC-MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('GC-TSQ','MRM','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('IMS','IMS-HMS','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('IMS','IMS-HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('IMS','IMS-HMS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LCQ','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LCQ','MS-MSn','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ','MS-MSn','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-ETD','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-ETD','MS-CID/ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-ETD','MS-ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-ETD','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-FT','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-FT','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-FT','HMS-MSn','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-FT','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-Prep','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('LTQ-Prep','MS-MSn','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-CID/ETD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-CID/ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-ETciD-EThcD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-ETciD-EThcD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-ETciD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-ETciD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-ETD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-EThcD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-EThcD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-HCD-CID-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-HCD-CID-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-HCD-CID/ETD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-HCD-CID/ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-HCD-ETD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-HCD-ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-HCD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-PQD-CID/ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','HMS-PQD-ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Lumos','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('MALDI-Imaging','C60-SIMS-HMS','Imaging datasets using C60 SIMS')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('MALDI-Imaging','MALDI-HMS','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('MALDI-TOF','MALDI-HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Micromass_TOF','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Micromass_TOF','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap','HMS-MSn','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Orbitrap','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Other','HMS-HCD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Other','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Other','HMS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Other','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Other','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('PrepHPLC','UV','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('QExactive','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('QExactive','HMS-HCD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('QExactive','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('QTrap','MRM','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('QTrap','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('QTrap','MS-MSn','Typical mode')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('Sciex_TripleTOF','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('TSQ','MRM','Use for MRM')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('TSQ','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('TSQ','MS-MSn','Use for MSn')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-CID/ETD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-CID/ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-ETD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HCD-CID-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HCD-CID-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HCD-CID/ETD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HCD-CID/ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HCD-ETD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HCD-ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HCD-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-HMSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-PQD-CID/ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','HMS-PQD-ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','LAESI-HMS','LAESI source coupled to an Orbitrap; results are in folders with a .raw file plus related files')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosOrbi','MS-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosPro','MS','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosPro','MS-CID/ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosPro','MS-ETD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosPro','MS-HCD-CID-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosPro','MS-HCD-MSn','')
INSERT INTO [T_Instrument_Group_Allowed_DS_Type] VALUES ('VelosPro','MS-MSn','')
