/****** Object:  Table [T_LC_Cart] ******/
/****** RowCount: 107 ******/
SET IDENTITY_INSERT [T_LC_Cart] ON
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (1,'unknown',1,'Not a valid cart',null)
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (2,'No_Cart',2,'An ad hoc or non cart based LC apparatus was used','3/10/2006 10:34:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (11,'Andromeda',10,'Single emmitter system.','3/10/2006 12:47:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (12,'Doc',10,'','3/10/2006 10:28:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (13,'Draco',10,'','3/14/2006 9:07:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (14,'Earth',10,'','3/13/2006 7:36:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (15,'Firefly',2,'nanoPOTS autosampler','3/10/2006 4:14:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (16,'Griffin',10,'','3/20/2006 7:30:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (17,'Pegasus',10,'Fast Separation','6/20/2006 11:52:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (18,'Phoenix',10,'Installed Eksigent pumps November 2012.','3/13/2006 3:04:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (19,'Raptor',10,'','6/8/2007 2:17:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (20,'Roc',10,'Metabolomics Cart','3/10/2006 9:52:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (27,'Falcon',10,'LC ISCO Formic, 4 column 10k constant pressure system. The Flagship of our LC fleet.','5/22/2006 8:36:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (28,'Hawk',10,'','4/18/2006 11:06:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (29,'Sphinx',10,'','3/10/2006 5:34:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (30,'Agilent',2,'Commercial Agilent 1100 capillary HPLC system outfitted with binary pumps, autosampler, degasser and solvent tray','3/13/2006 12:30:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (31,'Protein_RP',10,'This is a manual LC system used for intact protein separations. Comprised of 2 10k-psi ISCO pumps and controller, 10k-psi (1/16" fittings) valves with back-side pressure sealing. Valve configurations; 6 port injection valve, 4 port mobile phase select valve, and 4 port column select valve. Home-made mixer for gradient formation. On/off valve for selecting between mixer purge and splitter column.','3/10/2006 5:37:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (32,'Yufeng_20k-psi',10,'This is an R&D LC system used primarily by Yufeng Shen and is modified routinely for different applications. Revision history will NOT be maintained for this LC system.','5/1/2006 9:09:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (33,'Pluto',10,'Manual LC cart','4/5/2006 9:32:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (34,'Owl',10,'','9/6/2006 8:14:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (35,'Eagle',10,'Dedicated to IMS capability development 3/9/2010. Configured for extended separations.','9/18/2006 5:01:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (36,'Kestrel',10,'20,000 psi mixers','3/18/2008 4:40:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (37,'Osprey',10,'15 Minute Separation','6/16/2009 3:35:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (38,'VENUS',10,'metal-free, up to 5k psi','2/12/2009 1:00:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (39,'SATURN',10,'manual single column LC cart w/ SPE','5/13/2009 1:15:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (40,'2D_online',10,'1st Dimension, HILIC,2nd Dimension, RPLC,20 online fractionation storage loops','6/22/2009 10:58:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (41,'Tambora',10,'Agilent cart','10/1/2009 2:24:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (42,'Mazama',10,'Agilent Cart','9/29/2009 4:10:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (43,'Tiger',2,'First ARRA NexGen L 3 Agilent Pumps (2 nano and 1 cap) 8 Two Position Valves and 4 Multi-Position valves, PAL','3/16/2010 12:38:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (44,'Lion',10,'Second Dimension HILIC cart.  Next Generation LC 3 Agilent Pumps (2 nano and 1 cap) 8 Two Position Valves and 4 Multi-Position valves, PAL','10/21/2010 11:58:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (45,'Lynx',3,'2nd ARRA Next-Gen 3 Agilent Pumps (2 nano and 1 cap) 8 Two Position Valves and 4 Multi-Position valves, PAL','4/16/2010 10:17:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (46,'Cougar',10,'3rd ARRA Next Generation LC 3 Agilent Pumps (2 nano and 1 cap) 8 Two Position Valves and 4 Multi-Position valves, PAL','5/21/2010 6:14:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (47,'Cheetah',10,'4th ARRA Next Gen Platform 3 Agilent Pumps (2 nano and 1 cap) 8 Two Position Valves and 4 Multi-Position valves, PAL','6/23/2010 5:43:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (48,'Harrier',10,'4 Column Phospho Cart','9/23/2010 1:51:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (49,'Gandalf',2,'#4 2D Waters NanoAcquity LC, easy conversion to 1D cart.  Serial numbers nBSM:F10NPB865N;nBSM2:F10NPB866N;nSM:F10NPS742M.','8/23/2010 11:44:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (50,'Aragorn',2,'#2 2D Waters NanoAcquity LC, easy conversion to 1D cart.  Serial numbers nBSM:G10NPB891N;nBSM2:E10NPB862N;nSM:F10NPS739M.','8/23/2010 11:45:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (51,'Legolas',3,'#3 2D Waters NanoAcquity LC, easy conversion to 1D cart.  Serial numbers nBSM:E10NPB863N;nSM:F10NPS741M.','8/23/2010 11:44:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (52,'Gimli',2,'#1 2D Waters NanoAcquity LC, easy conversion to 1D cart.  Serial numbers nBSM:E10NPB859N;nSM:L10NPS876M.','8/23/2010 11:30:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (53,'Frodo',2,'#5 2D Waters NanoAcquity LC, easy conversion to 1D cart.  Serial numbers nBSM:F10NPB868N;nBSM2:F10NPB869N;nSM:F10NPS743M.','9/14/2010 4:53:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (54,'Sauron',2,'#6 2D Waters NanoAcquity LC, easy conversion to 1D cart.  Serial numbers nBSM:H10NPB926N;nBSM2:F10NPB872N;nSM:F10NPS745M.','8/23/2010 11:25:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (57,'Auto_2D_online',10,'Auto version of 2D_online. Fractions from 1st D RPLC are transferred online w/ UV monitoring to 2nd D WCX-HILIC which has 4 SPEs and 4 columns.','12/2/2010 9:07:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (58,'Polaroid',2,'Constant Flow Waters Nano-Acquity (1d only). Serial numbers nBSM:M10NPB053N;nSM:A11NPS920M.','2/19/2011 12:28:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (60,'Jaguar',10,'3 Agilent Pumps (2 nano and 1 cap) 8 Two Position Valves and 4 Multi-Position valves, PAL','4/13/2011 9:55:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (61,'Samwise',2,'NanoAcquity cart acquired from Tox-Refurbished for Global Lipidomics. Serial numbers nBSM:M08NPB528N;nBSM2:A09NPB545N;nSM:A09NPS508M.','8/4/2012 8:46:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (62,'Blue_Spruce',10,'Advion Nanomate with LESA upgrade (Infusion, LC Coupling and LSEA tissue)','10/23/2012 8:45:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (63,'Pippin',2,'NanoAcquity cart acquired from Tox-Refurbished for Global Lipidomics. Serial numbers nBSM:M08NPB528N;nBSM2:A09NPB545N;nSM:A09NPS508M.','11/28/2012 10:53:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (64,'Iris',10,'Manual LC in BSF 1208 for sample prep use','12/10/2012 3:56:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (65,'Leopard',10,'New, used to be Roc','1/15/2013 11:56:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (66,'Methow',10,'Eksigent pumps. Used to be Phoenix','1/15/2013 6:09:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (67,'Rogue',2,'Used to be Lion, changed naming convention','1/18/2013 11:14:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (68,'Snake',10,'Used to be Eagle renamed to reflect Eksigent','1/21/2013 6:04:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (69,'Columbia',10,'Eksigent System.  Used to be Andromeda','4/9/2013 11:20:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (70,'Smeagol',2,'#1 2D Waters NanoAcquity LC 1D cart.  Serial numbers nBSM:L12NPB418N;nSM:F12NPS111M','2/21/2013 8:42:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (72,'Merry',2,'Waters 2DLC commercial system','3/1/2013 9:15:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (73,'Cedar',3,'LCMSnet controlled cart with Waters pumps and ISCO for loading.  Cart reconfigured in IDL to accommodate Waters Pumps','8/27/2014 4:20:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (74,'Alder',2,'Being used for online digestion','6/25/2013 10:19:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (75,'Nautilus',10,'The Nautilus LC cart is a 1200 series Agilent Nanopump and Auto sampler.','8/13/2013 3:58:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (76,'Einstein',10,'ISCO pumps for Direct Infusion of DOM samples','9/10/2013 10:27:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (77,'Bane',2,'This is the Waters LC specifically for intact protein analysis. Configuration includes two pumps and a sample manager.','1/8/2014 1:57:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (78,'Arwen',2,'M Class Waters 2D LC','9/29/2014 12:14:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (79,'Oak',2,'Thermo/Dionex pump (800 bar) with an ISCO on the low boy.  Short armed pal. LCMSnet controlled','12/1/2014 9:33:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (80,'Rainier',2,'Thermo Vanquish System','1/29/2015 5:41:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (81,'Precious',2,'Waters 1D M-Class nano-Acquity','3/27/2015 2:59:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (82,'Kite',10,'Formerly called IMAC.  Renamed to reflect style of cart.  Auto version of 2D_online. Fractions from 1st D RPLC are transferred online w/ UV monitoring to 2nd D WCX-HILIC which has 4 SPEs and 4 columns.','1/11/2015 11:29:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (84,'Wally',10,'Waters M-Class 2D nano-Acquity','9/29/2016 10:28:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (85,'Fir',2,'Smaller cart Agilent pumps from Cougar,','5/6/2015 5:11:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (86,'Hoopty',2,'S&S industries HTP cart for multiple and optimal infusion experiments','8/20/2015 2:00:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (87,'RapidFire365-01',2,'Agilent RapidFire 365 SPE','11/12/2015 9:48:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (88,'Beech',10,'Direct infusion cart capable of 1200 samples per day','3/12/2016 1:34:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (89,'Lola',2,'Waters H-Class UHPLC','8/30/2016 9:27:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (90,'Bilbo',2,'1D Waters NanoAcquity','9/26/2016 8:37:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (93,'Brandi',2,'Waters H-Class UHPLC','12/5/2016 11:00:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (94,'Elm',2,'Thermo/Dionex pump (800 bar) with an ISCO on the low boy.  Short armed pal. LCMSnet controlled.  Small form factor cart, desktop computer','3/3/2017 8:19:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (95,'Magnolia',2,'Micro-flow infusion cart','3/15/2017 12:15:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (96,'Aspen',10,'Infusion system composed of a PAL autosampler and an Agilent nano pump.','6/16/2017 2:50:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (97,'IronMan',2,'Dionex Ultimate 3000 nano RSLC for metallomics','8/30/2017 9:18:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (98,'Yew',10,'','9/28/2017 12:52:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (107,'GCQE01',2,'Thermo GC Q-Exactive','11/21/2017 2:17:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (108,'ValcoNanoPump',2,'This is manual testing configuration for pump from Valco Feb 2018','2/22/2018 1:12:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (109,'Juniper',10,'Thermo/Dionex pump (800 bar). Long armed pal. LCMSnet controlled. Small form factor cart, laptop computer','3/2/2018 5:53:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (110,'Balzac',2,'Waters 1D M-Class nano-Acquity','5/10/2018 3:34:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (111,'NanoPots-3',2,'Thermo/Dionex pump (800 bar). Manual injection.','8/24/2018 9:45:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (113,'Romulus',2,'Thermo Dionex Ultimate 3000 with autosampler, gradient pump, loading pump, and column heating / trapping compartment','1/29/2019 8:55:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (114,'Remus',2,'Thermo Dionex Ultimate 3000 with autosampler, gradient pump, loading pump, and column heating / trapping compartment','1/29/2019 8:56:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (115,'Rage',2,'Waters 1D M-Class nano-Acquity','4/22/2019 4:09:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (116,'Fiji',2,'Agilent 1260 Infinity II high flow system, Sampler DEAGQ00605, Pump DEAE800647, Column Heater (1100 Series) DE11123368','8/14/2019 2:11:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (117,'Tahiti',2,'Agilent 1260 Infinity II, Vialsampler G7129C DEAGQ01116, Bin Pump G7112B DEAB00808, Column Heater DEAED14113','8/14/2019 4:34:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (118,'Mosquito',2,'Nano-Pots auto-sampler','11/13/2019 2:31:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (119,'Larch',2,'Smaller cart with short armed PAL capacity for 4 valves','12/5/2019 1:16:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (120,'Cicero',2,'Thermo Dionex Ultimate 3000 with autosampler, gradient pump, loading pump, and column heating / trapping compartment','1/16/2020 1:57:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (121,'Kristin',2,'Agilent 1290 LC system','3/18/2020 12:48:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (122,'Guam',10,'Agilent 1290 Infinity ALS (Autosampler) Model: G1329A Serial: DE64776208, Agilent 1200 Bin Pump Model: G1312A Serial: DE63060488','10/7/2020 2:18:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (123,'Glacier',2,'Thermo Vanquish System running Thermo SII','10/13/2020 4:17:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (124,'Stretch',2,'Dionex Ultimate 3000 RSLCnano System','10/20/2020 5:34:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (125,'Roxanne',2,'Waters High-Flow H-class+ Sample Manager-FTN and Quaternary Solvent Manager','11/16/2020 4:45:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (126,'Titus',2,'Thermo Dionex Ultimate 3000 with autosampler, gradient pump, loading pump, and column heating / trapping compartment','9/13/2021 1:25:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (127,'Evosep02',2,'Online Desalting LC','4/5/2022 5:39:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (128,'Tonga',2,'Formerly the NMR fractionation LC.  Agilent 1290 Infinity II Pump, Autosampler, Column Heater, UV detector and Fraction collector','6/10/2022 10:58:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (129,'Evosep01',2,'Online Desalting LC','8/31/2022 7:08:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (130,'Birch',2,'Thermo/Dionex pump (800 bar) with Loading Pump .  Long armed pal. LCMSnet controlled','10/4/2022 2:11:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (131,'Crater',2,'Thermo Vanquish Flex with two column compartments and a quaternary pump.','10/20/2022 10:08:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (132,'Olympic',2,'Thermo Vanquish Flex with two column compartments and a quaternary pump.','10/21/2022 2:30:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (133,'Teton',2,'Thermo Vanquish Neo system, no column compartment','10/21/2022 2:32:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (134,'Lisa',2,'Thermo Vanquish Neo system, no column compartment','4/24/2023 11:42:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (135,'Bart',2,'Thermo Vanquish Neo system, no column compartment','4/24/2023 11:42:00 AM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (136,'Maple',2,'Thermo/Dionex pump (800 bar) with Loading Pump. Long armed pal. LCMSnet controlled. EMSL owned.','8/23/2023 1:27:00 PM')
INSERT INTO [T_LC_Cart] (ID, Cart_Name, Cart_State_ID, Cart_Description, Created) VALUES (137,'Holly',2,'Thermo/Dionex pump (800 bar) with Loading Pump. Long armed pal. LCMSnet controlled. EMSL owned.','8/23/2023 1:27:00 PM')
SET IDENTITY_INSERT [T_LC_Cart] OFF
