/****** Object:  Table [T_MaxQuant_Mods] ******/
/****** RowCount: 550 ******/
SET IDENTITY_INSERT [T_MaxQuant_Mods] ON
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (1,'Acetyl (K)','notCterm',1120,'C(2) H(2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (2,'Acetyl (Protein N-term)','proteinNterm',1120,'C(2) H(2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (3,'Carbamidomethyl (C)','anywhere',1014,'H(3) C(2) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (4,'Oxidation (M)','anywhere',1115,'O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (5,'Phospho (STY)','anywhere',1010,'H O(3) P')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (6,'GlyGly (K)','anywhere',1021,'H(6) C(4) N(2) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (7,'Methyl (KR)','anywhere',1032,'H(2) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (8,'Dimethyl (KR)','anywhere',1208,'H(4) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (9,'Trimethyl (K)','anywhere',1188,'H(6) C(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (10,'Pro5','anywhere',null,'Cx(5) C(-5)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (11,'Pro6','anywhere',null,'Cx(5) Nx C(-5) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (12,'Glu->pyro-Glu','anyNterm',1121,'H(-2) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (13,'Gln->pyro-Glu','anyNterm',1169,'H(-3) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (14,'QQTGG (K)','notCterm',null,'H(29) C(18) N(7) O(8)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (15,'Deamidation (N)','anywhere',1127,'H(-1) N(-1) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (16,'Deamidation 18O (N)','anywhere',null,'H(-1) N(-1) Ox')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (17,'Deamidation (NQ)','anywhere',1127,'H(-1) N(-1) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (18,'Hydroxyproline','anywhere',1115,'O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (19,'Carbamyl (N-term)','anyNterm',1037,'H C N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (20,'Delta:H(2)C(2) (N-term)','anyNterm',null,'C(2) H(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (21,'Dioxidation (MW)','anywhere',1064,'O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (22,'Trioxidation (C)','anywhere',1008,'O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (23,'Dethiomethyl (M)','anywhere',1161,'H(-4) C(-1) S(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (24,'Cation:Na (DE)','anywhere',null,'H(-1) Na')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (25,'Methyl (E)','anywhere',1032,'H(2) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (26,'Dehydrated (ST)','anywhere',1121,'H(-2) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (27,'Oxidation (P)','anywhere',1115,'O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (28,'Dimethyl (K)','anywhere',1208,'H(4) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (29,'Amidated (Protein C-term)','proteinCterm',1243,'H N O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (30,'Sulfo (STY)','anywhere',1220,'S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (31,'Acetyl (N-term)','anyNterm',1120,'C(2) H(2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (32,'Amidated (C-term)','anyCterm',1243,'H N O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (33,'Sulfation (Y)','anywhere',null,'S O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (34,'Phospho (ST)','anywhere',1010,'H O(3) P')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (35,'Cys-Cys','anywhere',1272,'H(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (36,'Arg6','anywhere',null,'Cx(6) C(-6)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (37,'Arg10','anywhere',null,'Cx(6) Nx(4) C(-6) N(-4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (38,'Lys4','anywhere',null,'Hx(4) H(-4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (39,'Lys6','anywhere',null,'Cx(6) C(-6)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (40,'Lys8','anywhere',null,'Cx(6) Nx(2) C(-6) N(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (41,'DimethLys0','anywhere',1208,'H(4) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (42,'DimethNter0','anyNterm',1208,'H(4) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (43,'DimethLys4','anywhere',null,'Hx(4) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (44,'DimethNter4','anyNterm',null,'Hx(4) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (45,'DimethLys8','anywhere',null,'Hx(6) H(-2) Cx(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (46,'DimethNter8','anyNterm',null,'Hx(6) H(-2) Cx(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (47,'18O','anyCterm',null,'Ox(2) O(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (48,'ICAT-0','anywhere',1041,'H(17) C(10) N(3) O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (49,'ICAT-9','anywhere',null,'H(17) Cx(9) N(3) O(3) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (50,'ICPL-Lys0','anywhere',null,'H(3) C(6) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (51,'ICPL-Nter0','anyNterm',null,'H(3) C(6) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (52,'ICPL-Lys4','anywhere',null,'H(-1) Hx(4) C(6) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (53,'ICPL-Nter4','anyNterm',null,'H(-1) Hx(4) C(6) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (54,'ICPL-Lys6','anywhere',null,'H(3) Cx(6) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (55,'ICPL-Nter6','anyNterm',null,'H(3) Cx(6) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (56,'ICPL-Lys10','anywhere',null,'H(-1) Hx(4) Cx(6) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (57,'ICPL-Nter10','anyNterm',null,'H(-1) Hx(4) Cx(6) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (58,'mTRAQ-Lys0','anywhere',null,'H(12) C(7) N(2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (59,'mTRAQ-Nter0','anyNterm',null,'H(12) C(7) N(2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (60,'mTRAQ-Lys4','anywhere',null,'H(12) C(4) Cx(3) N Nx O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (61,'mTRAQ-Nter4','anyNterm',null,'H(12) C(4) Cx(3) N Nx O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (62,'mTRAQ-Lys8','anywhere',null,'H(12) C Cx(6) Nx(2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (63,'mTRAQ-Nter8','anyNterm',null,'H(12) C Cx(6) Nx(2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (64,'DimethLys2','anywhere',null,'H(2) Hx(2) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (65,'DimethNter2','anyNterm',null,'H(2) Hx(2) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (66,'DimethLys6','anywhere',null,'Hx(6) C(2) H(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (67,'DimethNter6','anyNterm',null,'Hx(6) C(2) H(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (68,'Leu7','anywhere',null,'C(-6) Cx(6) N(-1) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (69,'Ile7','anywhere',null,'C(-6) Cx(6) N(-1) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (70,'iTRAQ4plex-Nter114','anyNterm',1179,'H(12) C(5) Cx(2) N(2) Ox')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (71,'iTRAQ4plex-Nter115','anyNterm',1179,'H(12) C(6) Cx N Ox Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (72,'iTRAQ4plex-Nter116','anyNterm',1179,'H(12) C(4) Cx(3) N Nx O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (73,'iTRAQ4plex-Nter117','anyNterm',1179,'H(12) C(4) Cx(3) N Nx O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (74,'iTRAQ4plex-Lys114','anywhere',1179,'H(12) C(5) Cx(2) N(2) Ox')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (75,'iTRAQ4plex-Lys115','anywhere',1179,'H(12) C(6) Cx N Ox Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (76,'iTRAQ4plex-Lys116','anywhere',1179,'H(12) C(4) Cx(3) N Nx O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (77,'iTRAQ4plex-Lys117','anywhere',1179,'H(12) C(4) Cx(3) N Nx O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (78,'iTRAQ8plex-Nter113','anyNterm',1237,'H(24) C(7) Cx(7) N(3) Nx O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (79,'iTRAQ8plex-Nter114','anyNterm',1237,'H(24) C(7) Cx(7) N(3) Nx O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (80,'iTRAQ8plex-Nter115','anyNterm',1237,'H(24) C(8) Cx(6) N(2) Nx(2) O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (81,'iTRAQ8plex-Nter116','anyNterm',1237,'H(24) C(7) Cx(7) N(3) Nx O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (82,'iTRAQ8plex-Nter117','anyNterm',1237,'H(24) C(7) Cx(7) N(3) Nx O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (83,'iTRAQ8plex-Nter118','anyNterm',1237,'H(24) C(8) Cx(6) N(2) Nx(2) O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (84,'iTRAQ8plex-Nter119','anyNterm',1237,'H(24) C(8) Cx(6) N(2) Nx(2) O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (85,'iTRAQ8plex-Nter121','anyNterm',1237,'H(24) C(8) Cx(6) N(2) Nx(2) O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (86,'iTRAQ8plex-Lys113','anywhere',1237,'H(24) C(7) Cx(7) N(3) Nx O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (87,'iTRAQ8plex-Lys114','anywhere',1237,'H(24) C(7) Cx(7) N(3) Nx O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (88,'iTRAQ8plex-Lys115','anywhere',1237,'H(24) C(8) Cx(6) N(2) Nx(2) O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (89,'iTRAQ8plex-Lys116','anywhere',1237,'H(24) C(7) Cx(7) N(3) Nx O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (90,'iTRAQ8plex-Lys117','anywhere',1237,'H(24) C(7) Cx(7) N(3) Nx O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (91,'iTRAQ8plex-Lys118','anywhere',1237,'H(24) C(8) Cx(6) N(2) Nx(2) O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (92,'iTRAQ8plex-Lys119','anywhere',1237,'H(24) C(8) Cx(6) N(2) Nx(2) O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (93,'iTRAQ8plex-Lys121','anywhere',1237,'H(24) C(8) Cx(6) N(2) Nx(2) O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (94,'TMT2plex-Nter126','anyNterm',1489,'H(20) C(11) Cx N(2) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (95,'TMT2plex-Nter127','anyNterm',1489,'H(20) C(11) Cx N(2) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (96,'TMT2plex-Lys126','anywhere',1489,'H(20) C(11) Cx N(2) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (97,'TMT2plex-Lys127','anywhere',1489,'H(20) C(11) Cx N(2) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (98,'TMT6plex-Nter126','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (99,'TMT6plex-Nter127','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (100,'TMT6plex-Nter128','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (101,'TMT6plex-Nter129','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (102,'TMT6plex-Nter130','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (103,'TMT6plex-Nter131','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (104,'TMT8plex-Nter126C','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (105,'TMT8plex-Nter127N','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (106,'TMT8plex-Nter127C','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (107,'TMT8plex-Nter128C','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (108,'TMT8plex-Nter129N','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (109,'TMT8plex-Nter129C','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (110,'TMT8plex-Nter130C','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (111,'TMT8plex-Nter131N','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (112,'TMT10plex-Nter126C','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (113,'TMT10plex-Nter127N','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (114,'TMT10plex-Nter127C','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (115,'TMT10plex-Nter128N','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (116,'TMT10plex-Nter128C','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (117,'TMT10plex-Nter129N','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (118,'TMT10plex-Nter129C','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (119,'TMT10plex-Nter130N','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (120,'TMT10plex-Nter130C','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (121,'TMT10plex-Nter131N','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (122,'TMT11plex-Nter131C','anyNterm',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (123,'TMT6plex-Lys126','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (124,'TMT6plex-Lys127','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (125,'TMT6plex-Lys128','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (126,'TMT6plex-Lys129','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (127,'TMT6plex-Lys130','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (128,'TMT6plex-Lys131','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (129,'TMT8plex-Lys126C','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (130,'TMT8plex-Lys127N','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (131,'TMT8plex-Lys127C','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (132,'TMT8plex-Lys128C','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (133,'TMT8plex-Lys129N','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (134,'TMT8plex-Lys129C','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (135,'TMT8plex-Lys130C','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (136,'TMT8plex-Lys131N','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (137,'TMT10plex-Lys126C','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (138,'TMT10plex-Lys127N','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (139,'TMT10plex-Lys127C','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (140,'TMT10plex-Lys128N','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (141,'TMT10plex-Lys128C','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (142,'TMT10plex-Lys129N','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (143,'TMT10plex-Lys129C','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (144,'TMT10plex-Lys130N','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (145,'TMT10plex-Lys130C','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (146,'TMT10plex-Lys131N','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (147,'TMT11plex-Lys131C','anywhere',1267,'H(20) C(8) Cx(4) N O(2) Nx')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (148,'iodoTMT6plex-Cys126','anywhere',null,'H(28) C(12) Cx(4) N(3) Nx O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (149,'iodoTMT6plex-Cys127','anywhere',null,'H(28) C(12) Cx(4) N(3) Nx O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (150,'iodoTMT6plex-Cys128','anywhere',null,'H(28) C(12) Cx(4) N(3) Nx O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (151,'iodoTMT6plex-Cys129','anywhere',null,'H(28) C(12) Cx(4) N(3) Nx O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (152,'iodoTMT6plex-Cys130','anywhere',null,'H(28) C(12) Cx(4) N(3) Nx O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (153,'iodoTMT6plex-Cys131','anywhere',null,'H(28) C(12) Cx(4) N(3) Nx O(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (154,'HexNAc (ST)','anywhere',1053,'H(13) C(8) N O(5)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (155,'Hex(1)HexNAc(1) (ST)','anywhere',null,'C(14) H(23) O(10) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (156,'Hex (K)','anywhere',1054,'C(6) H(10) O(5)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (157,'Hex(5) HexNAc(4) NeuAc(2) (N)','anywhere',null,'C(84) H(136) O(61) N(6)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (158,'Hex(5) HexNAc(4) NeuAc(2) Sodium (N)','anywhere',null,'C(84) H(135) O(61) N(6) Na')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (159,'Ala->Arg','anywhere',null,'H(7) C(3) N(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (160,'Ala->Asn','anywhere',1037,'H C N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (161,'Ala->Asp','anywhere',1417,'C O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (162,'Ala->Cys','anywhere',1220,'S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (163,'Ala->Gln','anywhere',1014,'H(3) C(2) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (164,'Ala->Glu','anywhere',null,'H(2) C(2) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (165,'Ala->Gly','anywhere',1270,'H(-2) C(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (166,'Ala->His','anywhere',null,'H(2) C(3) N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (167,'Ala->Xle','anywhere',1188,'H(6) C(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (168,'Ala->Lys','anywhere',null,'H(7) C(3) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (169,'Ala->Met','anywhere',null,'H(4) C(2) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (170,'Ala->Phe','anywhere',null,'H(4) C(6)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (171,'Ala->Pro','anywhere',null,'H(2) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (172,'Ala->Ser','anywhere',1115,'O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (173,'Ala->Thr','anywhere',null,'H(2) C O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (174,'Ala->Trp','anywhere',null,'H(5) C(8) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (175,'Ala->Tyr','anywhere',null,'H(4) C(6) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (176,'Ala->Val','anywhere',1208,'H(4) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (177,'Arg->Ala','anywhere',null,'H(-7) C(-3) N(-3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (178,'Arg->Asn','anywhere',null,'H(-6) C(-2) N(-2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (179,'Arg->Asp','anywhere',null,'H(-7) C(-2) N(-3) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (180,'Arg->Cys','anywhere',null,'H(-7) C(-3) N(-3) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (181,'Arg->Gln','anywhere',null,'H(-4) C(-1) N(-2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (182,'Arg->Glu','anywhere',null,'H(-5) C(-1) N(-3) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (183,'Arg->Gly','anywhere',null,'H(-9) C(-4) N(-3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (184,'Arg->His','anywhere',null,'H(-5) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (185,'Arg->Lys','anywhere',1498,'N(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (186,'Arg->Met','anywhere',null,'H(-3) C(-1) N(-3) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (187,'Arg->Phe','anywhere',null,'H(-3) N(-3) C(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (188,'Arg->Pro','anywhere',null,'H(-5) C(-1) N(-3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (189,'Arg->Ser','anywhere',null,'H(-7) C(-3) N(-3) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (190,'Arg->Thr','anywhere',null,'H(-5) C(-2) N(-3) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (191,'Arg->Trp','anywhere',null,'H(-2) N(-2) C(5)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (192,'Arg->Tyr','anywhere',null,'H(-3) N(-3) C(3) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (193,'Arg->Val','anywhere',null,'H(-3) C(-1) N(-3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (194,'Arg->Xle','anywhere',null,'H(-1) N(-3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (195,'Asn->Ala','anywhere',null,'H(-1) N(-1) C(-1) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (196,'Asn->Arg','anywhere',null,'O(-1) H(6) C(2) N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (197,'Asn->Asp','anywhere',1127,'H(-1) N(-1) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (198,'Asn->Cys','anywhere',null,'H(-1) N(-1) C(-1) O(-1) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (199,'Asn->Gln','anywhere',1032,'H(2) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (200,'Asn->Glu','anywhere',null,'N(-1) H C O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (201,'Asn->Gly','anywhere',null,'H(-3) N(-1) C(-2) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (202,'Asn->His','anywhere',null,'O(-1) H C(2) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (203,'Asn->Lys','anywhere',null,'O(-1) H(6) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (204,'Asn->Met','anywhere',null,'N(-1) O(-1) H(3) C S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (205,'Asn->Phe','anywhere',null,'N(-1) O(-1) H(3) C(5)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (206,'Asn->Pro','anywhere',null,'N(-1) O(-1) H C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (207,'Asn->Ser','anywhere',null,'H(-1) N(-1) C(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (208,'Asn->Thr','anywhere',null,'N(-1) H')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (209,'Asn->Trp','anywhere',null,'O(-1) H(4) C(7)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (210,'Asn->Tyr','anywhere',null,'N(-1) H(3) C(5)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (211,'Asn->Val','anywhere',null,'N(-1) O(-1) H(3) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (212,'Asn->Xle','anywhere',null,'N(-1) O(-1) H(5) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (213,'Asp->Ala','anywhere',null,'O(-2) C(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (214,'Asp->Arg','anywhere',null,'O(-2) H(7) C(2) N(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (215,'Asp->Asn','anywhere',null,'O(-1) H N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (216,'Asp->Cys','anywhere',null,'O(-2) C(-1) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (217,'Asp->Gln','anywhere',null,'O(-1) H(3) C N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (218,'Asp->Glu','anywhere',1032,'H(2) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (219,'Asp->Gly','anywhere',null,'O(-2) C(-2) H(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (220,'Asp->His','anywhere',null,'O(-2) H(2) C(2) N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (221,'Asp->Lys','anywhere',null,'O(-2) H(7) C(2) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (222,'Asp->Met','anywhere',null,'O(-2) H(4) C S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (223,'Asp->Phe','anywhere',null,'O(-2) H(4) C(5)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (224,'Asp->Pro','anywhere',null,'O(-2) H(2) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (225,'Asp->Ser','anywhere',null,'O(-1) C(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (226,'Asp->Thr','anywhere',null,'O(-1) H(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (227,'Asp->Trp','anywhere',null,'O(-2) H(5) C(7) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (228,'Asp->Tyr','anywhere',null,'O(-1) H(4) C(5)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (229,'Asp->Val','anywhere',null,'O(-2) H(4) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (230,'Asp->Xle','anywhere',null,'O(-2) H(6) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (231,'Cys->Ala','anywhere',null,'S(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (232,'Cys->Arg','anywhere',null,'S(-1) H(7) C(3) N(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (233,'Cys->Asn','anywhere',null,'S(-1) H C N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (234,'Cys->Asp','anywhere',null,'S(-1) C O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (235,'Cys->Gln','anywhere',null,'S(-1) H(3) C(2) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (236,'Cys->Glu','anywhere',null,'S(-1) H(2) C(2) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (237,'Cys->Gly','anywhere',null,'S(-1) H(-2) C(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (238,'Cys->His','anywhere',null,'S(-1) H(2) C(3) N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (239,'Cys->Lys','anywhere',null,'S(-1) H(7) C(3) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (240,'Cys->Met','anywhere',1208,'H(4) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (241,'Cys->Phe','anywhere',null,'S(-1) H(4) C(6)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (242,'Cys->Pro','anywhere',null,'S(-1) H(2) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (243,'Cys->Ser','anywhere',null,'S(-1) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (244,'Cys->Thr','anywhere',null,'S(-1) H(2) C O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (245,'Cys->Trp','anywhere',null,'S(-1) H(5) C(8) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (246,'Cys->Tyr','anywhere',null,'S(-1) H(4) C(6) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (247,'Cys->Val','anywhere',null,'S(-1) H(4) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (248,'Cys->Xle','anywhere',null,'S(-1) H(6) C(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (249,'Gln->Ala','anywhere',null,'H(-3) C(-2) N(-1) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (250,'Gln->Arg','anywhere',null,'O(-1) H(4) C N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (251,'Gln->Asn','anywhere',1270,'H(-2) C(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (252,'Gln->Asp','anywhere',null,'H(-3) C(-1) N(-1) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (253,'Gln->Cys','anywhere',null,'H(-3) C(-2) N(-1) O(-1) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (254,'Gln->Glu','anywhere',1127,'H(-1) N(-1) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (255,'Gln->Gly','anywhere',null,'H(-5) C(-3) N(-1) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (256,'Gln->His','anywhere',null,'H(-1) O(-1) C N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (257,'Gln->Lys','anywhere',null,'O(-1) H(4) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (258,'Gln->Met','anywhere',null,'N(-1) O(-1) H S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (259,'Gln->Phe','anywhere',null,'N(-1) O(-1) H C(4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (260,'Gln->Pro','anywhere',null,'H(-1) N(-1) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (261,'Gln->Ser','anywhere',null,'H(-3) C(-2) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (262,'Gln->Thr','anywhere',null,'H(-1) C(-1) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (263,'Gln->Trp','anywhere',null,'O(-1) H(2) C(6)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (264,'Gln->Tyr','anywhere',null,'N(-1) H C(4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (265,'Gln->Val','anywhere',null,'N(-1) O(-1) H')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (266,'Gln->Xle','anywhere',null,'N(-1) O(-1) H(3) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (267,'Glu->Ala','anywhere',null,'O(-2) H(-2) C(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (268,'Glu->Arg','anywhere',null,'O(-2) H(5) C N(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (269,'Glu->Asn','anywhere',null,'O(-1) H(-1) C(-1) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (270,'Glu->Asp','anywhere',1270,'H(-2) C(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (271,'Glu->Cys','anywhere',null,'O(-2) H(-2) C(-2) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (272,'Glu->Gln','anywhere',null,'O(-1) H N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (273,'Glu->Gly','anywhere',null,'O(-2) H(-4) C(-3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (274,'Glu->His','anywhere',null,'O(-2) C N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (275,'Glu->Lys','anywhere',null,'O(-2) H(5) C N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (276,'Glu->Met','anywhere',null,'O(-2) H(2) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (277,'Glu->Phe','anywhere',null,'O(-2) H(2) C(4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (278,'Glu->Pro','anywhere',null,'O(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (279,'Glu->Ser','anywhere',null,'O(-1) H(-2) C(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (280,'Glu->Thr','anywhere',null,'O(-1) C(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (281,'Glu->Trp','anywhere',null,'O(-2) H(3) C(6) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (282,'Glu->Tyr','anywhere',null,'O(-1) H(2) C(4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (283,'Glu->Val','anywhere',null,'O(-2) H(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (284,'Glu->Xle','anywhere',null,'O(-2) H(4) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (285,'Gly->Ala','anywhere',1032,'H(2) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (286,'Gly->Arg','anywhere',null,'H(9) C(4) N(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (287,'Gly->Asn','anywhere',1014,'H(3) C(2) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (288,'Gly->Asp','anywhere',null,'H(2) C(2) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (289,'Gly->Cys','anywhere',1252,'H(2) C S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (290,'Gly->Gln','anywhere',1284,'H(5) C(3) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (291,'Gly->Glu','anywhere',null,'H(4) C(3) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (292,'Gly->His','anywhere',null,'H(4) C(4) N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (293,'Gly->Lys','anywhere',null,'H(9) C(4) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (294,'Gly->Met','anywhere',null,'H(6) C(3) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (295,'Gly->Phe','anywhere',null,'H(6) C(7)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (296,'Gly->Pro','anywhere',null,'H(4) C(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (297,'Gly->Ser','anywhere',null,'H(2) C O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (298,'Gly->Thr','anywhere',null,'H(4) C(2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (299,'Gly->Trp','anywhere',null,'H(7) C(9) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (300,'Gly->Tyr','anywhere',null,'H(6) C(7) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (301,'Gly->Val','anywhere',1188,'H(6) C(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (302,'Gly->Xle','anywhere',null,'H(8) C(4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (303,'His->Ala','anywhere',null,'H(-2) C(-3) N(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (304,'His->Arg','anywhere',null,'H(5) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (305,'His->Asn','anywhere',1234,'H(-1) C(-2) N(-1) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (306,'His->Asp','anywhere',1235,'H(-2) C(-2) N(-2) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (307,'His->Cys','anywhere',null,'H(-2) C(-3) N(-2) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (308,'His->Gln','anywhere',null,'C(-1) N(-1) H O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (309,'His->Glu','anywhere',1389,'C(-1) N(-2) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (310,'His->Gly','anywhere',null,'H(-4) C(-4) N(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (311,'His->Lys','anywhere',null,'N(-1) H(5)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (312,'His->Met','anywhere',null,'C(-1) N(-2) H(2) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (313,'His->Phe','anywhere',null,'N(-2) H(2) C(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (314,'His->Pro','anywhere',null,'C(-1) N(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (315,'His->Ser','anywhere',null,'H(-2) C(-3) N(-2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (316,'His->Thr','anywhere',null,'C(-2) N(-2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (317,'His->Trp','anywhere',null,'N(-1) H(3) C(5)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (318,'His->Tyr','anywhere',null,'N(-2) H(2) C(3) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (319,'His->Val','anywhere',null,'C(-1) N(-2) H(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (320,'His->Xle','anywhere',null,'N(-2) H(4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (321,'Lys->Ala','anywhere',null,'N(-1) H(-7) C(-3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (322,'Lys->Arg','anywhere',null,'N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (323,'Lys->Asn','anywhere',null,'H(-6) C(-2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (324,'Lys->Asp','anywhere',null,'N(-1) H(-7) C(-2) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (325,'Lys->Cys','anywhere',null,'N(-1) H(-7) C(-3) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (326,'Lys->Gln','anywhere',null,'H(-4) C(-1) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (327,'Lys->Glu','anywhere',null,'N(-1) H(-5) C(-1) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (328,'Lys->Gly','anywhere',null,'N(-1) H(-9) C(-4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (329,'Lys->His','anywhere',null,'H(-5) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (330,'Lys->Met','anywhere',null,'N(-1) H(-3) C(-1) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (331,'Lys->Phe','anywhere',null,'N(-1) H(-3) C(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (332,'Lys->Pro','anywhere',null,'N(-1) H(-5) C(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (333,'Lys->Ser','anywhere',null,'N(-1) H(-7) C(-3) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (334,'Lys->Thr','anywhere',null,'N(-1) H(-5) C(-2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (335,'Lys->Trp','anywhere',null,'H(-2) C(5)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (336,'Lys->Tyr','anywhere',null,'N(-1) H(-3) C(3) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (337,'Lys->Val','anywhere',null,'N(-1) H(-3) C(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (338,'Lys->Xle','anywhere',null,'N(-1) H(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (339,'Met->Ala','anywhere',null,'H(-4) C(-2) S(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (340,'Met->Arg','anywhere',null,'S(-1) H(3) C N(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (341,'Met->Asn','anywhere',null,'H(-3) C(-1) S(-1) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (342,'Met->Asp','anywhere',null,'H(-4) C(-1) S(-1) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (343,'Met->Cys','anywhere',null,'H(-4) C(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (344,'Met->Gln','anywhere',null,'H(-1) S(-1) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (345,'Met->Glu','anywhere',null,'H(-2) S(-1) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (346,'Met->Gly','anywhere',null,'H(-6) C(-3) S(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (347,'Met->His','anywhere',null,'H(-2) S(-1) C N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (348,'Met->Lys','anywhere',null,'S(-1) H(3) C N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (349,'Met->Phe','anywhere',null,'S(-1) C(4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (350,'Met->Pro','anywhere',1340,'H(-2) S(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (351,'Met->Ser','anywhere',null,'H(-4) C(-2) S(-1) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (352,'Met->Thr','anywhere',null,'H(-2) C(-1) S(-1) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (353,'Met->Trp','anywhere',null,'S(-1) H C(6) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (354,'Met->Tyr','anywhere',null,'S(-1) C(4) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (355,'Met->Val','anywhere',null,'S(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (356,'Met->Xle','anywhere',null,'S(-1) H(2) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (357,'Phe->Ala','anywhere',null,'H(-4) C(-6)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (358,'Phe->Arg','anywhere',null,'C(-3) H(3) N(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (359,'Phe->Asn','anywhere',null,'H(-3) C(-5) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (360,'Phe->Asp','anywhere',null,'H(-4) C(-5) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (361,'Phe->Cys','anywhere',null,'H(-4) C(-6) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (362,'Phe->Gln','anywhere',null,'H(-1) C(-4) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (363,'Phe->Glu','anywhere',null,'H(-2) C(-4) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (364,'Phe->Gly','anywhere',null,'H(-6) C(-7)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (365,'Phe->His','anywhere',null,'H(-2) C(-3) N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (366,'Phe->Lys','anywhere',null,'C(-3) H(3) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (367,'Phe->Met','anywhere',null,'C(-4) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (368,'Phe->Pro','anywhere',null,'H(-2) C(-4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (369,'Phe->Ser','anywhere',null,'H(-4) C(-6) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (370,'Phe->Thr','anywhere',null,'H(-2) C(-5) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (371,'Phe->Trp','anywhere',1266,'H C(2) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (372,'Phe->Tyr','anywhere',1115,'O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (373,'Phe->Val','anywhere',null,'C(-4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (374,'Phe->Xle','anywhere',null,'C(-3) H(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (375,'Pro->Ala','anywhere',null,'C(-2) H(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (376,'Pro->Arg','anywhere',null,'H(5) C N(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (377,'Pro->Asn','anywhere',null,'C(-1) H(-1) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (378,'Pro->Asp','anywhere',null,'C(-1) H(-2) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (379,'Pro->Cys','anywhere',null,'C(-2) H(-2) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (380,'Pro->Gln','anywhere',null,'H N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (381,'Pro->Glu','anywhere',1064,'O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (382,'Pro->Gly','anywhere',null,'C(-3) H(-4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (383,'Pro->His','anywhere',null,'C N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (384,'Pro->Lys','anywhere',null,'H(5) C N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (385,'Pro->Met','anywhere',null,'H(2) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (386,'Pro->Phe','anywhere',null,'C(4) H(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (387,'Pro->Ser','anywhere',null,'C(-2) H(-2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (388,'Pro->Thr','anywhere',1233,'C(-1) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (389,'Pro->Trp','anywhere',null,'C(6) H(3) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (390,'Pro->Tyr','anywhere',null,'C(4) H(2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (391,'Pro->Val','anywhere',null,'H(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (392,'Pro->Xle','anywhere',null,'C H(4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (393,'Ser->Ala','anywhere',null,'O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (394,'Ser->Arg','anywhere',null,'O(-1) H(7) C(3) N(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (395,'Ser->Asn','anywhere',1276,'H C N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (396,'Ser->Asp','anywhere',null,'O C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (397,'Ser->Cys','anywhere',null,'O(-1) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (398,'Ser->Gln','anywhere',null,'H(3) C(2) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (399,'Ser->Glu','anywhere',null,'O H(2) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (400,'Ser->Gly','anywhere',null,'O(-1) H(-2) C(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (401,'Ser->His','anywhere',null,'O(-1) H(2) C(3) N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (402,'Ser->Lys','anywhere',null,'O(-1) H(7) C(3) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (403,'Ser->Met','anywhere',null,'O(-1) H(4) C(2) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (404,'Ser->Phe','anywhere',null,'O(-1) H(4) C(6)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (405,'Ser->Pro','anywhere',null,'O(-1) H(2) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (406,'Ser->Thr','anywhere',1032,'H(2) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (407,'Ser->Trp','anywhere',null,'O(-1) H(5) C(8) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (408,'Ser->Tyr','anywhere',null,'H(4) C(6)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (409,'Ser->Val','anywhere',null,'O(-1) H(4) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (410,'Ser->Xle','anywhere',null,'O(-1) H(6) C(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (411,'Thr->Ala','anywhere',null,'O(-1) H(-2) C(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (412,'Thr->Arg','anywhere',null,'O(-1) H(5) C(2) N(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (413,'Thr->Asn','anywhere',null,'H(-1) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (414,'Thr->Asp','anywhere',1213,'H(-2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (415,'Thr->Cys','anywhere',null,'O(-1) H(-2) C(-1) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (416,'Thr->Gln','anywhere',1276,'H C N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (417,'Thr->Glu','anywhere',null,'O C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (418,'Thr->Gly','anywhere',null,'O(-1) H(-4) C(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (419,'Thr->His','anywhere',null,'O(-1) C(2) N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (420,'Thr->Lys','anywhere',null,'O(-1) H(5) C(2) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (421,'Thr->Met','anywhere',null,'O(-1) H(2) C S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (422,'Thr->Phe','anywhere',null,'O(-1) H(2) C(5)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (423,'Thr->Pro','anywhere',null,'O(-1) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (424,'Thr->Ser','anywhere',1270,'H(-2) C(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (425,'Thr->Trp','anywhere',null,'O(-1) H(3) C(7) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (426,'Thr->Tyr','anywhere',null,'H(2) C(5)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (427,'Thr->Val','anywhere',null,'O(-1) H(2) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (428,'Thr->Xle','anywhere',null,'O(-1) H(4) C(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (429,'Trp->Ala','anywhere',null,'H(-5) C(-8) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (430,'Trp->Arg','anywhere',null,'C(-5) H(2) N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (431,'Trp->Asn','anywhere',null,'H(-4) C(-7) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (432,'Trp->Asp','anywhere',null,'H(-5) C(-7) N(-1) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (433,'Trp->Cys','anywhere',null,'H(-5) C(-8) N(-1) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (434,'Trp->Gln','anywhere',null,'H(-2) C(-6) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (435,'Trp->Glu','anywhere',null,'H(-3) C(-6) N(-1) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (436,'Trp->Gly','anywhere',null,'H(-7) C(-9) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (437,'Trp->His','anywhere',null,'H(-3) C(-5) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (438,'Trp->Lys','anywhere',null,'C(-5) H(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (439,'Trp->Met','anywhere',null,'H(-1) C(-6) N(-1) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (440,'Trp->Phe','anywhere',null,'H(-1) C(-2) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (441,'Trp->Pro','anywhere',null,'H(-3) C(-6) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (442,'Trp->Ser','anywhere',null,'H(-5) C(-8) N(-1) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (443,'Trp->Thr','anywhere',null,'H(-3) C(-7) N(-1) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (444,'Trp->Tyr','anywhere',1234,'H(-1) C(-2) N(-1) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (445,'Trp->Val','anywhere',null,'H(-1) C(-6) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (446,'Trp->Xle','anywhere',null,'C(-5) N(-1) H')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (447,'Tyr->Ala','anywhere',null,'C(-6) H(-4) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (448,'Tyr->Arg','anywhere',null,'C(-3) O(-1) H(3) N(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (449,'Tyr->Asn','anywhere',null,'C(-5) H(-3) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (450,'Tyr->Asp','anywhere',null,'C(-5) H(-4) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (451,'Tyr->Cys','anywhere',null,'C(-6) H(-4) O(-1) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (452,'Tyr->Gln','anywhere',null,'C(-4) H(-1) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (453,'Tyr->Glu','anywhere',null,'C(-4) H(-2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (454,'Tyr->Gly','anywhere',null,'C(-7) H(-6) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (455,'Tyr->His','anywhere',null,'C(-3) H(-2) O(-1) N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (456,'Tyr->Lys','anywhere',null,'C(-3) O(-1) H(3) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (457,'Tyr->Met','anywhere',null,'C(-4) O(-1) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (458,'Tyr->Phe','anywhere',null,'O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (459,'Tyr->Pro','anywhere',null,'C(-4) H(-2) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (460,'Tyr->Ser','anywhere',null,'C(-6) H(-4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (461,'Tyr->Thr','anywhere',null,'C(-5) H(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (462,'Tyr->Trp','anywhere',null,'O(-1) H C(2) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (463,'Tyr->Val','anywhere',null,'C(-4) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (464,'Tyr->Xle','anywhere',null,'C(-3) O(-1) H(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (465,'Val->Ala','anywhere',null,'C(-2) H(-4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (466,'Val->Arg','anywhere',null,'C H(3) N(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (467,'Val->Asn','anywhere',null,'C(-1) H(-3) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (468,'Val->Asp','anywhere',null,'C(-1) H(-4) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (469,'Val->Cys','anywhere',null,'C(-2) H(-4) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (470,'Val->Gln','anywhere',1060,'H(-1) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (471,'Val->Glu','anywhere',null,'H(-2) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (472,'Val->Gly','anywhere',null,'C(-3) H(-6)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (473,'Val->His','anywhere',null,'H(-2) C N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (474,'Val->Lys','anywhere',null,'H(3) C N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (475,'Val->Met','anywhere',1220,'S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (476,'Val->Phe','anywhere',null,'C(4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (477,'Val->Pro','anywhere',1173,'H(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (478,'Val->Ser','anywhere',null,'C(-2) H(-4) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (479,'Val->Thr','anywhere',null,'C(-1) H(-2) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (480,'Val->Trp','anywhere',null,'H C(6) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (481,'Val->Tyr','anywhere',null,'C(4) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (482,'Val->Xle','anywhere',null,'C H(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (483,'Xle->Ala','anywhere',null,'C(-3) H(-6)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (484,'Xle->Arg','anywhere',null,'H N(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (485,'Xle->Asn','anywhere',null,'C(-2) H(-5) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (486,'Xle->Asp','anywhere',null,'C(-2) H(-6) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (487,'Xle->Cys','anywhere',null,'C(-3) H(-6) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (488,'Xle->Gln','anywhere',null,'C(-1) H(-3) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (489,'Xle->Glu','anywhere',null,'C(-1) H(-4) O(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (490,'Xle->Gly','anywhere',null,'C(-4) H(-8)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (491,'Xle->His','anywhere',null,'H(-4) N(2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (492,'Xle->Lys','anywhere',1170,'H N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (493,'Xle->Met','anywhere',null,'C(-1) H(-2) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (494,'Xle->Phe','anywhere',null,'H(-2) C(3)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (495,'Xle->Pro','anywhere',null,'C(-1) H(-4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (496,'Xle->Ser','anywhere',null,'C(-3) H(-6) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (497,'Xle->Thr','anywhere',null,'C(-2) H(-4) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (498,'Xle->Trp','anywhere',null,'H(-1) C(5) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (499,'Xle->Tyr','anywhere',null,'H(-2) C(3) O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (500,'Xle->Val','anywhere',null,'C(-1) H(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (501,'CamCys->Ala','anywhere',null,'S(-1) H(-3) C(-2) N(-1) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (502,'CamCys->Arg','anywhere',null,'S(-1) H(4) C N(2) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (503,'CamCys->Asn','anywhere',null,'S(-1) H(-2) C(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (504,'CamCys->Asp','anywhere',null,'S(-1) O H(-3) C(-1) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (505,'CamCys->Gln','anywhere',null,'S(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (506,'CamCys->Glu','anywhere',null,'S(-1) O H(-1) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (507,'CamCys->Gly','anywhere',null,'S(-1) H(-5) C(-3) N(-1) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (508,'CamCys->His','anywhere',null,'S(-1) C N H(-1) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (509,'CamCys->Lys','anywhere',null,'S(-1) H(4) C O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (510,'CamCys->Met','anywhere',null,'H N(-1) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (511,'CamCys->Phe','anywhere',null,'S(-1) H C(4) N(-1) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (512,'CamCys->Pro','anywhere',null,'S(-1) H(-1) N(-1) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (513,'CamCys->Ser','anywhere',null,'S(-1) H(-3) C(-2) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (514,'CamCys->Thr','anywhere',null,'S(-1) H(-1) C(-1) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (515,'CamCys->Trp','anywhere',null,'S(-1) H(3) C(6) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (516,'CamCys->Tyr','anywhere',null,'S(-1) H C(4) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (517,'CamCys->Val','anywhere',null,'S(-1) H N(-1) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (518,'CamCys->Xle','anywhere',null,'S(-1) H(3) C N(-1) O(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (519,'Ala->CamCys','anywhere',null,'S H(3) C(2) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (520,'Arg->CamCys','anywhere',null,'H(-4) C(-1) N(-2) S O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (521,'Asn->CamCys','anywhere',null,'S H(2) C')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (522,'Asp->CamCys','anywhere',null,'O(-1) S H(3) C N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (523,'Gln->CamCys','anywhere',1220,'S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (524,'Glu->CamCys','anywhere',null,'O(-1) S H N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (525,'Gly->CamCys','anywhere',null,'H(5) C(3) S N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (526,'His->CamCys','anywhere',null,'C(-1) N(-1) S H O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (527,'Lys->CamCys','anywhere',null,'H(-4) C(-1) S O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (528,'Met->CamCys','anywhere',1060,'H(-1) N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (529,'Phe->CamCys','anywhere',null,'H(-1) C(-4) S N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (530,'Pro->CamCys','anywhere',null,'S H N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (531,'Ser->CamCys','anywhere',null,'S H(3) C(2) N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (532,'Thr->CamCys','anywhere',null,'S H C N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (533,'Trp->CamCys','anywhere',null,'H(-2) C(-6) S O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (534,'Tyr->CamCys','anywhere',null,'C(-4) H(-1) S N')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (535,'Val->CamCys','anywhere',null,'H(-1) S N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (536,'Xle->CamCys','anywhere',null,'C(-1) H(-3) S N O')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (537,'Thioacyl (DSP)','anywhere',null,'C(3) H(4) O S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (538,'K2020','anywhere',null,'Cx(2) C(-2) Nx(2) N(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (539,'K0400','anywhere',null,'Hx(4) H(-4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (540,'K6020','anywhere',null,'Cx(6) C(-6) Nx(2) N(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (541,'K5210','anywhere',null,'Cx(5) C(-5) Hx(2) H(-2) Nx(1) N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (542,'K3410','anywhere',null,'Cx(3) C(-3) Hx(4) H(-4) Nx N(-1)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (543,'K4400','anywhere',null,'Cx(4) C(-4) Hx(4) H(-4)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (544,'K0800','anywhere',null,'Hx(8) H(-8)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (545,'K6420','anywhere',null,'Cx(6) C(-6) Hx(4) H(-4) Nx(2) N(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (546,'K1920','anywhere',null,'Cx(1) C(-1) Hx(9) H(-9) Nx(2) N(-2)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (547,'K3900','anywhere',null,'Cx(3) C(-3) Hx(9) H(-9)')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (548,'Cysteinyl','anywhere',1312,'H(5) C(3) N O(2) S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (549,'Cysteinyl - carbamidomethyl','anywhere',null,'H(2) O C S')
INSERT INTO [T_MaxQuant_Mods] (Mod_ID, Mod_Title, Mod_Position, Mass_Correction_ID, Composition) VALUES (550,'Oxidation (MP)','anywhere',1115,'O')
SET IDENTITY_INSERT [T_MaxQuant_Mods] OFF
