/****** Object:  Table [dbo].[T_MiscPaths] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_MiscPaths](
	[TMP_ID] [int] IDENTITY(1,1) NOT NULL,
	[Server] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Client] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Function] [char](32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_T_MiscPaths] PRIMARY KEY CLUSTERED 
(
	[TMP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_T_MiscPaths_Function] ******/
CREATE NONCLUSTERED INDEX [IX_T_MiscPaths_Function] ON [dbo].[T_MiscPaths]
(
	[Function] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO
