/****** Object:  Table [T_Predefined_Analysis_Scheduling_Rules] ******/
/****** RowCount: 9 ******/
SET IDENTITY_INSERT [T_Predefined_Analysis_Scheduling_Rules] ON
INSERT INTO [T_Predefined_Analysis_Scheduling_Rules] (SR_evaluationOrder, SR_instrumentClass, SR_instrument_Name, SR_dataset_Name, SR_analysisToolName, SR_priority, SR_processorGroupID, SR_enabled, SR_Created, ID) VALUES (10,'','LTQ%','QC%','%Sequest%',1,100,1,'6/22/2005 4:27:39 PM',101)
INSERT INTO [T_Predefined_Analysis_Scheduling_Rules] (SR_evaluationOrder, SR_instrumentClass, SR_instrument_Name, SR_dataset_Name, SR_analysisToolName, SR_priority, SR_processorGroupID, SR_enabled, SR_Created, ID) VALUES (13,'','','QC%','%XTandem%',1,100,0,'3/6/2006 7:05:22 PM',103)
INSERT INTO [T_Predefined_Analysis_Scheduling_Rules] (SR_evaluationOrder, SR_instrumentClass, SR_instrument_Name, SR_dataset_Name, SR_analysisToolName, SR_priority, SR_processorGroupID, SR_enabled, SR_Created, ID) VALUES (15,'LTQ_FT','','','%MASIC%',1,115,0,'8/23/2007 1:30:56 PM',106)
INSERT INTO [T_Predefined_Analysis_Scheduling_Rules] (SR_evaluationOrder, SR_instrumentClass, SR_instrument_Name, SR_dataset_Name, SR_analysisToolName, SR_priority, SR_processorGroupID, SR_enabled, SR_Created, ID) VALUES (11,'','LTQ%','SE_QC%','%Sequest%',1,100,1,'4/11/2008 3:44:44 PM',108)
INSERT INTO [T_Predefined_Analysis_Scheduling_Rules] (SR_evaluationOrder, SR_instrumentClass, SR_instrument_Name, SR_dataset_Name, SR_analysisToolName, SR_priority, SR_processorGroupID, SR_enabled, SR_Created, ID) VALUES (14,'LTQ_FT','','mouseUSA%','%MASIC%',4,115,0,'10/6/2008 2:55:03 PM',110)
INSERT INTO [T_Predefined_Analysis_Scheduling_Rules] (SR_evaluationOrder, SR_instrumentClass, SR_instrument_Name, SR_dataset_Name, SR_analysisToolName, SR_priority, SR_processorGroupID, SR_enabled, SR_Created, ID) VALUES (10,'Finnigan_Ion_Trap','LTQ%','GLBRC_Sc%','%Sequest%',2,135,1,'10/5/2009 2:25:53 PM',112)
INSERT INTO [T_Predefined_Analysis_Scheduling_Rules] (SR_evaluationOrder, SR_instrumentClass, SR_instrument_Name, SR_dataset_Name, SR_analysisToolName, SR_priority, SR_processorGroupID, SR_enabled, SR_Created, ID) VALUES (10,'LTQ_FT','LTQ%','EIF_AIMS%','%Sequest%',2,109,1,'10/5/2009 2:31:28 PM',113)
INSERT INTO [T_Predefined_Analysis_Scheduling_Rules] (SR_evaluationOrder, SR_instrumentClass, SR_instrument_Name, SR_dataset_Name, SR_analysisToolName, SR_priority, SR_processorGroupID, SR_enabled, SR_Created, ID) VALUES (12,'LTQ_FT','','BATS%','%Sequest%',3,117,1,'11/8/2010 10:19:23 AM',114)
INSERT INTO [T_Predefined_Analysis_Scheduling_Rules] (SR_evaluationOrder, SR_instrumentClass, SR_instrument_Name, SR_dataset_Name, SR_analysisToolName, SR_priority, SR_processorGroupID, SR_enabled, SR_Created, ID) VALUES (13,'','','QC%','%MSGFPlus%',1,100,1,'2/28/2014 10:09:27 AM',118)
SET IDENTITY_INSERT [T_Predefined_Analysis_Scheduling_Rules] OFF
