/****** Object:  Table [T_Sample_Labelling] ******/
/****** RowCount: 19 ******/
/****** Columns: Label, ID ******/
INSERT INTO [T_Sample_Labelling] VALUES ('12C/13C',18)
INSERT INTO [T_Sample_Labelling] VALUES ('Cleavable ICAT',8)
INSERT INTO [T_Sample_Labelling] VALUES ('ICAT',3)
INSERT INTO [T_Sample_Labelling] VALUES ('iTRAQ',14)
INSERT INTO [T_Sample_Labelling] VALUES ('iTRAQ8',15)
INSERT INTO [T_Sample_Labelling] VALUES ('Leu_C13N15',11)
INSERT INTO [T_Sample_Labelling] VALUES ('N14/N15',2)
INSERT INTO [T_Sample_Labelling] VALUES ('none',1)
INSERT INTO [T_Sample_Labelling] VALUES ('O18',6)
INSERT INTO [T_Sample_Labelling] VALUES ('PEO-Biotin',5)
INSERT INTO [T_Sample_Labelling] VALUES ('Phe_C13',12)
INSERT INTO [T_Sample_Labelling] VALUES ('PhIAT',4)
INSERT INTO [T_Sample_Labelling] VALUES ('PhIST',10)
INSERT INTO [T_Sample_Labelling] VALUES ('SP-ICAT',9)
INSERT INTO [T_Sample_Labelling] VALUES ('Sulfo-NHS-LC-Biotin',7)
INSERT INTO [T_Sample_Labelling] VALUES ('TMT10',19)
INSERT INTO [T_Sample_Labelling] VALUES ('TMT2',16)
INSERT INTO [T_Sample_Labelling] VALUES ('TMT6',17)
INSERT INTO [T_Sample_Labelling] VALUES ('Unknown',0)
