/****** Object:  Table [T_Separation_Group] ******/
/****** RowCount: 66 ******/
/****** Columns: Sep_Group, Comment, Active, Sample_Prep_Visible, Fraction_Count ******/
INSERT INTO [T_Separation_Group] VALUES ('CE','',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('Evosep_Whisper_20_SPD_60min','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('Evosep_Whisper_40_SPD_30min','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('GC','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('Glycans','',0,0,0)
INSERT INTO [T_Separation_Group] VALUES ('Infusion','Direction infusion',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-2D-Custom','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-2D-Formic','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-2D-HILIC','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Acetylome','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Agilent-2D-Intact','',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Eksigent','',0,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Formic_100min','',0,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Formic_150min','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Formic_1hr','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Formic_2hr','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Formic_30min','',0,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Formic_3hr','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Formic_45min','',0,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Formic_4hr','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Formic_5hr','',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Formic_80min','',0,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Formic_90min','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-GlcNAc','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-HiFlow','High flow LC (analytical LC)',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-HILIC','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-IMER-ND_2hr','',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-IMER-ND_3hr','',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-IMER_2hr','',0,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-IMER_3hr','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-IMER_5hr','',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-IntactProtein_200min','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-IonPairing','',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Metabolomics_LipidSoluble','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Metabolomics_LipidSoluble_25MinGradient','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Metabolomics_Oxylipids','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Metabolomics_Sonnenburg','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Metabolomics_WaterSoluble','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-MicroHpH-12','Use for placeholder requested runs that can be converted into requested run fractions',1,0,12)
INSERT INTO [T_Separation_Group] VALUES ('LC-MicroHpH-24','Use for placeholder requested runs that can be converted into requested run fractions',1,0,24)
INSERT INTO [T_Separation_Group] VALUES ('LC-MicroHpH-4','Use for placeholder requested runs that can be converted into requested run fractions',1,0,4)
INSERT INTO [T_Separation_Group] VALUES ('LC-MicroHpH-6','Use for placeholder requested runs that can be converted into requested run fractions',1,0,6)
INSERT INTO [T_Separation_Group] VALUES ('LC-MicroHpH-96','Use for placeholder requested runs that can be converted into requested run fractions',1,0,96)
INSERT INTO [T_Separation_Group] VALUES ('LC-MicroSCX-12','Use for placeholder requested runs that can be converted into requested run fractions',1,0,12)
INSERT INTO [T_Separation_Group] VALUES ('LC-MicroSCX-6','Use for placeholder requested runs that can be converted into requested run fractions',1,0,6)
INSERT INTO [T_Separation_Group] VALUES ('LC-NanoHpH-12','Use for placeholder requested runs that can be converted into requested run fractions',1,0,12)
INSERT INTO [T_Separation_Group] VALUES ('LC-NanoHpH-24','Use for placeholder requested runs that can be converted into requested run fractions',1,0,24)
INSERT INTO [T_Separation_Group] VALUES ('LC-NanoHpH-6','Use for placeholder requested runs that can be converted into requested run fractions',1,0,6)
INSERT INTO [T_Separation_Group] VALUES ('LC-NanoHpH-96','Use for placeholder requested runs that can be converted into requested run fractions',1,0,96)
INSERT INTO [T_Separation_Group] VALUES ('LC-NanoPot_100min','NanoPot separations',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-NanoPot_1hr','NanoPot separations',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-NanoPot_2hr','NanoPot separations',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-NanoPot_30min','NanoPot separations',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-NanoPot_3hr','NanoPot separations',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-NanoSCX-12','Use for placeholder requested runs that can be converted into requested run fractions',1,0,12)
INSERT INTO [T_Separation_Group] VALUES ('LC-NanoSCX-6','Use for placeholder requested runs that can be converted into requested run fractions',1,0,6)
INSERT INTO [T_Separation_Group] VALUES ('LC-PCR-Tube','',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Phospho','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-PRISM','',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-ReproSil-75um','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-TFA_100minute','',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Waters-NH4HCO2','',1,0,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Waters_High_pH','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('LC-Waters_Neutral','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('Other','',1,1,0)
INSERT INTO [T_Separation_Group] VALUES ('RapidFire-SPE','',1,1,0)
