/****** Object:  Table [T_Seq_Local_Symbols_List] ******/
/****** RowCount: 24 ******/
/****** Columns: Local_Symbol_ID, Local_Symbol, Local_Symbol_Comment ******/
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (0,'-','No modification symbol')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (1,'*','First dynamic mod in Sequest')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (2,'#','Second dynamic mod in Sequest')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (3,'@','Third dynamic mod in Sequest')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (4,'$','Fourth dynamic mod in X!Tandem; Sixth dynamic mod in Sequest v.27 (rev. 12)')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (5,'&','Fifth dynamic mod in X!Tandem')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (6,'!','Only used by X!Tandem')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (7,'%','Only used by X!Tandem')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (8,'[','Sequest uses this for peptide C-terminus dynamic mods')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (9,']','Sequest uses this for peptide N-terminus dynamic mods')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (10,'^','Fourth dynamic mod in Sequest v.27 (rev. 12)')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (11,'~','Fifth dynamic mod in Sequest v.27 (rev. 12)')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (12,'†','Additional dynamic mod supported by PHRP')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (13,'‡','Additional dynamic mod supported by PHRP')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (14,'¤','Additional dynamic mod supported by PHRP')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (15,'º','Additional dynamic mod supported by PHRP')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (16,'`','Additional dynamic mod supported by PHRP')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (17,'×','Additional dynamic mod supported by PHRP')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (18,'÷','Additional dynamic mod supported by PHRP')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (19,'ø','Additional dynamic mod supported by PHRP')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (20,'¢','Additional dynamic mod supported by PHRP')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (21,'=','Additional dynamic mod supported by PHRP')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (22,'+','Additional dynamic mod supported by PHRP')
INSERT INTO [T_Seq_Local_Symbols_List] VALUES (23,'_','Additional dynamic mod supported by PHRP')
