/****** Object:  Database [DMSHistoricLogCapture] ******/
CREATE DATABASE [DMSHistoricLogCapture] ON  PRIMARY 
( NAME = N'DMSHistLogCapture_dat', FILENAME = N'C:\SQLServerData\DMSHistLogCapture_data.mdf' , SIZE = 14736640KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'DMSHistLogCapture_log', FILENAME = N'H:\SQLServerData\DMSHistLogCapture_log.ldf' , SIZE = 5248KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
ALTER DATABASE [DMSHistoricLogCapture] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DMSHistoricLogCapture].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DMSHistoricLogCapture] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET ANSI_NULLS ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET ANSI_PADDING ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET ARITHABORT ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET  READ_WRITE 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET  MULTI_USER 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DMSHistoricLogCapture] SET DB_CHAINING OFF 
GO
GRANT CONNECT TO [pnl\d3m580] AS [dbo]
GO
