/****** Object:  Database [DMSHistoricLogCapture] ******/
CREATE DATABASE [DMSHistoricLogCapture]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DMSHistLogCapture_dat', FILENAME = N'J:\SQLServerData\DMSHistoricLogCapture.mdf' , SIZE = 14736640KB , MAXSIZE = UNLIMITED, FILEGROWTH = 262144KB )
 LOG ON 
( NAME = N'DMSHistLogCapture_log', FILENAME = N'H:\SQLServerData\DMSHistoricLogCapture_log.ldf' , SIZE = 5605504KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DMSHistoricLogCapture].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DMSHistoricLogCapture] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET ANSI_NULLS ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET ANSI_PADDING ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET ARITHABORT ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET  MULTI_USER 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DMSHistoricLogCapture] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DMSHistoricLogCapture] SET DELAYED_DURABILITY = DISABLED 
GO
USE [DMSHistoricLogCapture]
GO
/****** Object:  User [PNL\D3M578] ******/
CREATE USER [PNL\D3M578] FOR LOGIN [PNL\D3M578] WITH DEFAULT_SCHEMA=[PNL\D3M578]
GO
/****** Object:  User [PNL\D3M580] ******/
CREATE USER [PNL\D3M580] FOR LOGIN [PNL\D3M580] WITH DEFAULT_SCHEMA=[PNL\D3M580]
GO
/****** Object:  User [RBAC-DMS_Developer] ******/
CREATE USER [RBAC-DMS_Developer] FOR LOGIN [PNL\EMSL-Prism.Users.Developers]
GO
GRANT SHOWPLAN TO [DDL_Viewer] AS [dbo]
GO
GRANT CONNECT TO [RBAC-DMS_Developer] AS [dbo]
GO
ALTER DATABASE [DMSHistoricLogCapture] SET  READ_WRITE 
GO
